Automattic/newspack-popups

src/editor/index.js

I was getting missing file errors [because the editor css file wasn't getting built](https://github.com/Automattic/newspack-popups/blob/2b0652007d304e1bfd7191d9346b2bf0105da42a/includes/class-newspack-popups.php#L147). It's an empty file, but I assumed we'd probably add some CSS at some point, so I didn't just remove it.
1. Before checking this PR out, `npm run clean && npm run build`. Observe missing file error when trying to create a pop up and missing file in `dist` folder.
2. Check PR out, repeat above process, observe error goes away and file exists.

Include style file so it gets compiled

---

src/editor/index.js

This branch moves the popup CPT options to the Document sidebar. Previously they were located in a sidebar specifically for the post type, which led to discoverability problems.
1. Check out the branch, run `npm run build:webpack`
2. Click `Pop-ups` in the admin navigation and create a new Popup.
3. Open the Document sidebar (if it isn't open already), and verify it  has a Pop-up Settings panel, with Trigger, Frequency, and Placement options.
4. Make changes to the settings, save the post, and verify the changes stick.

Move Options to Document Sidebar

---

includes/class-newspack-popups.php

This  changes the `$post_type` to a more description  string: `newspack_popups_cpt`. The CPT labels are all included as well, so there should no longer be any references to  "Post" on Pop-up  edit pages.
Closes https://github.com/Automattic/newspack-popups/issues/13.
1. Verify pop-ups can be created and work properly in the front end. (Note that any existing Pop-ups will be lost after switching to this branch)
2. Verify that all text referring to Pop-ups shows the word "pop-up" rather than  "post." For example, page title when editing  a Pop-up, "No pop-ups found", "Search pop-ups" button, etc.

Improvements To Custom Post Type Definition

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups.php

Adds category filtering to Pop-ups. The Pop-up CPT  now allows category selection, and these will be used to determine the rules for which pop-ups appear on which posts. 
- If a post has one or more categories assigned, the most recent Pop-up with any of those categories will be shown. 
- If no Pop-ups have the same categories as  the post, the most recent Pop-up with no categories will be shown. This is called the "Sitewide" pop-up.
Two questions:
1) To query for Pop-ups with no  categories I've used this logic:
```
$args['category__not_in'] = get_terms(
'category',
[
'fields' => 'ids',
]
);
```
This may be inefficient if there are a large number of categories. Is there a better way to structure this query?
2) In working on this, I noticed that the `the_content` hook fires twice. Is this …

Category Filtering

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups.php
src/editor/index.js

Newsletter links often have a `utm_source` query parameter to track the source of the traffic. Based on this parameter we can make the assumption that a site visitor is already a newsletter subscriber, and suppress all pop-ups to avoid annoying the user with a call to action they have already taken. In the Pop-up settings pane there is a new `UTM Suppression` text field. When a request contains the `utm_source` param, a transient is updated that links the value to the user by their AMP Reader ID. The `amp-access` API call checks to see if  the current Pop-up has UTM Suppression defined, and if so if the current user came in through that code. If a match is found, the user will never be shown the pop-up. 
cc: @tristanloper 
1. Create a Pop-up. Trigger by Scroll Progress, set Scroll …

utm_source Pop-up Suppression

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups.php
src/editor/index.js
src/view/style.scss

The Overlay is now clickable/dismiss-able in addition to the close button. Clicking the overlay behind the pop-up should have exactly the same  effect as clicking the close button - the popup is dismissed, and the `newspack-popups/v1/reader` API is called. There is also an overlay opacity range control, which can be set from 0-100.
cc: @tristanloper 
1. Create a pop-up with Frequency=Every Page View, Trigger=Scroll Progress, Scroll Progress=20. 
2. View the site in an incognito window, and navigate to any single post. The popup should appear as you scroll down.
3. Click the background and verify the Pop-up is dismissed.
4. Alter the overlay opacity setting, and verify the change.
5. Change the Frequency to "Once A Day."
6. View a post, the popup should appear. Click the overlay to …

Overlay Improvements

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups.php
src/editor/index.js
src/view/style.scss

Adds an optional button that dismisses the pop-up forever. When editing the Pop-up the document sidebar now has a `Text for "Not Interested" button`  field. If  this is populated, there will be a light button at the bottom of the popup with that text. Clicking the button dismisses the popup with a special `dismiss_forever` flag that will cause it to never be shown again to the current user.
cc: @tristanloper 
1. Create a popup with Trigger=Scroll, Scroll Progress=20%, Frequency=Every Page View, Text for "Not Interested" button="I'm not interested."
2. View the site incognito, navigate to a Post, scroll down until you see the popup. 
3. Verify the button at the bottom of the popup.
4. Click the button. Verify popup is dismissed.
5. Navigate to any other page, verify the popup does not show …

Dismiss Button

---

includes/class-newspack-popups-inserter.php

This is a simple one...
It just adds a class of `newspack-popup-title` to the `h1` used for the title.
1. Switch to this branch
2. Load a post with the pop-up and inspect the title. Does it have the class?

Add a class the the `h1` title so it can easily be targeted by a theme

---

src/view/style.scss

Reset the margins of the elements inside the pop-up.
__Before__
__After__
1. Check a post with the pop-up
2. switch to this branch and run `npm run build`
3. refresh your post and notice the slight difference

Fix the margin bottom/top of the elements within the `.newspack-popup`

---

src/view/style.scss

In order to differentiate the pop-up from the content, I added a very subtle shadow to the wrapper. It's the most noticeable when the overlay opacity is set to 0.
__Before:__
__After:__
1. load a post with the popup
2. switch to this branch and run `npm run build`
3. reload the post, do you notice the shadow?

Add a very subtle box-shadow to `.newspack-popup-wrapper`

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php

After a successful Mailchimp signup, popups should not be shown again. This PR, combined with [recent additions to the Jetpack Mailchimp Block](https://github.com/Automattic/jetpack/pull/14050), will respond to a successful signup and suppress future popups. 
This is done using `amp-state` as follows:
- Upon successful form submission from the JP Mailchimp block, AMP state is updated: https://github.com/Automattic/jetpack/blob/master/extensions/blocks/mailchimp/mailchimp.php#L92
- `AMP.state.mailing_list_status` is reflected in hidden form elements in all of the forms associated with the popup.
- When the popup is hidden, the form is submitted and the API endpoint understands `mailing_list_status` to mean this user should never see a popup again. 
This functionality requires the most …

Suppress Popups After Mailchimp Signup

---

includes/class-newspack-popups-inserter.php

This PR registers and enqueues the AMP scripts so that they will be loaded in  non-AMP requests, even if the AMP plugin is not installed.
1. Create a Pop-Up, in an incognito window verify that it reveals and behaves normally in an AMP request.
2. Switch AMP mode to Transitional, test that behavior is identical in AMP and non-AMP requests.
3. Do the same in Reader Mode.
4. Disable the AMP plugin, then re-test a page. It should behave just like the AMP version.

Support For Non-AMP Requests

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php

This PR places Timed Pop-ups on non-posts, including Homepage, Pages, Category Archives, Author Archives, and Search Results. The hook used to place on Archive pages is specific to Newspack Theme, so for the moment, popups  will only appear on those pages if Newspack is the active theme. The  new logic applies only to Pop-ups with a timer trigger. Scroll triggers only work in posts, because the trigger point placement is calculated based on normal paragraph-based content.
1. With Newspack as the theme, create  a Pop-up, set Trigger: Timer, Delay: 1s, Frequency: Every Page View. 
2. In an incognito window, view homepage,  another page, a  category archive, an author archive, search results, and a post. The popup should appear on all of these.
3. Change the popup's Trigger to "Scroll …

Popups  On Non-Posts

---

includes/class-newspack-popups-api.php
src/editor/index.js

The "Every Page View" Frequency option was included to make testing easier while the plugin was in development. In real-world situations it enables aggressive overuse of popups which we want to avoid. In this PR the option is removed.
Build the plugin, verify the "Every Page View" Frequency option is no longer available. View several pages incognito and verify that any Pop-up appears at most once a day.

Remove "Every Page View" Frequency Option

---

includes/class-newspack-popups-model.php

After creating a new popup, all values were set to empty strings.
1. create a new popup
2. it should have `'test'` frequency by default, so it should appear right away without updating popup settings

Fix: default values

---

src/view/style.scss

By adding a padding-top we avoid having the top part of the pop-up being behind the admin bar. 
Closes #38.
1. Make sure you're logged in. Use a Pop-up in Test mode.
2. You can either: use the top placement, or have a pop-up with lots of content
3. Check a post. The pop-up should be displayed behind the admin bar at the top.
4. Switch to this branch.
5. Refresh your post. It should now be below the admin bar.

Add padding to the pop-up when admin bar is available

---

src/view/style.scss

Simplify the CSS for the buttons so the style will rely on the active theme. Also making sure some properties are not being overridden by the theme.
Closes #37  .
1. Switch to this branch
2. Try different themes
3. Does the pop-up look ok?

Update default style with more generic buttons and rely on current theme

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/index.js

Adds a checkbox to determine if Pop-up title is displayed. 
Closes https://github.com/Automattic/newspack-popups/issues/40
1. Create one Pop-up, Trigger=Timer, Delay=1, Frequency=Test Mode.
2. Open the site homepage, verify it appears without the title.
3. Edit the Pop-up and check `Display Pop-up Title`.
4. Open the site homepage again, verify the Pop-up appears with the title.

Toggle Pop-up Title Display

---

src/editor/index.js

Problem: the `newspack_popups_is_sitewide_default` on a post should be updated on save, like a meta field.  
How it works here - on save:
- the request is sent to `/sitewide_default/:id` endpoint
- post is saved
But `newspack_popups_is_sitewide_default` value in post save payload is ignored, so the response has stale value of `newspack_popups_is_sitewide_default`. Before, post save always happened after `/sitewide_default/:id` request has completed, so there was not such problem.

save sitewide_default on component update

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/index.js
src/editor/utils.js

"Sitewide Default" refers to the Pop-up that is shown on any page, assuming there is no better match based on category filters. Currently this will be the newest published Pop-up with no category assignments. This logic is awkward:
- Sometimes it is unclear why a particular Pop-up has this status. 
- Setting a different sitewide default requires changing the published date of the post, which is a bit janky. 
- As the display logic becomes richer (e.g. [referrer filters](https://github.com/Automattic/newspack-popups/issues/48)) this approach will quickly become untenable. 
- The current approach is effectively a blocker on https://github.com/Automattic/newspack-plugin/pull/409, and this change frees that work to proceed.
This PR clarifies this logic by storing the ID of the sitewide …

Refactor Sitewide Default

---

includes/class-newspack-popups-model.php

Quick fix needed to properly rendering the Popups UI in https://github.com/Automattic/newspack-plugin/pull/409. 
This is difficult to test. It could be tested by:
- Create a Popup, check the box to make it Sitewide Default, Publish.
- In any of the PHP files add this to the bottom:
```
add_action( 'init', function() {
var_dump( Newspack_Popups_Model::retrieve_popups() );
die();
} );
```
- Load a page, inspect the output, verify that `sitewide_default` is `true` for the correct Pop-up.

Fix Sitewide Default Setting In Pop-up List

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/index.js
src/editor/utils.js
src/view/style.scss

Adds a background color picker for Pop-ups, with a default of white.
Closes https://github.com/Automattic/newspack-popups/issues/49
- Will this feature make it too easy to produce unattractive Pop-ups? Should there be any restrictions on it?
- There is a border around Pop-up that I'm having trouble tracking down. Is this problematic? 
- I moved the background color from `newspack-popup` to `newspack-popup-wrapper`. Any issue with this?
1. Create a Pop-up, Trigger=Timer, Delay=1, Frequency=Test Mode, Placement=Center. Leave Background Image untouched.
2. Open site homepage, verify the Pop-up appears and looks exactly like it did previously.
3. Edit the Pop-up and set a background color. 
4. Open homepage again, verify Pop-up appears with correctly colored background.
5. Try all Placement …

Pop-up Background Color Control

---

src/view/style.scss

I'm overwriting the style of the `newspack-lightbox__close` button to make sure it blends in nicely with the rest of the content.
This allows to apply a background/text colour to `newspack-popup` and the button will inherit it.
1. On the front-end, try changing the background/text colour of `newspack-popup`
2. The close button shouldn't change
4. Play with the colours once again.

Update close button style to remove background colour and inherit text colour

---

includes/class-newspack-popups-inserter.php

This PR fixes an issue where popup content was getting injected into the feeds, so the first line of each item in a site's RSS feed would be the popup content.
1. Before applying this patch, create a popup:
2. Visit `/feed` on your site. Observe the pop up content is in the description for each item:
3. Apply this patch. Refresh. Observe the pop up content is not in the description for each item:

Dont inject popups into feeds

---

includes/class-newspack-popups.php

This PR sets up default values for a new pop-up when it is created. 
Closes #46 
1. Create a new Pop-up. 
2. Verify sidebar values match these https://github.com/Automattic/newspack-popups/compare/add/new-popup-defaults?expand=1#diff-5ceb977074740266ec972c731b1544ccR330-R340.
3. Save post and verify the values are intact.
4. Verify changes can be made to all values.

Pre-populate New Pop-ups with Defaults

---

includes/class-newspack-popups-inserter.php

This is a fix for a bug uncovered by https://github.com/Automattic/newspack-popups/pull/59. Since the popups aren't getting injected into excerpts on archives any more, the styles are not getting loaded on archives. Previously they were enqueued by the popup injecting itself into excerpts, disguising the bug.
1. Before applying this PR, create a popup and view it on an archive:
2. Apply this PR and view the popup again:

Load popup styles on archives

---

src/view/style.scss

Make sure full-width and wide blocks don't overflow the pop-up wrapper.
1. In a new pop-up CPT, add a bunch of wide and full-width blocks
2. Check the front-end, they should overflow (check front page, posts)
3. Switch to this branch.
4. Re-check the front-end

Fix popup blocks alignment (full-width and wide)

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/PopupPreview.js
src/editor/index.js
src/view/style.scss

This PR creates a new placement option: inline. When selected, the content is inserted inline in posts as opposed to being displayed in an overlay. For inline pop-ups the `trigger_scroll_progress` field is repurposed to determine the placement of the content.  
Unresolved issues (now resolved):
Closes https://github.com/Automattic/newspack-popups/issues/65.
- Create a new Pop-up, add Mailchimp block. Set Placement to "Inline," and Frequency to "Test Mode."
- Preview the block, verify it appears inline. Note that the Preview for inline blocks will be the most recent Post, since Inline Pop-ups cannot be inserted on the Homepage.
- Try different Position settings. Note that the Pop-up will be placed immediately after the paragraph that appears closest to the position specified, so setting …

Inline Placement

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
src/view/style.scss

Adds event tracking via Google Analytics. If Site Kit is installed and has analytics configured, every popup will report custom events:
1. Seen
1. Dismissed - by clicking on close button
1. Dismissed - by clicking on "not interested" text
1. Any link click in popup
1. Any form submission in popup
GA custom events have three properties: `Category`, `Action`, `Label`. This PR proposes the following use:
| Category | Action    | Label     |
| :------------- | :------------- | :------------- |
| `Newspack Popup` | `Popup (link clicked \| form submitted \| not interesting \| dismissed \| seen)`       | `Newspack Popup: <popup title>`       |
Closes #64.
1. Make sure Site Kit is connected to Analytics
1. Create a popup with a link and a form (e.g. Button block and Mailchimp block)
1. Visit site …

Add event tracking

---

includes/class-newspack-popups-api.php
src/editor/index.js

The Once-A-Day maximum frequency is overly cautious for Inline placements, because they are far less intrusive than overlays. This branch adds an "Every Page" frequency option which is available only when Placement is "Inline." This will cause the inline content to appear on every page, until dismissed (using "I'm Not Interested" button) or a successful subscription event. 
1. Create a Pop-up containing a Mailchimp block. Placement: Inline, Frequency "Every page." Publish, then check Sitewide Default and publish again.
2. In incognito window, navigate to a post. Verify you see the inline pop-up.
3. Navigate to several other posts, and verify you still the inline pop-up in each of these.
4. Click "I'm Not Interested." Navigate to another post, verify you do not see the popup anymore.
5. …

Every Page Frequency For Inline Placement

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

1. Fix Mailchimp submission reporting (before it worked just for inline popups)
1. Make analytics work on non-AMP pages 
1. Create a non-inline popup with a Mailchimp form
2. Visit the front-end, see the popup and submit with an email
3. Reload - the popup should not be visible
1. Set AMP to Transitional mode
1. Repeat 1-3
1. Create another popup and visit the front-end
1. Observe that the analytics events (load, visibility, dismissals) are being reported (in network console, search for requests with `collect`)

Fix analytics on non-AMP pages and for popups w/ Mailchimp

---

includes/class-newspack-popups-inserter.php

This branch addresses a conflict with Super Cool Ad Inserter, where under certain circumstances SCAI may place an ad within the markup of an inline popup. [This issue ](https://github.com/Automattic/newspack-popups/issues/85) demonstrates the problem that occurs when this happens. This branch resolves the problem by setting the priority of Pop-up insertion to be later, thus occurring after Super Cool Ad Inserter has already finished insertions.
Closes https://github.com/Automattic/newspack-popups/issues/85. Closes https://github.com/Automattic/newspack-popups/issues/84.
_This one is difficult to test!_
1. Install Super Cool Ad Inserter. In `/wp-admin/options-general.php?page=scaip` set values to 6/2/6.
2. Navigate to Newspack->Advertising and create a Google Ad Manager Unit. 
3. Navigate …

Super Cool Ad Inserter Collisions With Newspack Popups

---

src/view/style.scss

Make sure the floats are being cleared when inserting an inline pop-up.
1. In a post, add some paragraphs and a floated image
2. Add an inline pop-up to it (make sure that it's being inserted after your image)
3. Check the post -- it should look slightly broken
5. Check the post again...

Clear floats when using inline popup

---

includes/class-newspack-popups-model.php

Fixes a bug that can cause the loop to reset, which manifests in incorrect pub dates in the Newspack Blocks Homepage Posts block. h/t @philipjohn for finding this and @claudiulodro for the fix.
Closes https://github.com/Automattic/newspack-popups/issues/90
1. With Newspack Popups on `master`, create a few normal Posts and publish them.
2. If there are any Pop-ups, delete them all.
3. Create a Page. Add a Homepage Posts block, with **Excerpt** and **Show Date** enabled. 
4. Set the publish date to several months in the past, then publish the Page.
5. View the published page. The dates shown for posts in the block should be the date of the Page, not the date of the posts.
6. Switch to this branch, observe the correct dates are displayed.

fix: correct query reset that can reset the loop

---

includes/class-newspack-popups-model.php
src/view/index.js
src/view/patterns.scss
src/view/style.scss

If a pop-up has the Subscribe Pattern Style 1 then the pop-up add some extra CSS to it, removing the margin on both sides when centred and inline.
1. Create a new pop-up and insert the Subscribe Pattern Style 1
2. Preview -- you should have the "borders" around the pattern
3. Switch to this branch.
4. Refresh the preview -- you should see something similar to the screenshot above.
5. Test with inline placement as well.

Add style to subscribe pattern 1

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/PopupPreview.js
src/editor/index.js

A couple of changes to the logic and architecture, which result in the possibility of having multiple inline popups, and at most one overlaid popup:
- In editor, the "Sitewide Default" switch will be disabled if "inline" is chosen as placement.
- Some checks on the backend will prevent an inline popup from being marked as "sitewide default".
- Inline popups are inserted as shortcodes. This prevents an inline popup ending up inside another inline popup.
- All inline popups will be inserted into a post, unless there's category filtering. Any popup with a set category will only appear on a post with matching category.
- A non-inline popup will be displayed only if it's sitewide default, as it were (unless there's category filtering)
-  In admin's popup list view, a post state of "Inline" is …

Handle multiple popups

---

includes/class-newspack-popups-model.php
src/view/patterns.scss

This allows patterns to style pop-ups differently whether they display the title or not.
This PR also fixes issue when pop-up is using the subscribe pattern 1 and displays the title.
1. Create a new pop-up, inline or centred.
2. Add subscribe pattern 1
3. Display the pop-up title
4. Preview (the title should be right above the subscribe box with no margin)
5. Preview inline && centred.
6. Switch to this branch.
7. Preview again (you should see a margin between the subscribe box and the title)
8. Check the source and look for `.newspack-lightbox-has-title`

Add class to pop-up if display title is enabled

---

includes/class-newspack-popups-model.php

Popup analytics custom event should not be sent when previewing the popup.
This bug was introduced in #89 
1. On `master`, go and see a popup preview.
2. In Network tab of Devtools, observe an event being reported (a request to `https://www.google-analytics.com/collect` with `Newspack Announcement` in query string)
4. Trigger a preview again, observe that the custom event request to GA is not made.

Prevent reporting analytics data for popup previews

---

includes/class-newspack-popups-model.php

Closes #102.
I think the work going on in #103 is probably a good idea if we can make it work nicely on AMP and non-AMP modes, but I've stumbled across an easy solution directly for #102 . [There is a config param mentioned that suppresses the initial pageview logged in GA](https://developers.google.com/analytics/devguides/collection/gtagjs#disable_pageview_measurment). I did some testing, and was able to make it work in `amp-analytics`! 
This PR patches the immediate issue of the multiple pageviews.
1. Connect Site Kit. Create an inline and a modal popup.
2. Visit a post that has both popups. Observe 3 pageviews in Google Analytics real time view from the one page visit.
3. Apply patch. Visit a post that has both popups. Observe 1 pageview in Google Analytics real time view.

Suppress pageview logging in popups analytics.

---

includes/class-newspack-popups-inserter.php

Because we load `amp-form` script on non-AMP pages to handle forms in AMP way, some other forms might be broken. 
More context: https://github.com/ampproject/amphtml/issues/27638
Closes #100 
1. Create a page with a `form` that has `method="POST"`
1. Create a popup that will appear on this page (e.g. sitewide overlay popup in test mode)
2. Visit page with AMP disabled (disable plugin or set mode to Transitional)
3. Observe that the popup does not show up
3. Observe that the form can be submitted without errors

Disable popups on non-AMP pages with POST form elements

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups.php
src/document-settings/index.js
webpack.config.js

Instead of handling the form-with-post-on-AMP issue specifically, add option to disable popups for specific posts and pages.
1. Add a sitewide default popup
2. Visit a page or a post, observe popup displayed
3. Edit that page or post – check "Disable Popups" in Document panel i sidebar, save
2. Visit a page or a post, observe popup not show

Enable disabling popups for specific posts and pages

---

includes/class-newspack-popups-inserter.php

This PR fixes an issue discovered when Asia Times was trying to set up a paywall. When a user gets the "content restricted" message, an infinite loop happens between the code that inserts popups into content and the code that blocks the content with a "Content restricted" message. This PR solves the issue by preventing popups in the content on posts that are restricted. It doesn't really make sense to inject a popup in that scenario anyways.
1. Set up WooCommerce, WooCommerce Subscriptions, WooCommerce Memberships. Restrict a category to only members.
2. Set up an inline popup.
3. In an incognito window, visit a restricted page. Observe fatal error:
4. Apply patch. In an incognito window, visit a restricted page. Observe you get a "Restricted content" message:
cc @philipjohn just as a …

Prevent infinite loop with inline popups and paywalled content

---

includes/class-newspack-popups.php

See https://github.com/Automattic/newspack-popups/issues/117 for description of the problem.
Closes https://github.com/Automattic/newspack-popups/issues/117
1. Follow repro steps in https://github.com/Automattic/newspack-popups/issues/117
2. Create a build from this branch, replace Newspack Pop-ups with it.
3. Verify the admin bar is no longer visible.
4. Create a Pop-up and preview it. Verify there is no admin bar at the top of the preview.

fix: resolve issue causing admin bar to display incorrectly

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
newspack-popups.php
src/document-settings/index.js
src/editor/index.js

We're renaming "Pop-ups" -> "Campaigns" (discussion in `pamTN9-15s-p2`). See complete testing instructions in https://github.com/Automattic/newspack-plugin/pull/522.

refactor: rename pop-ups->campaigns

---

includes/class-newspack-popups-inserter.php

By matching block end comments instead of paragraph end tags, the popup will always be inserted between blocks, and not inside of a block (which might have paragraphs inside).
Resolves #92
1. On `master`
1. Add a quote block to a post
2. Add an inline popup and try to set the "Approximate position" so that the popup placed is where the quote is
2. Observe in preview that the inline popup in inserted into the quote block
4. Observe in preview that the inline popup and quote block are not conjoined

fix: popup insertion logic

---

includes/class-newspack-popups-inserter.php

Closes #124 .
1. On master, reproduce #124 
2. Add an inline popup, so we know that these are still working fine
2. Switch to this branch
3. Observe #124 is not reproducible anymore 
4. Observe that the inline popup works as expected

Fix insertion of overlay scroll-triggered popups

---

includes/class-newspack-popups-inserter.php

This PR fixes an issue one of our publishers noticed. On product pages clicking the Add to Cart button doesn't do anything. This is because the amp-form script intercepts the button and prevents it submitting. Additionally, inline popups display in the product description.
1. Before applying this patch, create a Simple Product in WooCommerce, give it any price. Have an active Campaign.
2. In incognito mode, attempt to add the product to the cart. Observe a JS error is thrown in the console and there is also an inline popup in the content:
3. Apply this patch. Attempt to add the product to the cart. Observe it works. Observe no inline popup in the content.

Dont load popups on products because of amp-form

---

src/editor/index.js

Closes #56.
1. On branch master, 
1. create or edit a campaign
2. Set background and overlay colors, save 
3. Unset colors 
3. Observe that the colors cannot be un-set
4. Switch to this branch, rebuild JS, do steps 2-4 again
4. Observe that the colors can now be unset. When unset, they are reverted to defaults – white for background color and black for overlay color

Handle default colors in the editor

---

includes/class-newspack-popups-inserter.php
package-lock.json
package.json
src/view/index.js

The plugin takes the unusual approach of using AMP libraries in non-AMP requests. This brings the benefits of a single implementation, but has led to a variety of problems mostly related to form handling. This PR begins the process of rewriting these pieces of functionality in vanilla Javascript. The plugin uses five AMP libraries: 'amp-access', 'amp-analytics', 'amp-animation', 'amp-form', 'amp-bind', and 'amp-position-observer'. This PR replaces `amp-form`.
1. Switch to AMP Transitional mode.
2. Create a few Campaigns.
3. Test in AMP and non-AMP pages, in a variety of browser. Verify the behavior is identical especially related to dismissal (clicking the overlay, clicking the close button, clicking "I'm not interested" link).
4. Test Campaigns that contain forms (Mailchimp, etc). Verify …

fix: remove amp-form in non-amp requests

---

includes/class-newspack-popups-api.php

Namespace argument in `register_rest_route` should not start nor end with a slash. Including it does not break anything, but pollutes the error log which impairs development.

Fix namespace use in register_rest_route

---

includes/class-newspack-popups-model.php

Jetpack Related Posts block fails in Campaigns because the Related Posts block seeks posts based on the ID of the Campaign, not the containing Post. This branch changes this by ~setting the containing Post as the global `post` object~ re-querying the containing post immediately before rendering the campaign.~ h/t @philipjohn for the approach.
Closes https://github.com/Automattic/newspack-popups/issues/143
1. Create an inline campaign. Add Jetpack Related Posts block. Give the campaign a title and click the toggle to display title so you'll be able to identify it even when empty.
2. On `master`, test the campaign in a post. It should render empty—a box with the title and nothing else.
3. Switch to this branch, and retest. Observe a normal Related Posts block with posts relevant to the …

fix: related posts in campaigns

---

includes/class-newspack-popups-inserter.php

This PR changes the approach to injecting campaigns into content, where all relevant campaigns are injected in a single pass through `parse_blocks`. This should resolve the issues where multiple inline campaigns are often positioned incorrectly.
Closes https://github.com/Automattic/newspack-popups/issues/142
1. Create 2 or more inline campaigns with different approximate position settings.
2. View a post, verify the campaign positions are roughly correct (the placements are approximations based on paragraph length so they will rarely be absolutely precise).
3. Experiment with different position settings, including swapping positions of two campaigns.
4. Add an Overlay campaign and make sure that performs correctly.
5. Verify the content of posts is correct and complete. Test with text and …

fix: insert all campaigns into content in one pass

---

src/view/index.js

The non-AMP form handling introduced in https://github.com/Automattic/newspack-popups/pull/127 is not being applied properly to inline campaigns. As a result, the permanent dismissal buttons don't function properly.
Closes https://github.com/Automattic/newspack-popups/issues/153
1. Switch AMP plugin to Transitional.
2. Create an inline campaign set to display on Every Page.
3. On `master`, view a post as a non-AMP page. 
4. Click "I'm not interested."
5. Observe the campaign is not hidden, the page reloads, and the campaign is shown again.
6. Switch to this branch and repeat 3-5.
7. Observe the campaign is hidden, the page does not reload, and the campaign is not shown on any other pages.
8. Verify the same correct behavior in an AMP request.

fix: non-amp form handling for inline campaigns

---

includes/class-newspack-popups-model.php

Adds a class name to `amp-lightbox` overlay and inline elements if the contents of the lightbox contains a Mailchimp newsletter prompt. This will allow us to target the AMP element for analytics. This relates to https://github.com/Automattic/newspack-plugin/pull/557.
If any additional newsletter services are implemented, they should be included in the check so the newsletter classes are added appropriately.
1. Create an overlay and inline campaign. In each campaign, add a Mailchimp newsletter form block.
2. On the front-end, inspect each campaign element. They should include the class names `newspack-newsletter-prompt-overlay` and `newspack-newsletter-prompt-inline`, respectively.

feat: add class names for newsletter prompts, for analytics tracking

---

includes/class-newspack-popups-model.php

Use newspack-plugin's `newspack_analytics_events` filter to report GA events for all events except [visibility](https://amp.dev/documentation/components/amp-analytics/#page-and-element-visibility-trigger). 
Closes #151 
1. Observe #151 not being reproducible
2. Observe analytics events reported as expected:
1. Load event
1. Seen event
1. Link click
1. Form submission
1. Dismissal
1. Permanent Dismissal

Analytics: use newspack-plugin's filter where possible

---

includes/class-newspack-popups-inserter.php

Erroneusly there was an assumption that SCAIP ad insertion might create issues only with inline campaigns. This PR fixes this – now SCAIP will be prompted to insert its stuff before campaigns insertion, regardless of campaign type.
Closes #158.
1. Try to reproduce #158, observe it's not reproducible after changes from this branch are applied.

Fix ad insertion in overlay campaigns

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

This PR is a new approach in the ongoing saga of `the_content` filter being called by all kinds of posts besides the main one which has side effects related to `amp-analytics`, Homepage Posts block, and others. Here, querying for Campaign CPTs is separated from the code that renders them. The rendering occurs only just before inserting the campaign into content. This solves the problems that arise from blocks within a Campaign being rendered even if the campaign may not end up being used. 
This is a refactor and should not change the behavior of the plugin. To test, create multiple campaigns of different types and verify that they render properly.

refactor: render campaign content immediately before injection

---

includes/class-newspack-popups-inserter.php

This addresses behavior described in https://github.com/Automattic/newspack-plugin/pull/575#issuecomment-653256024.
High-level summary: when the Jetpack Related Posts module is enabled, and it displays at least one related post that lacks a featured image, it causes the `the_content` hook to fire multiple times. This results in the [`insert_popups_in_content`](https://github.com/Automattic/newspack-popups/pull/165/files#diff-9c9a6b7ce934e14992cebfb9a2b61470R137) callback to be run multiple times as well, which potentially results in AMP analytics event triggers to be outputted more than once per element. This in turn causes several JS errors for the duplicate event triggers and could potentially pose problems for AMP validation in the future.
This PR fixes this (and any other undiscovered …

fix: duplicate execution of the_content filter

---

includes/class-newspack-popups-model.php

This PR should fix an issue with artificially low bounce rates reported in Google Analytics. Since the popupVisible event wasn't marked as a non-interaction event, anyone that saw a campaign would be marked as a user that didn't bounce. 
I'm not sure how you'd really test this, since a local environment is going to have a weird bounce rate if you've hooked it up to GA, and bounce rate analytics aren't available in real-time AFAIK. I think we should find a willing participant and make the change on their site for a couple days to see how it affects things.

Make popupVisible non-interactive event

---

includes/class-newspack-popups-settings.php
src/settings/index.js
src/settings/style.scss

Applies missing stylesheet to the settings view and fixes one styling issue.
1. On master, build the plugin files and visit the settings screen 
2. Observe that there is no Newspack-brand-related styling applied and there is no `settings.css` file loaded
3. Observe that there's a checkmark render on top of the checkbox (when checked)
4. Switch to this branch and rebuild
4. Observe both issues resolved

Fix settings styling

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-settings.php
src/settings/index.js

Add a setting (on by default) to suppress all Newsletter Campaigns if one of them was dismissed permanently.
1. Create three campaigns – two with newsletter forms (Jetpack Mailchimp form), one without. Set all to "Every page" frequency.
2. Visit the site, observe all three are shown.
3. Dismiss permanently ("Not interested" button at the bottom) one of the newsletter campaigns
3. Reload the page – observe that both newsletter campaigns are not visible, and only the non-newsletter one renders
4. Visit Campaigns settings, uncheck the "Supress all Newsletter campaigns if at least once Newsletter campaign was permanently dismissed." option
4. Revisit the site – observe that only the dismissed campaign is not displayed.

Add option to suppress all newsletter campaigns if one was dismissed

---

includes/class-newspack-popups-inserter.php

Adding back a feature accidentaly removed in #89. Non-test mode campaigns should be hidden for logged-in users.
1. Create a campaign in test frequency – observe that it's visible for logged-in users and not visible for non-logged-in users.
2. Switch campaign to a different mode – observe that it's visible for non-logged-in users and not visible for logged-in users.

feat: hide non-test campagins for logged-in users

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php

Fixes issues cased by #173.
1. Create inline, every page campaigns: two with newsltter signup forms (A, B) and one without (C)  
2. Add "UTM Suppression" to campaign A of value `My Newsletter`
3. Visit an article to verify all campaigns are shown
4. Visit that article with `utm_source=My%20Newsletter` parameter in URL
4. Observe that only B and C campaigns are visible
4. Navigate to another article (so that there's no `utm_source` parameter in the URL)
4. Observe that only B and C campaigns are visible
4. Visit that article with `utm_medium=email` parameter in URL
4. Observe that only C campaign is visible
4. Navigate to another article (so that there's no `utm_medium` parameter in the URL)
4. Observe that only C campaign is visible
A tip: if your local instance is as slow as mine, you'll …

Fix: UTM params suppression conflict

---

includes/class-newspack-popups-inserter.php

As it says on the tin
1. On `master`, visit an article with a campaign in non-AMP mode
2. Click "I'm not interested" to permanently dismiss the article
3. Observe page reloading
4. Redo step 2
4. Observe no page reload and that the request to `/reader` endpoint in handled asynchroneusly

Fix dismissal errors on non-AMP pages

---

src/settings/index.js

Fixes a typo in one of the option labels. From:
```
Suppress all Newsletter campaigns if at least once Newsletter campaign was permanently dismissed.
```
to:
```
Suppress all Newsletter campaigns if at least one Newsletter campaign was permanently dismissed.
```
1. Visit **Campaigns > Settings** and review the second option.

fix: a typo in one of the campaign settings options

---

.circleci/config.yml
.distignore
package.json

1. Change release ZIP file structure, so that it matches the structure used by WPORG plugins
1. `semantic-release` config update which will enable [prereleases](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#pre-release-branches). 
1. Run `npm run release:archive`
2. Install the plugin on a fresh site, confirm that it works as before

Build: change release zip structure 

---

includes/class-newspack-popups-api.php

Adds `permission_callback` to `register_rest_route` calls, as it's a required argument in WP 5.5
1. On a page with popups, verify that calls to `/reader` endpoint are working as before – by dismissing a popup permanently and then checking that it's not displayed any more

Add permission callbacks (required in WP 5.5.)

---

includes/class-newspack-popups-model.php

Because of hos events are set up, a user dismissing a campaign and leaving the site would now count as a bounce. This PR fixes that. 
1. Create a campaign
2. Visit page, dismiss the campaign
3. Observe the event is sent as non-interaction to GA (`ni` parameter of value `1` in the request)

Fix bounce rates: dismissals as non-interaction

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-model.php

For a better interop with other plugins, two features are introduced here:
1. A hook which allows other plugins to receive the submitted email if a newsletter signup form in a Campaign was submitted
3. Blocks rendered within a Campaign are furnished with a `newspack-popups-content-block` class, for better event handling
1. Create a Campaign with a Newsletter signup block (Jetpack Mailchimp block)
2. In a different plugin, subscribe to `newspack_popups_mailing_list_subscription` hook
3. Visit an AMP page ([won't work with non-AMP](https://github.com/Automattic/newspack-popups/issues/200))
4. Subscribe to the newsletter 
5. Observe the hook receives a payload object with an `email` key, the value of which is the submitted email
6. Observe the blocks rendered within the Campaign have the …

Add interoperation features

---

includes/class-newspack-popups-api.php

It appears that something about get_transient has changed when PHP 7.4 is running.
Closes #179 
1. Switch to PHP 7.4
2. On `master`, observe a notice logged when Campaigns POST endpoint is hit
3. Switch to this branch, observe no notice logged

Handle false get_transient return value

---

includes/class-newspack-popups-model.php

Closes #185 
1. Create a draft campaign, then in the Newspack plugin's Campaigns wizard set it to test mode
2. Observe that this action does not trigger an error and set the draft campaign to test mode (and back)

Fix: enable drafts handling for setting options and categories

---

api/README.md
api/classes/class-lightweight-api.php
api/classes/class-maybe-show-campaign.php
api/classes/class-report-campaign-data.php
api/index.php
includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

Switches the plugin to use lightweight API, adds POST requests handling; changes how `amp-access` is used – to make just one GET request per page.
1. Create multiple campaigns
2. On a page where they all appear, observe that one GET request is made to get campaigns visibility
3. Dismiss a campaign – observe the POST request is made to the lighweight API endpoint
4. Observe all campaign functionality related to display conditions is working as before

Single GET per page; lightweight POST endpoint

---

includes/class-newspack-popups-inserter.php

Closes #219.
1. Observe #219 is not reproducible

Prevent a test category popup from taking the place of a sitewide default

---

api/classes/class-lightweight-api.php

Enables requests from AMP Cache. 
For a real test this code would have to be put on a site served by Google's AMP Cache – if you can't do that, just replace with value of `$http_host` with `site-url.cdn.ampproject.org` and observe the API requests completing (not returning 4XXs). Otherwise:
1. Visit site via AMP Cache
3. Observe API requests coming through

API: allow requests from AMP Cache

---

api/index.php
includes/class-newspack-popups.php

Fixes two issues related to config:
1. The path to the config assumed the plugin folder is named `newspack-popups` – it can be named differently, e.g. when it's an alpha build it will have the version appended after plugin name
2. On certain environments for some reason PHP does not have access to the environment, so here the `DB_USER` etc. checks are removed
1. Remove the config file of present
2. Verify that the config file is created (you might need to remove the `newspack_has_tried_to_create_lightweight_api_config` option)

API: config creation fix

---

src/view/style.scss

In some situations the .entry-content might not be of position relative.
(#page-position-marker element is an absolutely-placed child of .entry-content)
1. Create a scroll-triggered campaign
2. Verify it displays correctly on a homepage

Fix scroll-triggered campaigns

---

includes/class-newspack-popups-model.php

AMP Components can be self-closing, but if page is served as non-AMP, in some cases this may not be handled. 
In the case of this bug, the `amp-position-observer` component can be treated as not-closed, resulting in the page content being inserted as children of it. 
1. On `master`, create an overlay, scroll-triggered campaign, set to sitewide default 
2. Set your site to AMP transitional mode
3. Visit the (non-AMP) homepage, observe only the header and footer are displayed
3. Visit a (non-AMP) post, observe only the header and footer are displayed
4. Switch to this branch, reload site
5. Observe the homepage and post are rendered as expected, with the campaign triggered by scroll as expected
6. Also check the AMP version

Fix: scroll-triggered popups on non-AMP pages

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
src/settings/index.js
tests/bootstrap.php
tests/test-insertion.php

In some situations the user might wish to lessen the load on the server by disabling the API calls. 
In non-interactive mode the overlay campaigns will not be displayed, and inline campaigns will not be dismissible. All inline campaigns will be displayed, since the suppression logic will not be called.
Closes #248.
1. Create some inline and overlay (non-test-mode) campaigns. 
2. Observe they are displayed as expected. Dismiss the inline campaigns permanently.
3. Observe no campaigns are displayed.
4. Visit plugin settings, turn on the "non-interactive mode" setting.
5. Observe the overlay campaigns are still not displayed, but inline ones are.
6. In a new session, observe the above again.

Non-interactive (aka high traffic) mode

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
tests/test-model.php

In some cases, time-triggered popups will not show until scrolling.
Closes #241 
Closes #247
1. Create a time-triggered popup, set to test mode
1. On `master`, visit the site, scroll to the bottom, and reload
2. Observe the popup is not shown until site is scrolled to top
4. Observe the popup is displayed when loading the page with scroll offset

Fix time-triggered popups edge case

---

includes/class-newspack-popups-inserter.php
src/view/style.scss

Closes #246.
1. On `master`, create an inline campaign that should display at 1% position
2. Observe the markup is mangled
3. Update the campaign to display at 100% position
4. Also borked, right?
5. Switch to this branch, observe an inline campaign at 1% and 100% is displayed correctly
6. Test some other in-content placement percentages just to be sure

Fix inline campaign markup

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

Allows for testing of overlay campaigns.
Closes #62.
1. On `master`, create an overlay campaign in test mode
2. Observe that it will not be visible unless it's set to sitewide default. This will un-set the campaign which was the sitewide default up until now. Not cool.
3. Switch to this branch, observe that a test overlay campaign will be available for testing without the need to unset the sitewide default
4. Observe that you can make a mess by creating multiple overlay test campaigns

Testing overlay campaigns

---

src/editor/index.js

Closes #209.
1. Create a campaign, placement inline at 0%
2. Create a post with a one-word first paragraph
3. Observe the inline campaign is inserted before the first paragraph

Allow inline campaigns to appear before first block

---

includes/class-newspack-popups.php
src/editor/index.js

Closes #105.
1. Create a new campaign
2. Observe that in the "Frequency" setting, "Every page" option is disabled if it's an overlay campaign, and enabled when it's an inline campaign
3. Set it to "Every page", then change placement to non-inline – observe the frequency value is updated to "Once"

Disable "Every page" frequency for overlay campaigns

---

src/editor/index.js
src/editor/style.scss

Closes #130.
1. Create or edit a campaign
2. Observe there is no native preview button (the one next to Publish/Update)
3. There's only one preview button, for the modal preview

Disable native preview button

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups.php

Closes #109.
1. Create or edit a campaign, observe that tags can be chosen in the sidebar
2. Set a tag on the campaign, observe that it's displayed only on posts with matching tag (just like with category filtering)
3. Observe a campaign with no tags set behaves as before

Add tag filtering

---

includes/class-newspack-popups.php
src/editor/PopupPreview.js

Closes #110.
1. Disable campaigns on the latest post
2. Create or edit an inline campaign, observe that preview uses the lastest post which does not have disabled campaigns

Fix previews if latest post has campaigns disabled

---

api/campaigns/class-maybe-show-campaign.php
api/campaigns/index.php
api/classes/class-lightweight-api.php
api/segmentation/class-segmentation-report.php
api/setup.php
phpunit.xml.dist
tests/bootstrap.php
tests/test-segmentation.php

Adds cacheing, so the segmentation data is available before the logs are parsed.
Without cacheing, the to-be-implemented segmentation features (e.g. show a campaign after 3 posts are read) would work after a lag, since the events log is parsed in a cron job. 
Since there are no user-facing features here, testing can be done by inspecting the results of `Maybe_Show_Campaign::get_client_data` method in `Maybe_Show_Campaign`'s constructor, and following the tests to see how it's supposed to work.

Segmentation: use cacheing for client data

---

api/campaigns/class-report-campaign-data.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-model.php
phpunit.xml.dist
tests/test-api.php

Adds handling of an MC4WP plugin form subscription event. 
Related: #250
1. Create two campaigns, one with a Jetpack Mailchimp form, one with MC4WP form
2. Submit both 
3. Inspect the value of client data (`self::get_client_data( $client_id )`, e.g. in `Maybe_Show_Campaign`'s constructor)
4. Observe the email addresses were saved in client data

Handle MC4WP; store email subscriptions as an array

---

api/classes/class-lightweight-api.php
api/segmentation/class-segmentation-client-data.php
api/segmentation/index.php
includes/class-newspack-popups-donations.php
includes/class-newspack-popups.php
tests/test-api.php

Save WC order data as donation.
Related: #249
1. Make a donation on site
2. Check the options table for client data (use the `newspack-cid` cookie value)
3. Observe the donation data was saved
_Note: you might need to bypass HTTPS check on a local instance, to make WC webhook succeed:_
```
add_filter(
'http_request_args',
function ( $r ) {
$r['sslverify'] = false;
return $r;
}
);
```

Segmentation: save WC donation data

---

includes/class-newspack-popups-donations.php

On a site with no WooCommerce plugin, this plugin breaks. This fixes it.
1. Install the plugin from branch `master` on a site with no WooCommerce plugin installed
2. Observe the admin panel does not load
3. Install the plugin from this branch
4. Observe the admin panel works as expected

Fix: check of WC-related class exists

---

api/classes/class-lightweight-api.php

Fixes issue that causes the following warnings to be logged:
```
[27-Oct-2020 19:23:08 UTC] PHP Warning:  array_filter() expects parameter 1 to be array, null given in /wordpress/plugins/newspack-popups/1.15.0/api/campaigns/class-maybe-show-campaign.php on line 42
[27-Oct-2020 19:23:08 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /wordpress/plugins/newspack-popups/1.15.0/api/campaigns/class-maybe-show-campaign.php on line 42
```
1. On `master` visit front end in an incognito browser. Make note of the `cid` in the API request.
2. In the options table, edit the transient for the current `cid`, and remove the `posts_read` array, so it looks something like this: ```{"suppressed_newsletter_campaign":false}```
3. Visit another page, observe …

fix: add posts_read array to legacy client data

---

api/campaigns/class-maybe-show-campaign.php
api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-settings.php
src/settings/index.js
tests/bootstrap.php
tests/test-api.php

The setting to hide donation campaigns for donors is off by default, because I assume some sites might want to enable repeated donation. That's open for discussion, though. 
Closes #141.
1. Create a campaign with a donation block 
2. In the plugin settings, check "Suppress all donation campaigns if the reader has donated." setting
3. Visit the site and donate using the donation block on the campaign
4. Wait for about a minute, WC has to notify the plugin about the donation
Note: you might need to disable SSL checking on a local instance:
```
add_filter(
'http_request_args',
function ( $r ) {
$r['sslverify'] = false;
return $r;
}
);
```

Donation campaigns suppression

---

includes/class-newspack-popups-inserter.php

Recent changes to the handling of Test Mode campaigns introduced two issues related to overlays:
- If there is a sitewide default campaign a logged in user will get two instances of the same popup layered on top of each other.
- If there are multiple popups a logged in user may get two overlapping popups. 
- Anonymous users won't have either of these problems, so this is purely an issue for site editors.
This PR addresses the problem by retaining only the first overlay campaign from all candidates. This may not be a perfect solution, as an admin may see an overlay that isn't the expected one, but for now this resolves the obvious problem. 
1. On `master`, create and publish a single overlay campaign, Sitewide default.
2. View a page on the site (logged in). Observe two versions of the …

fix: allow only one overlay campaign per page

---

includes/class-newspack-popups-model.php

Fixes a small issue
1. Create two inline campaigns with newsletter signup forms – one with MC4WP form, other with Jetpack form
2. Visit an article with the `utm_medium=email` param in URL
3. Ensure the "Suppress Newsletter campaigns if visitor is coming from email." setting is on
4. Observe that only the Jetpack-form campaign is hidden
5. Switch to this branch and observe that both campaigns are hidden

Handle MC4WP forms when assessing if campaign has newsletter form

---

api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups.php
src/editor/index.js
src/editor/utils.js
tests/test-api.php
tests/test-model.php

Closes #271.
1. In `newspack-plugin`, switch to `add/segmentation-ui` branch
2. Observe a new tab in the Campaigns wizard – "Segmentation"
3. Create a segment with minimum read articles count of 3 and maximum of 5
4. Create a campaign, observe a new select in the sidebar – "Segment"
5. Choose the newly created segment and publish the campaign
6. Observe that the campaign is shown only when reading the 3rd, 4th, and 5th article
7. Experiment a bit more with segments (e.g. remove a segment after a campaign was assigned one, try different configurations of min. and max. articles read count)

Add posts read count segmentation

---

includes/class-newspack-popups.php

Adds a password check to preview post getting. 
1. Make the most recent post password-protected
2. On `master`, observe that the campaign preview will use homepage for previews
3. Switch to this branch, observe that the campaign preview will use the most recent not-password-protected post

Improve preview post link

---

includes/class-newspack-popups-inserter.php

The injection of Campaigns into Events single pages provided by The Events Calendar plugin causes a loop that leads to memory exhaustion, time outs and malformed markup. To resolve, this PR blocks injection into content unless the post type is `post` or `page`. This is done with a filter to allow other CPTs to opt-in for Campaign injection. 
Closes https://github.com/Automattic/newspack-popups/issues/295
1. Install [The Events Calendar](https://wordpress.org/plugins/the-events-calendar/) plugin and create/publish at least one Event. 
2. Create at least one campaign.
3. On master, view the event in the front end. Observe the page times out, or renders broken markup.
4. Switch to this branch, observe the Event page loads normally.
5. Bonus, test the filter. Add this anywhere code executes: …

fix: inject campaigns into posts and pages only

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-segmentation.php

Closes #299.
1. On `master`, disable Campaigns for a post, view the post in non-AMP mode
2. Observe that AMP JS scripts are loaded anyway
3. Switch to this branch, observe the AMP JS scripts are not loaded for this post

Do not enqueue scripts if post has Campaigns disabled

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

1. Fixes a bug introduced in #206 
2. Removes classname appending introduced in #201 – since the audience/segmentation features are now a part of this plugin, it won't be needed
1. On `master`, observe that:
2. `newspack-popups-content-block` classname is appended to dynamic (e.g. jetpack signup form) blocks inside of a campaign
2. The API endpoint is failing, so no campaigns are shown
3. Switch to this branch, observe that the classname is not being appended, and that the API endpoint is not failing

Fix settings format for API; remove classname appending

---

api/setup.php
includes/class-newspack-popups.php

This PR does three things:
1. Closes #314 by moving the configuration file location to the `wp-content` directory rather than root
1. Fixes the conditional for checking whether to create a config file or not, as it wasn't actually working reliably on non-Atomic environments
1. Changes the hook used so that the plugin is not attempting to write to the disk from frontend requests, which could create performance issues
1. On a non-Atomic environment where no configuration file exists, observe there is no config file
2. Open any admin screen
3. Observe there is now a configuration file

Improve configuration file handling

---

.circleci/config.yml
babel.config.js
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
package-lock.json
package.json
src/view/index.js
src/view/utils/index.js
src/view/utils/index.test.js

Polyfill of `amp-analytics` AMP script (just the bits used by the plugin), part of #193.
A part that needs some explanation here is the linker parameter. Here's [a short overview](https://amp.dev/documentation/components/amp-analytics/#linkers), and here the [documentation about linker param receiving](https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/linker-id-receiving.md) – the part that's actually polyfilled. Linker param _setting_ is not handled here, because it would be set only by a page served from AMP cache, which would be… an AMP page (not a version with polyfill).
Here's an example of a linker param:
```
?ref_newspack_cid=1*10zr7ce*cid*T2ptZDdJNU9EYndELWV0TlM1N0FwSGVwNHE3S240VkVVU0o3YlNsaFc2YVVPRXJhSWFhaVlsOTgtQXNsc21Eeg
```
The `T2pt…` part is …

Polyfill amp-analytics script

---

api/setup.php
includes/class-newspack-popups.php

#315 changed the config file path, but did not ensure handling of the legacy config file path. This fixes that. 
1. Follow the testing steps in #315 to ensure config is created in `wp-content` on a fresh site
2. Move the config file to the root, observe that the API is still functional

Fix: legacy config file path

---

includes/class-newspack-popups-segmentation.php

For segmentation features (e.g. posts read count, category affinity), we just need 30 days worth of data about read posts. 
Closes #251 – since the segmentation-related data will be reported to GA as custom dimensions (#325), there's no need to save a condensed snapshot of the removed data. 
1. Create some events in the `wp_newspack_campaigns_events` with `created_at` dates from before 30 days ago
2. Load the site
3. Inspect the database, observe that the rows with dates older than 30 days are no more

Prune segmentation data

---

includes/class-newspack-popups-inserter.php

Campaigns with 'never' frequency should not be rendered into content.
1. On `master`, create a campaign with 'never' frequency
2. Observe it's rendered in HTML
3. Switch to this branch, observe the campaign is not in HTML

Do not render campaigns with 'never' frequency

---

api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
api/segmentation/class-segmentation.php
includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-segmentation.php
package-lock.json
package.json
src/view/index.js
src/view/utils/index.js

Allows for reporting reader frequency, donor status, subscriber status, as custom dimensions to GA. 
Note that with current implementation these custom dimensions will be reported only for pageviews (not for custom events).
Closes #259 .
1. Switch Newspack Plugin to branch `add/external-custom-dimensions` (https://github.com/Automattic/newspack-plugin/pull/685)
2. Visit the Analytics Wizard, Custom Dimensions tab
3. Observe new options in the "Role" select:
4. Assign some custom dimensions to the Campagins segmentation related roles (the three latter ones)
5. Visit the homepage, then a post, observe the `pageview` is reported to GA with the custom dimensions, with appropriate values
6. Repeat for both AMP and non-AMP versions of the site, the custom dimensions sent with `pageview` should …

Report segmentation-related data as custom dimension to GA

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
src/editor/FrequencySidebar.js
src/editor/Sidebar.js
src/editor/index.js
src/editor/utils.js

Adds an "above header" campaign placement, as requested in #260
Additional changes in Theme (https://github.com/Automattic/newspack-theme/pull/1131) and the plugin (https://github.com/Automattic/newspack-plugin/pull/691)
1. Create a new campaign, observe a new option in "Placement" select – "Above site header"
2. Use this option
3. Verify that the campaign is placed above site header
4. Filtering (category, tag, etc.) and everything else should work as with a regular inline campaign

Add above header placement option

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
tests/test-insertion.php

Closes #4.
1. Create a time-triggered overlay campaign
2. On `master`, open a post with a featured image and ensure the post content area starts below the fold (is not visible when page is scrolled to top)
3. Observe the time-triggered campaign is not displayed until scrolled down (when the post content area becomes visible)
4. Switch to this branch, observe the campaign is displayed right away (after the specified delay, that is)

Insert time-triggered overlay campaigns above header

---

includes/class-newspack-popups.php

After discussing with @thomasguillot we concluded that Campaign Groups should be a hierarchical taxonomy for clearer UI.
1. Verify Campaign Groups is now hierarchical, with checkbox UI like core Categories as opposed to Tags.

feat: make campaign groups a hierarchical taxonomy

---

api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-view-as.php
includes/class-newspack-popups.php
tests/test-api.php

Adds a feature that enables admins to view site as a member of a particular segment would see it.
There's not UI for that yet – it's a 'stealth' feature. The way to control it it via a URL query param and cookies.
1. Create a bunch of campaigns, using different segments – to use all segmentation options.
2. Visit the site as a logged-in user. 
3. Observe that active campaigns are not visible, and test campaigns are – nothing new here
4. Append a `view_as` query param to the URL, with the value of `segment:<segment-id>` (e.g. `?view_as=segment:5fa056b4b94bc`). You can read the segment ID from URL in Campaigns Wizard -> Segments -> edit a segment.
5. Observe that now, as a logged in admin user, you can see the applicable active campaigns – as a member of the chosen segment would.
6. …

Add "view as segment" feature

---

api/campaigns/class-campaign-data-utils.php

Support `Articles read in session` when previewing a segment.
Closes https://github.com/Automattic/newspack-popups/issues/361
1. On `master`, create a segment with min/max values for Articles read in session.
2. Create an inline campaigns and choose the segment.
3. In the Newspack Plugin Campaigns wizard preview as the segment.
4. Observe the campaign is not shown.
5. Switch to this branch, preview again.
6. Observe the campaign is now shown.

fix: session read count in view-as logic

---

src/view/index.js
src/view/utils/index.js
src/view/utils/index.test.js

Due to [this clean function](https://github.com/Automattic/newspack-popups/pull/306/files#diff-961feb79bdd31646421b94dfdb35d9ea989a94b447987ea75e325e9665465241R86), when visiting a non-AMP page or post, the AMP polyfill cleans the URL of linker params but leaves a trailing `?` character at the end of the URL. It also creates extra browser history via `history.pushState`. This PR removes the trailing `?` and uses `history.replaceState` to avoid the extra browser history.
1. On `master`, visit a non-AMP post in a new Incognito window and observe that the page loads with a trailing `?` on the URL. Also observe that clicking the browser's back button after the the page loads just removes the `?` without actually going back to the prior page.
2. Check out this branch and run `npm run build`. …

fix: remove trailing question mark from cleaned non-AMP URLs

---

api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/FrequencySidebar.js

In order to manually place an inline campaign via shortcode the campaign needs to have a normal frequency (e.g. every page) which means it will appear in posts. This will often be undesirable, if the campaign is designed exclusively for the homepage. This branch adds a new frequency option called "Manual Placement." When selected, the campaign will only show up when manually placed by shortcode. This is a bit similar to the `Manual Only` option that was originally in https://github.com/Automattic/newspack-popups/pull/321, although we ended up removing it ([my fault](https://github.com/Automattic/newspack-popups/pull/321#discussion_r532261142)!)
Closes https://github.com/Automattic/newspack-popups/issues/372
https://github.com/Automattic/newspack-plugin/pull/796 adds UI for selecting …

feat: manual placement

---

.circleci/config.yml

Includes composer dependencies in the release job, otherwise the segmentation API won't work. 
Closes #359.
1. Create an alpha release by merging this branch into the `alpha` branch.
2. In CircleCI, confirm that the alpha release job completes successfully without errors.
3. Install the alpha release package on a test site, confirm that all segmentation features are working as expected.

fix: install composer dependencies on release job

---

api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
tests/test-api.php

Fixes two issues with category affinity segmentation.
1. On `master`, create a segment using category affinity criterion and assign it to a campaign
2. Observe the segment size ("This segment would reach…") not changing, always at 100%
3. Use the preview feature to view site as the segment member, observe that the relevant campaign is not displayed
5. Observe the segment size updated when as expected in the segment editor
6. Observe the preview feature working as expected

Segmentation: category affinity fixes

---

api/campaigns/class-maybe-show-campaign.php
api/segmentation/class-segmentation.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
tests/test-api.php
tests/test-insertion.php
tests/test-segmentation.php

Fixes two issues with "view as" feature.
1. On `master`, visit the Campaigns Wizard, "Preview" tab
2. Observe that when "Default (no segment)" is selected (with no groups), the preview will display test campaigns
3. Observe that when previewing a campaign with `once` frequency, it will not be displayed on subsequent preview
4. Switch to this branch, and `fix/view-as` branch on `newspack-plugin`
5. Observe the issues not reproducible anymore

Disregard frequency with view-as; handle 'all' in view-as spec

---

src/editor/EditorAdditions.js

When the dismiss button label is cleared out by the editor, the preview of the text remains on screen. This PR corrects this.
1. On `master`, create a new campaign, open `Dismiss Button Settings`, delete all text. Observe it is impossible to completely clear the text. 
2. Switch to this branch, observe the issue is resolved.

fix: remove dismiss button preview when empty

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/FrequencySidebar.js
src/editor/StatusSidebar.js
tests/test-insertion.php
tests/test-model.php

Test with https://github.com/Automattic/newspack-plugin/pull/809.
Replaces https://github.com/Automattic/newspack-popups/pull/365
Full testing instructions in https://github.com/Automattic/newspack-plugin/pull/809

feat: deprecate test mode and never frequency

---

includes/class-newspack-popups-model.php

There's currently a bug where Above Header campaigns will only be shown if they happen to have a timer trigger, which is an unused feature for this type of campaign. This corrects the issue.
1. On `master`, create a new campaign. Switch it to be an overlay, and set the trigger to scroll progress. Switch Inline back on, and set placement to Above Site Header.
2. Observe the campaign will not display in previews or front end. 
3. Switch to this branch, observe the campaign displays normally.

fix: corrected logic for above header display

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

Previews created from the preview tab does should be able to show any campaigns that match the selected segment, even if no groups are selected.
This PR can replace #356 as it contains all changes in that branch (required for properly testing that the Preview tab works with both published and unpublished campaigns). Leaving #356 open for now so that it can be tested separately if necessary.
1. On `master`, go to the Preview tab and select any segment while leaving the Groups field empty.
2. Observe that only published campaigns are displayed in the preview modal (basically only what can appear on the front-end rather than what matches the `view_as` param).
3. Check out this branch.
4. Select any segment while leaving Groups empty and "Show unpublished campaigns" OFF. Confirm that all …

fix: in preview tab, allow previewing without choosing groups

---

includes/class-newspack-popups-model.php
src/view/style.scss

Adds `newspack-above-header-popup` instead of `newspack-inline-popup` class to Above Header campaigns, causing them to bleed to the left/right edges. 
1. Create an Above Header campaign and an Inline campaign.
2. View in front end. Verify the inline campaign appears normal, and the above header bleeds to the left/right edges.

fix: remove inline class for above header campaigns

---

api/campaigns/class-campaign-data-utils.php
tests/test-api.php

When using view-as-segment for a segment that has 0 values for read counts, the logic will not take these values from the segment and instead falls back to any legitimate views that have been logged in the current browser. This leads to confusing, sometimes incorrect results where previewing may work correctly for some users and incorrectly for other based on their history of viewing the site. This branch resolves the issue by always adopting the `min_posts` and `min_session_posts` verbatim from the segment, regardless of whether they are zero or not. `max_posts` and `max_session_posts` are ignored, since being precisely at the min values is sufficient for matching the segment.
A separate question this raises is whether segments with 0 counts should even be allowed, but that's for later. …

fix: view-as-segment should always take min count values

---

includes/class-newspack-popups.php

The admin bar is meant to be hidden while previewing campaigns, but a small bug causes it to be hidden always. This PR corrects the issue.
1. On `master` verify the admin bar is not visible when viewing the site while as a logged in admin.
2. Switch to this branch, verify the admin bar is now hidden properly.
3. Preview several campaigns, verify the admin bar is NOT shown in the preview window.

fix: bug that causes admin bar to be hidden

---

includes/class-newspack-popups.php

https://github.com/Automattic/newspack-popups/pull/349 introduced a regression that causes the admin bar to be shown (empty) on the front end to logged out users. This doesn't happen on all sites (probably) because some are running plugins that use the `show_admin_bar` filter with a higher priority than 10, which effectively overrides this bug.  
1. On `master` view a page on the front end, logged out. You _may_ see the admin bar. If you don't, manually edit https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups.php#L58 and change the priority from 10 to a much higher number. This should cause the admin bar to display.
2. Switch to this branch, verify the admin bar is no longer visible. (If you changed the priority in step 1 you should also change it in …

fix: admin bar shown on front end logged out

---

includes/class-newspack-popups-inserter.php

Fixes a bug appearing when multiple inline campaigns would fail to be inserted in-between blocks.
1. Create a post with a single paragraph
2. Create two inline campaigns, both set at 100%
3. On `master`, observe only one of them is visible
4. Switch to this branch, observe both are visible

Fix insertion bug

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
tests/test-api.php

This addresses an edge case where a prompt (formerly "campaign") has been assigned a segment which was later deleted. This change caused segmentation tests to fail, so these have been refactored slightly to create real segments with unique IDs.
1. On `master`, create a segment, then create a campaign and assign the segment.
2. Navigate to Campaigns Wizard, observe results of the `newspack/v1/wizard/newspack-popups-wizard` API request. 
3. The campaign should have `options.selected_segment_id` set to the ID of the segment.
4. Delete the segment.
5. Navigate back to Campaigns Wizard, observe the API results still has the ID even though it doesn't exist.
6. Switch to this branch, refresh Campaigns Wizard. 
7. Observe `options.selected_segment_id` is `null`.

fix: set segment id to null if segment doesn't exist

---

includes/class-newspack-popups.php

Adds the option to specify campaign group and segment as query parameters when creating a new campaign. 
1. Create at least one campaign group and segment. Note the ID of the segment and the term_id of the group.
2. Go directly to a URL like this: `/wp-admin/post-new.php?post_type=newspack_popups_cpt&group={term_id}&segment={segment_id}`
3. Verify the new campaign has the correct group and segment assignments.

feat: specify group and segment in url for new campaigns

---

api/classes/class-lightweight-api.php

Adds `no-store`, `no-cache`, and `must-revalidate` headers to the lightweight API.
Closes https://github.com/Automattic/newspack-popups/issues/433
1. Verify the headers are present on API responses.
2. Verify the issue described in https://github.com/Automattic/newspack-popups/issues/433
, then create a build of the plugin from this branch and temporarily deploy it to the production site. Verify the fix resolves the issue.

fix: add cache control headers

---

api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

Along with https://github.com/Automattic/newspack-plugin/pull/856, fixes previewing logic when previewing prompts within a single campaign, when previewing active prompts, or when previewing unassigned prompts.
Follow testing instructions in https://github.com/Automattic/newspack-plugin/pull/856.

fix: preview functionality by campaign/group

---

includes/class-newspack-popups-model.php

Fixes overlay insertion so that category overlays are never displayed on non-matching pages or posts.
1. On `master`, create an overlay and assign a category. Make sure it's the only published overlay and it's in a segment that would be matched by new readers.
2. In an incognito session, visit the site front-end on the homepage or a post without a matching category. Observe that the overlay is shown even though its category doesn't match the page.
3. Check out this branch.
4. Visit the site in a new incognito session. This time confirm that the overlay only appears when visiting a post with a matching category.
5. Publish a second overlay in the same segment and don't assign a category to it.
6. Visit the site in a new incognito session. Confirm that on posts with a category that matches …

fix: prevent category overlays from being fetched erroneously

---

includes/class-newspack-popups-model.php
src/view/style.scss

When previewing, a user might be confused as to what will actually be visible for the reader. In this PR, styling for inactive (draft) prompts is introduced in the preview window.
1. Visit the Campaigns Wizard
2. Preview a segment
3. Observe that inactive (draft) prompts are marked with striped overlay and a label in top-left corner

Campaigns Wizard: mark draft prompts in preview

---

includes/class-newspack-popups-model.php

This resolves an issue that can occur when a site has a substantial number of prompts. Most of the prompt queries do not have `posts_per_page` set, which means they will have a limit of 10. If there are many more than 10 prompts, there can be situations where prompts that should be shown are not returned by the query, and therefore not shown.
1. On `master` create at least one post with a category.
2. Create a new inline prompt, set the category to match the post.
3. Create at least 10 more inline prompts. Assign these to a segment that would not include first time visitor (e..g newsletter subscriber)
4. View the categorized post in an incognito window. Observe you do not see the prompt. 
5. Switch to this branch and refresh the page. Observe you now see the prompt.

fix: increase max number of prompts to retrieve

---

includes/class-newspack-popups-inserter.php

Allows prompts placed manually via shortcodes to be displayed in previews.
1. On `master`, create a segment with min. 2 articles read and an inline prompt assigned to the segment.
2. Place the prompt in a page's content via a shortcode.
3. In a new incognito session, view at least two articles, then visit the page with the shortcode and confirm that you see the prompt where you placed it.
4. Preview the segment and navigate (in the preview window) to the page with the shortcode. Confirm that you do NOT see the prompt.
5. Check out this branch, then preview and navigate to the same page again. Now confirm that you do see the prompt where placed via shortcode.

fix: show shortcoded prompts in previews

---

includes/class-newspack-popups-segmentation.php

Along with https://github.com/Automattic/newspack-plugin/pull/886, adds server-side validation of segmentation sort request params. Halts operation and returns an error if the passed segment IDs don't match segment IDs that exist in the options table.
Closes https://github.com/Automattic/newspack-plugin/issues/882.
Follow testing instructions in https://github.com/Automattic/newspack-plugin/pull/886.

feat: validate segmentation sort operations

---

README.md
api/campaigns/class-maybe-show-campaign.php
tests/bootstrap.php

Removes the requirement for the `ENABLE_CAMPAIGN_EVENT_LOGGING` constant to be present and `true` in order to enable visit logging for segmentation purposes. This requirement results in new sites installing the plugin for the first time getting only half-functional segmentation features until the constant is added.
Now that segmentation features have been live for some time without major issues, in order to better support new sites, it might be time to flip the condition: if the `DISABLE_CAMPAIGN_EVENT_LOGGING` is defined and `true`, then visit logging is disabled. Otherwise, it is enabled by default.
Closes #459.
1. Create a new site and install/setup the Newspack plugin and this plugin.
2. If it isn't created automatically, create the `newspack-popups-config.php` file as [described in …

feat: enable visit logging by default

---

api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-model.php
src/editor/SegmentationSidebar.js
src/editor/style.scss
tests/test-api.php

Along with https://github.com/Automattic/newspack-plugin/pull/874, allows multiple segments to be assigned to each prompt. When deciding whether to show a particular prompt to a reader, all assigned segments are taken into account and the prompt is shown if one of the assigned segments is the reader's highest-priority matching segment.
Depends on #432.
Closes #442.
Follow testing instructions in https://github.com/Automattic/newspack-plugin/pull/874.

feat: allow multiple segments per prompt

---

api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-segmentation.php

Enable cookie spoofing when previewing.
TODO/Question: this would spam the logs and DB with the preview-generated data – perhaps it should be removed in a CRON job?
Follow instructions in https://github.com/Automattic/newspack-plugin/pull/891

Handle visit data also in previews

---

includes/class-newspack-popups-segmentation.php

Ensures non-interaction mode sticks to the promise of disabling API calls.
1. On `master`, verify that when non-interaction mode is on, a call is made to the API on page load, and that segmentation-derived custom dimensions are reported*
2. Switch to this branch, observe the above is not true anymore
3. Turn off the non-interaction mode and verify that segmentation-derived custom dimensions are reported
4. Add a `NEWSPACK_POPUPS_DISABLE_REPORTING_CUSTOM_DIMENSIONS` flag of value `true` to `wp-config.php`
5. Observe that the API calls for prompts are made, but not for custom GA config, and that the segmentation-derived custom dimensions are not reported. This flag is for additional debugging purposes.
\* look for `collect' calls in network tab. The custom dimensions have to be configured …

Prevent segmentation-derived custom dimensions reporting in non-interaction mode

---

includes/class-newspack-popups-inserter.php

Closes #465, supersedes #466
1. Create a post with a _massive_ jetpack slideshow block* at the top followed by at least five other blocks
2. Create five inline prompts, each at a position of 25% more than the last one
3. On `master`, observe the prompts are rendered at the top of the post content
4. Switch to this branch, observe the prompts are rendered at intended placements
\* Mine had about 80 images, beat that

Fix placement computation

---

includes/class-newspack-popups-inserter.php

There's no need to poll the AMP Access API for prompts that aren't published/active. This fixes a bug where prompts that are inserted via shortcode (either in widgets or directly in post content) are checked against AMP Access authorization even if they're not published, which could result in unnecessary client data logging and DB writes even if the authorization result is `false`.
1. On `master`, create a draft prompt and assign to any segment.
2. Insert the prompt via shortcode into any post or page using `[newspack-popup id="<PROMPT ID>"]`.
3. Visit the post in a new incognito session. In Dev Tools > Network, filter XHR requests by `api/campaigns` and inspect the request. Observe that the response [includes the ID of your draft prompt](https://d.pr/i/h814fj), indicating that it's being …

fix: no amp-access auth check for inactive prompts

---

includes/class-newspack-popups-inserter.php

Potential fix for a bug that causes Homepage Posts to sometimes render the wrong posts.
1. Visit https://abq-debug.newspackstaging.com in two separate browser sessions: one logged in and the other not logged in. Observe that while logged in, the first Homepage Posts block shows the correct post—the most recently published post—while the other session seems to skip that post and show the next most recently published post.
2. View several articles and note the positions of inline prompts.
3. Temporarily disable the `newspack-popups-release` plugin and install/activate the plugin from this branch.
4. Refresh the homepage in both sessions and confirm that all Homepage Posts blocks are showing the same posts, now.
5. View several articles and confirm that the inline prompts are still injected …

fix: render_block causes Homepage Posts to render wrong post

---

api/segmentation/class-segmentation-custom-ga-config.php

Closes #461.
1. Ensure Campaigns-related custom dimensions are configured
2. Visit the site as a non-logged-in user
3. Observe the return value of the request to `/wp-content/plugins/newspack-popups/api/segmentation/index.php` - the campaigns-related custom dimensions' values should be returned as strings, no booleans

Process custom dimensions' values as strings

---

api/classes/class-lightweight-api.php
api/segmentation/class-segmentation.php
includes/class-newspack-popups-segmentation.php

The Campaigns plugin sets a transient for each prompt/user combination, which on a high traffic site is a source of significant options table bloat, causing performance issues. https://github.com/Automattic/newspack-popups/issues/478 lists a number of ways this can be optimized. This PR addresses one of these, creating a custom database table for Campaigns transients, taking the burden off the WordPress options table. At the moment when the table is created, all existing Campaigns transients are copied over. I opted not to delete the transients in the options table as this would be a potentially destructive action. We can manually prune the options tables of production sites on a case-by-case basis.
1. With this branch checked on, go to any wp-admin page. Observe a new database table is …

refactor: custom db table for campaign transients

---

includes/class-newspack-popups-segmentation.php

Adds a `date` column to the new (#488) custom transients table. The timestamp will be useful for data pruning in the future, as outlined in #478.
1. Drop the new custom transients table
2. Visit the site 
3. Observe the table was created, with a `date` column. The default values should be the current timestamp.

Add timestamp column to custom transients table

---

includes/class-newspack-popups-inserter.php

#466 and #468 tweaked the inline prompt insertion logic to account for slideshows, but it wasn't enough to truly fix the insertion logic in posts with slideshows. This PR introduces the concept of ignoring certain types of blocks for purposes of inline prompt insertion; these blocks may contain a massive amount of block content but will only take up a small amount of visual space in the post content, so their content length shouldn't be used for purposes of inline prompt insertion.
The new feature lets us designate any block to be ignored by adding it to the `$blacklisted_blocks` array in `class-newspack-popups-inserter.php`. At time of PR, only `jetpack/slideshow` and `newspack-blocks/carousel` are designated as such, but more can be added if they're found to cause similar issues with …

fix: introduce blacklisted blocks to ignore when inserting prompts

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups.php

Closes #447.
1. On `master`, raname your default category to something else than "Uncategorized"
2. Visit the Campaigns wizard, observe that the prompts have the default category assigned on activation
3. Switch to this branch; deactivate & activate a prompt - observe it does not have the default category assigned
4. In Campaign Wizard, assign the default category via the category filtering options (![image](https://user-images.githubusercontent.com/7383192/111289683-aee46080-8645-11eb-8bc7-2895ecc06711.png)), observe the category filtering is applied
5. Edit a prompt, assign the default category via the editor sidebar, observe the category is applied

Remove default category on prompt activation

---

includes/class-newspack-popups-inserter.php

This PR fixes a few small issues with the `newspack_newsletters_assess_has_disabled_popups` filter:
1. [The logic in the `get_post_meta( get_the_ID(), 'newspack_popups_has_disabled_popups', true )` check](https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups-inserter.php#L123-L128) would override anything which hooked into the filter before that check. Best practices around filters are that a filter should only modify the return value if it is different than the default return value; that will correctly ensure that any other plugin is able to modify the return value. See the testing instructions for a more clear example of why this is an issue.
2. [The default return value in `::assess_has_disabled_popups` was …

Allow filters to suppress popups better

---

.circleci/config.yml
api/campaigns/class-maybe-show-campaign.php
api/campaigns/class-report-campaign-data.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-inserter.php
tests/test-api.php

Taking inspiration from #478, makes two changes to the way the plugin handles writing transients:
a. Transients are not written for unrecognized readers who do not have any ~read-posts~ recorded history (this should avoid writing new empty client data rows for bounced readers), and
b. Writes a maximum of one row per client, with all prompt-related data collected in that row.
Does not do anything to add expiration logic to transients (let's save that for another PR to keep this testable).
Since the transient name and data format differ slightly, this PR also handles the legacy format. If we can't find client or campaign data using the new transient name, we look for data using the legacy name. Then, if legacy data is found, we save that data with the new name and format and then delete the …

refactor: minimize transients written to one per reader

---

.distignore
api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-custom-placements.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-placements.php
includes/class-newspack-popups.php
src/blocks/custom-placement/block.json
src/blocks/custom-placement/edit.js
src/blocks/custom-placement/editor.scss
src/blocks/custom-placement/index.js
src/blocks/custom-placement/view.php
src/blocks/index.js
src/editor/DismissSidebar.js
src/editor/FrequencySidebar.js
src/editor/SegmentationSidebar.js
src/editor/Sidebar.js
src/editor/utils.js
tests/bootstrap.php
tests/test-blocks.php
tests/test-insertion.php
webpack.config.js

Along with https://github.com/Automattic/newspack-plugin/pull/898, creates a new system for placing prompts manually in post or page content. Prompts assigned to a custom placement will be rendered on the page and displayed according to segmentation rules (one prompt per segment per block).
This MVP provides three custom placements that can be placed in post content via a new Custom Placement block. Could be extended to allow editors to create and update their own custom placements, too, but this isn't included yet.
Closes #444.
Follow testing instructions in https://github.com/Automattic/newspack-plugin/pull/898.

feat: custom placements

---

src/editor/Sidebar.js
src/editor/style.scss

Updates the `ToggleControl` to make a prompt inline vs. overlay to a pair of radio buttons. This makes it much clearer that a prompt can be either overlay or inline.
Closes #471 (but I selfishly made the executive decision not to kill the "Display prompt title" option, because I use it a lot for testing).
1. Check out this branch, run `npm run build`
2. Edit a prompt and expand the "Prompt Settings" sidebar.
3. Confirm that the prompt type is now set using these radio buttons, that you can only select one or the other option, and that when "inline" is selected, only inline placement options appear (and vice versa).

feat: use RadioControls for prompt type selection

---

src/blocks/custom-placement/edit.js

1. On `master`, insert a Custom Placement block on a post or page
2. Observe a React error in the JS console about missing "key" prop
3. Switch to this brach, rebuild
4. Observe error gone

Add missing key prop in CustomPlacementEditor

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

With the changes in #416, separate retrieval of overlay and inline prompts is not necessary anymore, since the multiple overlays are allowed to be rendered on the page (API logic decides which is shown). 
Handling of the category condition was redundant, since categorised prompts are filtered out by `should_display` method.
This is mostly a refactor, with one user-facing change: the preview is now disregarding the category. Before, segment previews would not display a categorised prompt, unless the preview post had matching category (which could happen by chance). With changes here, all prompts tied to a campaign and/or segment will be displayed in the preview.
Mostly a refactor/performance improvement, so verify that everything works as expected

Simplify prompt retrieval

---

includes/class-newspack-popups-custom-placements.php
includes/class-newspack-popups-inserter.php
tests/bootstrap.php
tests/test-insertion.php
tests/wp-unittestcase-pagewithpopups.php

Fixes two small bugs, refactors and adds tests.
2. Create two inline prompts at 0% scroll, "everyone" segment, then insert one of them using a shortcode in a post, right at the top.
3. Open Campaigns Wizard, preview the non-shortcoded prompt 
4. Issue 1. - Observe that the previewed prompt is rendered twice - in the shortcode spot and according to the inline placement rules
5. Load a page as non-admin, where some inline prompts, but none custom-placement prompts are rendered 
6. Issue 2. - Observe the payload in `GET /newspack-popups/api/campaigns/index.php` contains duplicated items in `popups` query var
7. Switch to this branch, observe both issues gone

Small shortcode, amp-access fixes

---

api/campaigns/class-maybe-show-campaign.php
tests/test-api.php

Fixes previewing the "everyone" segment. When previewing "everyone", only prompts that are not assigned to any segments should be shown.
1. On `master`, create a few prompts that have no segment (thus appearing under "Everyone" in the Campaigns wizard), plus several prompts assigned to one or more segments.
2. Preview the "Everyone" segment. Observe that all prompts are shown in the preview.
3. Check out this branch and preview again.
4. This time, confirm that only prompts with no segment are displayed.

fix: when previewing "everyone" segment, show only prompts with no segments

---

api/classes/class-lightweight-api.php
includes/class-newspack-popups-segmentation.php

1. Removes preview session data when purging data
2. Adds updating `date` column on client data save, which will let us start removing stale client rows in the future
1. Optionally, remove all rows from the `*newspack_campaigns_transients` table for clarity
2. Visit some posts in incognito mode, see some prompts, just to get some client data into the table
3. Do some preview sessions in the Newspack Campaigns wizard, so preview sessions data is created in the table
4. Verify the data was added in the table, take note of the `date` column value
5. Browse & preview more, verify the `date` is updated to current date (the column should really be called `updated_at`)
6. Trigger the data pruning cron job*
7. Observe the preview data has been removed from the table
\* E.g. by running `wp cron …

DB enhancements

---

api/classes/class-lightweight-api.php
includes/class-newspack-popups.php
tests/bootstrap.php
tests/test-api.php

Ignores requests made by commonly known web crawlers in the API.
1. Verify the API works for regular requests made from a web browser
2. Set up Google Search Console w/ the site (e.g. by setting up Site Kit plugin)
2. Take note of the row count in the transients and events table*
3. Submit a URL of a post (on which prompts are displayed) to the URL inspection in Search Console UI
4. Wait for it to be crawled by Google** 
5. Verify that the row counts in the tables did not increase
\* `$ wp db query "select count(*) from wp_newspack_campaigns_transients"`, `$ wp db query "select count(*) from wp_newspack_campaigns_events"`
\** In my testing I've seen that Google hit my site after a few minutes (by means of an `error_log`ing the user agent in API), but it did not show up in the Search …

API: ignore crawler traffic

---

includes/class-newspack-popups-inserter.php
tests/test-insertion.php

Fixes a regression introduced in #506 
2. Create a post with a tag and an inline prompt with no tags assigned
3. Observe the prompt is not displayed on the post
4. Switch to this branch, observe the prompt is displayed
5. Assign a different tag to the prompt, observe it's now not displayed (since tags don't match)
6. Assign the post's tag to the prompt, observe the prompt is displayed

Fix tag criterion

---

includes/class-newspack-popups-inserter.php
tests/test-insertion.php
tests/wp-unittestcase-pagewithpopups.php

Fixes two unrelated bugs.
2. Preview a draft inline prompt, observe that it's not shown neither in segment, nor single prompt previews
3. Create two above-header prompts: firstly (it has to be published earlier) one with segment assigned, then one without
4. Visit the site in incognito as the segment member - observe the non-segmented prompt displayed instead of the segmented one
5. Switch to this branch, observe the issues are gone

Fixes: drafts previews, segmentation orderiing

---

api/classes/class-lightweight-api.php
includes/class-newspack-popups-inserter.php
tests/test-insertion.php

Inspired by https://github.com/Automattic/newspack-popups/pull/515#discussion_r609913318. I felt that because the category and tag filtering should behave the same way, they should share the same logic and method. This PR combines the methods that compare post and prompt categories and tags into a single method that takes a second `$taxonomy` arg (defaulting to category). Just seemed like one tiny thing we could do to reduce the mental load when troubleshooting prompt display logic.
This is a pure refactor, so the behavior shouldn't differ at all from `master`. Test that prompts with and without categories and tags display as expected on posts with and without matching categories and tags.

refactor: combine tags/category filtering methods into one

---

includes/class-newspack-popups-inserter.php

Adds special handling for "Classic Content" blocks when it comes to inline prompt insertion. Instead of treating the entire block as a single block, like other blocks, we now break up the Classic Content string by block-level HTML elements (`</p>`, `</ul>`, `</ol>`, etc.—not [every single one](https://developer.mozilla.org/en-US/docs/Web/HTML/Block-level_elements), but the main ones I think make sense to insert prompts before or after) and insert prompts between those elements. Should work whether the Classic Content block is the only block in a post, or if it's mixed with other blocks.
The insertion approach is inspired by the logic in the Super Cool Ad Inserter plugin, but simplified since we already have handling for short content, lots of prompts, etc. It also looks for various …

feat: handle classic content for inline prompt insertion

---

src/view/style.scss

There was a dependency on Newspack theme in secret form field hiding.
1. Install the plugin on a site without Newspack theme
2. Go to WC checkout page
3. Observe the `#newspack-cid_field` form field is not visible

Ensure WC client ID field is hidden

---

includes/class-newspack-popups-inserter.php

Fixes a small issue.
It looks like the Group or Columns blocks are inserting an empty block somewhere, which gets picked up as the classic block in the insertion logic.
0. On `master`
1. Create a post with the following content: a Group, with Columns, a single Column inside, and a Heading in the Column
2. Ensure some inline prompts are inserted in the post
3. Observe and error (when in WP debug mode) shown on the front-end about `Offset not contained in string`
4. Switch to this branch, observe no error shown

Fix: empty blocks handling

---

includes/class-newspack-popups-model.php
src/view/index.js

Fixes a bug.
Ensures all prompt elements have a `newspack-popup` CSS class for unified targeting.
1. On `master`, create an above-header prompt
2. View site in non-AMP mode, dismiss the prompt
3. Observe the page reloads, with the prompt still there
4. Switch to this branch, dismiss the prompt - observe the page does not reload and the prompt does not show up again

Fix: interaction of above-header prompts in non-AMP mode

---

includes/class-newspack-popups-model.php
tests/test-api.php

Fixes a bug discovered while testing https://github.com/Automattic/newspack-plugin/pull/944, which limits the number of non-shortcoded and non-custom-placement posts checked against `amp-access` to 10. This fix bumps that limit up to 100, which should give sites a lot more headroom.
1. On `master`, publish a lot of prompts to "Everyone" or an easily matched segment—at least ~15 of all types (inline, overlay, above-header) which will be programmatically inserted and should be displayed together. Additionally, publish a couple of shortcoded and custom placement prompts and insert into a post.
2. View the post in a new incognito session. Observe that only 10 of the programmatically inserted prompts are displayed, plus the shortcoded and custom placement prompts.
- If you inspect the DOM and …

fix: bump query limit up to 100 for eligible prompts

---

includes/class-newspack-popups-model.php

#497 introduced event encoding to make the GA config size smaller. With changes in https://github.com/Automattic/newspack-plugin/pull/944, this is no longer necessary. On top of that, prompt placement is added to the event label.
1. Use `feat/ga-amp-config-batching` (https://github.com/Automattic/newspack-plugin/pull/944) branch of Newspack Plugin
2. Load a page with some prompts, observe* GA custom events being sent with `Newspack Announcements` category, `<prompt-position>: <prompt-title> (<prompt-post-id>)` label (e.g. `Inline: Newletters CTA (42)`), and a human-readable name
3. After a day, observe these events showing up properly in Newspack plugin's Campaigns Analytics screen
\* to view GA reporting calls, filter the requests in the Network devtools tab by `collect`

Analytics: revert event encoding

---

includes/class-newspack-popups-inserter.php

Fixes a bug where the Inserter class tries to inject prompt markup into attachment descriptions and other content that fires the `the_content` hook, instead of the main article content. Does so by using the existing `newspack_campaigns_post_types_for_campaigns` filter to only insert prompts into content for posts and pages, by default, plus any post types added via that filter hook.
1. On `master`, publish a post and set a featured image. In the featured image details, enter some content into the Description field (not the Caption field). Make sure you have some inline and/or overlay prompts active that will be rendered on the post.
2. View the post in a new incognito session. Observe that the prompts are not displayed, and that their markup might even be partially injected into the …

fix: use filter to decide which post types to insert ads into content

---

api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

On top of a config variable, exposes the API debugging info via a request param. I don't this this is a security concern, as the debugging information does not contain anything sensitive.
Enables debugging the prompt suppression reasons.
Also, makes a small tweak to `amp-access` payload creation.
1. Visit a page with some prompts, observe that (only) after appending a `newspack-campaigns-debug` parameter to the URL, `debug` key is returned along with the response from `GET /api/campaigns/index.php`
2. Observe that the response contains a `suppression` key, with data about why a particular prompt was suppressed
3. Try out different suppression scenarios, observe them reflected in the response.
4. Insert an overlay prompt via a shortcode _EDIT: and assign it to a category, visit a post of …

API debugging

---

includes/class-newspack-popups-model.php

Fixes a bug introduced in https://github.com/Automattic/newspack-popups/pull/497. Besides the reproduction scenario below, the fixed bug probably caused inflated counts of `Form Submission` custom GA events. This is because the bug makes other forms' dismissals being reported as a newsletter-bearing form submissions - however I've been able to reproduce that only on non-AMP pages.
1. On `master`, set up an inline prompt containing the Mailchimp newsletter subscription block 
2. Set the site to AMP transitional mode
2. Visit a page with the prompt
3. Observe that the `Form Submission` GA custom event* is not fired upon form submission on AMP version
5. Observe the `Form Submission GA custom event fired on both AMP and non-AMP versions
\* filter the requests in the …

Fix form selector for analytics

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-custom-placements.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
package-lock.json
package.json
src/blocks/custom-placement/index.js
src/blocks/index.js
src/blocks/single-prompt/block.json
src/blocks/single-prompt/edit.js
src/blocks/single-prompt/editor.scss
src/blocks/single-prompt/index.js
src/blocks/single-prompt/view.php
src/editor/Sidebar.js
src/editor/utils.js
tests/test-blocks.php
tests/test-insertion.php

Does a few things:
1. Reinstates "manual-only" as a placement option (not a frequency option as it was previously). Prompts with this placement option will never get programmatically inserted anywhere, so they won't be displayed unless used in a shortcode or the new Single Prompt block (see below).
2. Creates a Single Prompt block which allows you to select a single inline or manual-only prompt to be displayed where placed in a post or page. This is basically a controlled wrapper UI that renders the prompt as a `[newspack-popup]` shortcode, and will hopefully be a more user-friendly alternative to using shortcodes for this purpose.
3. Makes the help text shown alongside the Placement options in the editor sidebar more helpful, by describing the currently selected option's behavior. Also …

feat: single prompt block and manual-only placement option

---

includes/class-newspack-popups-model.php

Applies the `the_content` filter to rendered prompt content. This allows shortcodes in prompt content to be rendered and processes prompt content like any other WP post content.
~I'm not sure if this might cause other side effects with prompt rendering, but so far I'm not seeing any issues. If we do start encountering unwanted side effects, we could try replacing `apply_filters` with `do_shortcode` to only process shortcodes in the prompt content.~ Turns out applying the `the_content` filter does cause an endless loop when rendering prompts in a custom placement block. This was caught by the e2e test `test_e2e_mutual_exclusion`. Using `do_shortcode` instead successfully renders shortcodes inside prompt content and also passes all tests while being a little less far-reaching in its …

feat: allow shortcodes in prompt content

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups.php
tests/test-insertion.php

Closes #430.
1. In `master` branch, set up a new prompt above the header.
2. Visit an account-related page like `/my-account/lost-password/`, and observe the prompt on the page.
3. Check out this branch, refresh the post. Confirm that the prompt is not displayed on the page.

fix: prevent prompts in account related posts

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/Duplicate.js
src/editor/Preview.js
src/editor/index.js
src/editor/style.scss
tests/test-e2e.php

Adds functionality to duplicate a prompt. Copies are created as new draft prompts with the same title/content, taxonomy terms, and prompt-related meta values as the source prompt.
Prompts can be duplicated from either the Campaigns dashboard or from a single prompt editor screen.
Closes #554.
1. Ensure Campaigns is on this branch and Newspack Plugin is on https://github.com/Automattic/newspack-plugin/pull/1001.
2. In WP admin, visit **Newspack > Campaigns**. Confirm that in the primary popover menu for any prompt, there's a new menu item to "Duplicate" the prompt:
3. Click "Duplicate". Confirm that a new draft prompt is created with the title "Copy of <original prompt title". It should have the same segment assignments, categories, tags, and meta values (so if copying an overlay, it …

feat: duplicate a prompt

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
package-lock.json
package.json
src/editor/Duplicate.js
src/editor/style.scss
src/editor/utils.js

Improves the UI for duplicating prompts. When duplicating a prompt from the single-prompt edit screen, you are now presented with a modal with the opportunity to rename the duplicate before creating it, an option to close the modal or edit the duplicate after it's created, and a notice if the duplicate is created without a campaign (which would cause it to be visible in the Campaigns dashboard only under the "unassigned" filter).
Closes #560.
1. Go to **Newspack > Campaigns**. Open the primary popover menu and select "Duplicate". Confirm that you now see a modal with a text input to rename the duplicate, which loads the default name ("Prompt title copy", "Prompt title copy 2", etc.) at first.
2. Edit the name, but click "Cancel", click "Duplicate" again on the same prompt, confirm that …

feat: improved duplication UI via modal

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
src/editor/Sidebar.js

In WP 5.8, blocks-based widget content is no longer saved in the `widget_text` option. Therefore, the method we use to get prompts placed in widget areas no longer works—which means that any prompts with the "manual only" placement that won't appear in the post content that are placed in a widget area via a Single Prompt block won't be included in the AMP access request and thus will never be shown. This PR fixes this by ensuring that any active "manual only" prompts are always checked against AMP access. This hopefully won't result in much performance impact since "manual only" prompts are meant to be used sparingly.
Closes #573.
1. On a site running WP 5.8, go to **Appearance > Widgets**. Insert a Single Prompt block and select an active block that has the "manual only" placement.
2. …

fix(wp-5.8): allow manual-only prompts to appear in widget blocks

---

includes/class-newspack-popups.php

Avoids a hard editor crash in the new WP 5.8 widgets block editor by not enqueuing editor assets that assume we're editing a single post.
Closes #570.
This one is a bit hard to test because the crash doesn't always occur on every site. To truly confirm the fix, you'll need to have access to a site such as [this one](https://wp58test-localprofile.newspackstaging.com/wp-admin/widgets.php) where the bug is confirmed to be happening with the latest plugin release (ping me for credentials to this site).
1. On `master` or the latest release package, visit **Appearance > Widgets** and observe a hard editor crash with a JS console error such as:
```
TypeError: _wordpress_edit_post__WEBPACK_IMPORTED_MODULE_4__ is undefined
PopupsSettingsPanel webpack:///./src/document-settings/index.js?:31
...
``` …

fix(wp-5.8): avoid an editor crash due to missing data in widgets block editor

---

includes/class-newspack-popups-inserter.php

Allows prompts in Custom Placements to be rendered when placed via widgets.
Closes #576.
Confirm that this solves #576—prompts placed in widgets with the Custom Placement block should be shown to readers according to segmentation logic.

fix: allow custom placement prompts to be displayed if in widget blocks

---

api/setup.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php

Small tweaks:
1. Assume the DB prefix is `wp_` if it's not defined. 
2. Ensure API URL has uses HTTPS - it happened on my local instance that the `plugins_url` returned HTTP URL despite the site URL set to HTTPS. Don't know why, but this won't hurt - if site is not HTTPS, `amp-access` won't work anyway.
1. Remove `DB_PREFIX` definition from your Campaigns config file
2. Ensure the Campaigns API works correctly

fix: assume DB prefix; ensure https

---

includes/class-newspack-popups-model.php

Enables trash retrieval.
_Instructions in https://github.com/Automattic/newspack-plugin/pull/1052_

feat: enable retrieving prompts from trash

---

includes/class-newspack-popups-segmentation.php
tests/test-segmentation.php

Remove reader data not updated in 30 days and not containing any donations or subscriptions.
Closes #583.
There is a test added, but double-checking won't hurt.
1. Manipulate the reader data* so that you can test the following premises:
1. A reader who did subscribe or donate, and was not updated since more than 30 days should **not** be removed
2. A reader who did not subscribe nor donate, and was **not updated** since more than 30 days should be removed
3. A reader who did not subscribe nor donate, and **was updated** less than 30 days ago should **not** be removed
2. Force pruning by running `wp cron event delete newspack_popups_segmentation_data_prune` and loading any admin page
3. Observe pruning results in the DB 
\* In the `wp_newspack_campaigns_transients` table. The `date` (the …

feat(api): remove reader data if no updates in 30 days

---

includes/class-newspack-popups-model.php

Remove whitelist for options setting, since all options unhandled in the `switch` are post meta. 
This is used by the Campaigns Wizard, test setting prompts' options via the Wizard. See https://github.com/Automattic/newspack-plugin/pull/1065#issuecomment-887540829

feat: remove options whitelist

---

includes/class-newspack-popups-inserter.php

Fixes a regression introduced in #587 
1. Create a prompt and set it to above header placement
2. Observe that it's not displayed on pages when on `master`
3. Switch to this branch, observe the prompt is displayed

fix: above-header popups on pages

---

includes/class-newspack-popups-model.php

Closes #598.
1. On `master`, create a prompt with a Jetpack Mailchimp form
2. Visit the frontend, sign up for the newsletter - observe that the payload to `POST /wp-content/plugins/newspack-popups/api/campaigns/index.php` has a wrong value in the `email` param (not substituted for the email address)
3. Switch to this branch, observe the `email` param i sent correctly

fix: email substitution in newsletter forms

---

src/view/utils/index.js

Tiny bugfix.
Can be taken at face value, but the issue appeared on after making a recurring donation using WC. WC then creates and logs in a user, so a `user_id` param of type `number` [is used in `amp-analytics` config](https://github.com/Automattic/newspack-popups/blob/0f1ae4d1ad16e8378940267af6bd227223f533a3/includes/class-newspack-popups-segmentation.php#L256). Anyway, the value of a URL param can be a number, too.

fix: amp analytics polyfill tweak

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
package-lock.json
package.json
src/editor/PostTypesPanel.js
src/editor/index.js
src/editor/utils.js
tests/test-e2e.php
tests/test-insertion-cpt.php
tests/test-model.php
tests/wp-unittestcase-pagewithpopups.php

Closes #567 .
1. Create a prompt, observe a new panel in the sidebar editor - "Post Types"
2. Observe "Posts" and "Pages" selected by default
3. Publish the prompt, observe it behaving as expected
4. Visit a CPT, observe the prompt is not visible there
5. In the editor select the CPT name and re-publish the prompt
6. Observe the prompt visible on the respective CPT
7. Create another prompt, and use a filter to set globally supported CPTs*
8. Publish the prompt, observe it is visible on the globally-enabled CPT
\* e.g.:  
```
add_filter( 'newspack_campaigns_post_types_for_campaigns', function( $post_types ) {
$post_types[] = 'press_release';
return $post_types;
} );
```

feat: targeting campaigns by post type

---

includes/class-newspack-popups-inserter.php
tests/test-insertion.php
tests/wp-unittestcase-pagewithpopups.php

Fixes a previewing bug.
1. On `master`, visit the Campaigns wizard and preview a segment
2. Notice that draft prompts are not being displayed
3. Switch to this branch, observe the draft prompts are displayed

fix: include drafts in segment previews

---

includes/class-newspack-popups.php
tests/bootstrap.php

Closes #591.
1. Ensure Site Kit w/ Analytics module is configured on your site, and that the data is reported to GA*
2. On `master`, remove (or rename) the [configuration file](https://github.com/Automattic/newspack-popups/blob/master/README.md#config-file)
2. Observe that the pageview request is not sent now 
3. Switch to this branch, observe the pageview request is sent
4. Reinstate the configuration file, observe the pageview request is sent still
\* Visit the frontend, verify a `GET google-analytics.com/r/collect` request is sent on page load, with a `t=pageview` parameter

fix: disable until configured

---

includes/class-newspack-popups-inserter.php
tests/test-insertion-cpt.php

Fixes a bug related to CPT handling.
1. Ensure you have a publicly-viewable CPT (e.g. from [`newspack-podcasts`](https://github.com/Automattic/newspack-podcasts/)) 
1. On `master`, create two inline prompts - one set to `post` post type only, the other to the CPT
2. Visit a post and a CPT  - observe the post-only prompt is appearing on the CPT
3. Switch to this branch, observe that the post-only prompt is appearing only on posts and the CPT-only prompt only on CPTs

fix: cpt handling

---

includes/class-newspack-popups-model.php

It turns out that another plugin can [modify](https://github.com/INN/link-roundups/blob/be0f2a93a892904bf1d55a9dfd8ccf9311822d87/inc/link-roundups/class-link-roundups.php#L60) the `WP_Query` ran by this plugin!
1. Install the [Link Roundups plugin](https://github.com/INN/link-roundups/)
2. Create at least one link roundup
3. On `master` visit Newspack->Campaigns wizard and observe the link roundups listed as prompts*
4. Switch to this branch, observe the problem gone 🪄
\* in my testing, I had to also update "Link Roundups" options and set custom name and slug

fix: ensure only popup CPTs are handled

---

api/segmentation/class-segmentation-client-data.php

Turns out that NRH has some legacy merge fields naming schemes. This PR ensures that if a merge field has the string `DONAT` in the name, it will be treated as a merge field denoting a donor. This should cover such cases as `DONATION`, `DONATED`, `HUB-DONATION`.
Same flow as #305, but with different merge field names.

feat(segmentation): improve how Mailchimp merge fields are handled

---

api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-segmentation.php
tests/test-api.php

Fixes a bug with donor tagging via donor landing page. The bug resulted from an unfortunate sequence of PRs - https://github.com/Automattic/newspack-popups/pull/397 was submitted before https://github.com/Automattic/newspack-popups/pull/408, but merged after it, and in the process a couple of lines of code were erroneously removed.
1. Visit the Campaign Wizard, settings tab
4. Set a page to act as a donor landing page (a "Thank you for donation" page) via "Donor landing page" setting
5. Create two prompts, one targeted at donors (A), other at non-donors (B)
6. Visit the site in a new session, observe the prompt B is displayed
7. Visit the donation landing page and navigate to another page or post
8. Observe that prompt A is now displayed

fix: donor landing page

---

src/view/index.js

Same issue as in https://github.com/Automattic/newspack-plugin/pull/1216
1. Set up a site with Site Kit, connecting both Analytics & Google Tag Manager modules
2. Visit a page which has AMP disabled
3. Observe `gtag is not defined` errors in the JS console
4. Switch to this branch, observe no errors shown.

fix: check if gtm exists

---

includes/class-newspack-popups-model.php

enable showing the same post in popups and page if they both contain the homepage-posts block with
the same category filter.
fix #126 
1. On a new page add the homepage-posts block and filter the posts to be displayed by a category.
2. Add a new overlay prompt with a homepage-posts block as its content.
3. Filter the posts by the same category as 1. on the overlay homepage-posts block.
4. Load the page and observe that the posts on the page don't contain the posts on the popup.
5. Reload the page a second time and observe that the page still doesn't show the posts from the popup, but the popup doesn't show (popups are shown once or once a day).
6. If this https://github.com/Automattic/newspack-blocks/pull/886 is not merged, pull it, or apply the small changes from it.
7. Checkout this …

enable homepage-posts posts duplication  between a page and an overlay prompt

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

Cleans up the insertion logic a bit. Before, the post type conditions used a bit convoluted logic of checking the equality of globally-supported post types and prompt's post types. Also, the default value for the supported post types meta was set to the default post types in [meta registration](https://github.com/Automattic/newspack-popups/blob/89ba2147be4cdb4839eab5a4a59d02887a0a4fcf/includes/class-newspack-popups.php#L333), but to globally-supported post types as fallback in `get_popup_options` method. I've only run into this when running tests in isolation, and was not able to come up with a reproducible scenario.
Logic is refactored so that it's clear and readable:
1. If prompt's supported post types are same as the defaults, use the globally-supported post types
2. Otherwise, use …

fix: post type support conditions

---

api/segmentation/class-segmentation-client-data.php

https://github.com/Automattic/newspack-plugin/pull/1168 introduced a new name for the MC API key
option, which will be managed from `newspack-plugin` instead of `newspack-newsletters`. We do keep the
old name for backward compatibility.
~~BREAKING CHANGE: Change MC API key option name, we'll use the new one from `newspack-plugin` instead
of the old one from `newspack-newsletters`. Keeping the old name for backward compatibility.~~
1. Create a donation page if you don't already have one in local, with a one-time payment option.
2. Add an offline payment method in WooCommerce (Check payments).
3. Register a Mailchimp API key from the `newspack-newsletters` plugin `Newsletters > Settings > Mailchimp API Key`
4. I didn't find a way to get `mc_cid` and `mc_eid` on the request, so you can add a …

fix(segmentation): change MC API key option name

---

api/setup.php

Use WordPress constants to cover scenario where custom wp-content directory name is used
Closes #612
1. Configure WordPress to use custom WP_CONTENT_DIR
2. Apply changes proposed in this PR
3. Review access.log  for 200 Ok or Response in Developer tools.
- Code to be written to use wp constant for wp-content/plugins/ in  
https://github.com/Automattic/newspack-popups/blob/bb5b1cb871ca8b7f9f4c99f918c6892b49658f3b/api/setup.php#L9

Fix/Use WordPress Constants

---

includes/class-newspack-popups.php

Adjust the wording in the config instructions to avoid use of "here" as link text.
* [x ] Have you followed the [Newspack Contributing guideline](https://github.com/Automattic/newspack-plugin/blob/master/.github/CONTRIBUTING.md)?
* [x ] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/) and [VIP Go coding standards](https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/)?
* [x ] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?
Closes #454

Don't use "here" as link text

---

api/setup.php

Fixes a bug occurring when `WP_CONTENT_DIR` has no trailing slash. 
1. [Define](https://github.com/Automattic/newspack-popups/blob/b2ae835d045907ad28acd09cb5dce03732deb1ff/api/setup.php#L19) `WP_CONTENT_DIR` without trailing slash
2. Make sure your API config file is in `wp-content` (not WP root) 
3. On `master`, observe the `GET` call to `/wp-content/plugins/newspack-popups/api/segmentation/index.php` failing (returning `missing config file`)
4. Switch to this branch, observe the call returning JSON

fix: path to config file

---

includes/class-newspack-popups-inserter.php
tests/test-content-intertion.php

#647 introduced a new bug in which some blocks are being stripped out of the page while being parsed by its filters. This is due the filtering out of blocks without `innerHTML`.
Not all blocks require `innerHTML` to display content. Blocks such as the Donation block and the Homepage Posts block uses other attributes to render their content.
This PR implements a stricter check to only filter out empty innerHTML of the following blocks:
- `null`
- core/paragraph
- core/heading
- core/list
- core/quote
- core/html
- core/freeform
It also implements a new assertion for more readable and less sensitive testing of block content insertion.
1. On the master branch, make sure you have inline campaigns visible
2. Create a page with donation and homepage posts block
3. Visit the page and see the …

fix: stricter empty block check

---

api/campaigns/index.php
api/segmentation/index.php
api/setup.php

Adds error response codes to failing API responses. 
It's hard to procure this errors with regular use of this plugin – easiest way to test would be to comment out fragments of code to verify the response codes are correct.

feat(api): add HTTP reponse codes to error reponses

---

includes/class-newspack-popups-inserter.php
src/view/patterns.scss

Closes #708.
1. Create a new prompt and set `In archive pages` as its placement, and select `Subscribe Pattern 1` as a pattern for the content `Patterns > Newspack Subscribe > Subscribe Pattern 1`.
2. Load an archive page (e.g. A user or category page).
3. Notice that there is no space between the prompt and the article before it. Notice also the subscribe pattern is not centered inside the block.
4. Load this ☺️ 
5. Reload the archive page, notice the prompt is placed evenly between articles, and its content is now centered.

fix: archive prompt spacing

---

includes/class-newspack-popups-inserter.php
tests/test-content-insertion.php
tests/test-content-intertion.php

#647 introduced grouping of blocks in order to avoid placing prompts after headings and floated image blocks. However, this introduced an edge case where if blocks can be duplicated if multiple headings and/or floated images appear consecutively.
1. On `master`, publish a post with test content that includes several individual paragraphs (which can be followed by prompts) as well as a series of consecutive headings and/or floated images (left or right). Or use the following test content:
<details>
<summary>Click for test content</summary>
```html
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce turpis leo, euismod egestas mauris non, aliquam ultrices dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec fermentum vulputate turpis, non auctor lectus. …
```

fix: duplicated, grouped blocks

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
tests/test-insertion.php

Instead of supporting just `[ 'post', 'page' ]` as the default post types for Campaigns, uses `get_post_types` to support posts, pages, and all public CPTs that have archives by default. Also applies a filter to the array of supported post types to allow other plugins to add or remove Campaigns support for specific post types.
Fixes some unexpected behavior that @kariae and I debugged together when trying to display an archive prompt on a category archive page that contained both posts and listings.
As a bonus, also fixes #720, as before we implemented post type support, we had hard-coded an exception to prevent inline prompts from being rendered on pages.
1. On your test site, make sure you have Newspack Listings and Newsletter plugins active, and some listings/newsletter posts published …

feat: add a filter for supported post types

---

includes/class-newspack-popups-inserter.php

Does two things:
1. Fixes a conflict between this plugin's non-AMP `view.js` and the core `mediaelement-core` JS, when the latter is also enqueued on the page. Note that the podcast player block still doesn't seem to work when AMP is enabled, but this doesn't seem to be related to this plugin.
2. Avoids enqueuing front-end JS and CSS if the "Disable prompts on this post or page" option is enabled, since it won't be needed in that case.
Closes #729.
1. Add a Jetpack Podcast Player to a post and configure it with a valid URL (try: https://feeds.megaphone.fm/no-place-like-home)
2. Disable AMP on the post.
3. View the post in an incognito window. On `master`, observe that the podcast player block is missing the media player component.
4. Check out this branch and refresh. Confirm that the …

fix: view.js conflict with mediaelement.js

---

includes/class-newspack-popups-model.php

This is a one-line fix that warrants quite a bit of explanation and testing.
There seems to be a race condition that happens when submitting a Donate block form on AMP pages. When submitting a Donate block form using the Newspack/WooCommerce Reader Revenue platform, the [handler](https://github.com/Automattic/newspack-plugin/blob/master/includes/class-donations.php#L536) performs some functionality and then does a [server redirect](https://github.com/Automattic/newspack-plugin/blob/master/includes/class-donations.php#L647) to the WooCommerce checkout page.
At the same time, when a form element is present in a prompt's content, a "Form Submission" event is reported when the form is submitted. On AMP pages, this event happens on the `amp-form-submit-success` trigger, which according to [AMP …

hotfix: donate form submission event

---

api/classes/class-lightweight-api.php
includes/class-newspack-popups-model.php

Accommodations for E2E tetsing:
- HTTP_HOST will contain the port (e.g. if connecting from localhost:8000, as in E2E tests),
and SERVER_NAME will not.
- forcing HTTPS is removed – amp-access will work with HTTP (see https://github.com/Automattic/newspack-popups/pull/579)
View a front-end of a page with some prompts – ensure the prompts are visible, as before (to test the API change).

feat(api): remove forcing HTTP; tweak referer verification

---

api/classes/class-lightweight-api.php

The `get_all_clients_data` method used by the API request to estimate a segment's reach based on reader activity currently gets literally all clients' reader activity data. On very high-traffic sites, this can be millions of rows' worth of data, which can cause the API request to timeout and/or fail.
This PR limits the number of rows returned to the 1000 most recent rows. It sorts on the indexed `id` column instead of the unindexed `created_at` column for hopefully better performance. 1000 rows should be enough reader data to calculate a reasonably accurate estimate of a segment's reach and should avoid the timeouts from fetching too much data at once.
Closes #627.
1. On a test site with a lot of reader activity data (ping me for credentials to such a test site), visit **Newspack > …

perf(segmentation): limit query results when fetching segmentation reach data

---

.distignore

.cache directory, created by `npm`, does not have to be distributed.

chore: prevent distribution of unneeded files

---

includes/class-newspack-popups-model.php

If overlay opacity is set to 0, it will currently default to 30%. This change allows the option to be set to 0.
Closes #632.
1. Publish an overlay prompt and set the overlay opacity option to `0`.
2. Preview or view in an incognito session and confirm that the overlay is shown with a transparent background.
3. Test other values to ensure that the setting is honored at any number.

fix: allow overlay_opacity to be set to 0 for prompts

---

includes/class-newspack-popups.php
src/editor/Preview.js

When previewing segments, we pass `view_as` query params on the preview iframe URL to any links within
the preview iframe content. We should do the same for preview iframes when previewing single
prompts. Currently, when previewing single prompts, the preview params aren't persisted as you navigate the site within the preview iframe, so things like Custom Placement or Single Prompt blocks won't render properly.
This updates the single-prompt preview component so that it passes preview query params to any links within the preview window, just like with the segment previews.
**Note:** This change won't prevent a Custom Placement or manual-only prompt from appearing as an inline prompt on the first post that appears in the preview window. This is because:
1. We don't want to force the user …

fix(preview): pass url params to links within single-prompt preview iframes

---

src/editor/Sidebar.js

Fixes an incorrectly-named prop in the `SelectControl` for prompt triggers.
Closes #748.
1. Confirm that #748 is not replicable.

fix: ensure correct option is selected for trigger dropdown

---

includes/class-newspack-popups-inserter.php
tests/test-content-insertion.php

Fixes an edge case that happens if an inline prompt with 0% scroll position is placed in a post consisting of only a single Group block. Also improves the insertion behavior surrounding blocks that contain inner blocks (not just Group blocks) so that the inner blocks' content is counted toward the block's total length. In practical terms this means that "container" blocks like Group and Column blocks will now have a more accurate content length when it comes to inserting inline prompts around them. These "container" blocks are still treated as single blocks, so prompts won't be inserted in between their inner blocks, which gives editors a way to ensure that prompts won't be inserted between certain content.
On top of this, also adds a failsafe condition where if the position for an inline …

fix: count inner blocks' content toward post length

---

includes/class-newspack-popups.php

When a category is deleted, prevents any prompts that had only that category from being assigned the default category.
Also slightly changes behavior in an [existing callback](https://github.com/Automattic/newspack-popups/blob/master/includes/class-newspack-popups.php#L951-L959) that happens on prompt publication to remove the default category only if it's the only category assigned to that prompt. This means it's possible to intentionally assign the default category to a prompt if it's assigned along with at least one other category, which could be a valid use case scenario (although maybe unlikely).
An alternative solution might be to always remove the default category from prompts, which would basically prevent it from ever being assigned to prompts, but that seemed heavy-handed to me. …

fix: prevent default category on term deletion

---

includes/class-newspack-popups-segmentation.php

Currently, when segmenting readers as donors, we check if the reader is logged in and if they have any WooCommerce orders purchased under their user. However, we don't check whether those orders have anything to do with Newspack donations, so if a site is using WooCommerce to offer any other types of products, all customers are marked as donors whether or not they've actually donated.
This PR does an extra step of ensuring that the reader has purchased Newspack donation products before considering them donors. This won't fix things for readers who have already been marked donors, but it will fix things for new readers going forward.
1. On your test site, make sure your Reader Revenue platform is set to Newspack and that you have the required WooCommerce plugins installed and active.
2. Go …

fix: only count donation products for donor segmentation

---

api/campaigns/class-campaign-data-utils.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
tests/test-api.php
tests/test-insertion.php

**Note:** #824 must be merged before reviewing/merging this branch.
Along with https://github.com/Automattic/newspack-plugin/pull/1563, adds a new segmentation feature for readers who have a user account. Allows you to target readers by whether or not they've logged in.
Note that a reader that has logged in and subsequently logged out is still considered a reader with a user account for the duration of their session—once a reader is known to own a user account, they will continue to match the "has user account" segment regardless of their current login state.
Closes #746.
1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/1563.
2. Visit **Newspack > Campaigns > Segments**. Add a new segment and give it a name.
3. Confirm there's a new dropdown field under …

feat: allow segmentation by user login status

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
tests/test-insertion.php

Changes prompt insertion logic so that logged-in admin and editor users see prompts just like regular readers. Like regular readers, admins and editors will only see prompts assigned to segments they match (so if an editor hasn't made any donations, they won't see donor-only prompts, for example).
Also prevents GA tracking code from firing for admins and editors, to hopefully prevent pollution of campaigns analytics data.
Closes #687.
1. Publish several prompts to several segments.
2. On `master`, as an admin user, browse the site's front-end. Observe that no prompts are displayed.
3. Check out this branch and browse again. Now confirm that prompts are displayed, as long as your reader activity matches their segments (so you may not see prompts shown to donors only, or to new readers).
1. …

feat: show prompts to logged-in admin and editor users

---

includes/class-newspack-popups-model.php

Makes two analytics-related changes:
1. !Changes the `event_category` label from `Newspack Announcement` to `Newspack Prompt` (@Automattic/newspack this is a potentially breaking change for sites running reports on `Newspack Announcement`—what are our collective thoughts on this?)~ Reverted this—see discussion below.
2. Adds a semicolon-delimited list of the prompt's segment(s) to each ~`event_category`~ event label, or "Everyone" if the prompt has no assigned segments
Closes #679.
1. Check out this branch and publish several prompts assigned to one, more than one, and zero segments.
3. In a new incognito window, view the page source and confirm that the analytics config now indicates the segments (or "Everyone").

feat(analytics): add segment name to event_category

---

api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups.php
src/editor/DismissSidebar.js
src/editor/EditorAdditions.js
src/editor/Sidebar.js
src/editor/utils.js
tests/test-api.php
tests/test-model.php

Current UI allows editors to make "virtually" undismissible prompts by simply not entering any text in the Dismiss Button Text field. In this case, the prompt can't be dismissed with a button click, but it will still be suppressed based on other factors such as newsletter subscription, donation, etc. This is not ideal for publishers who include prompts as more or less static design elements in specific areas, such as on the homepage.
This PR adds a new option to explicitly make inline, Custom Placement, and Manual-Only prompts "undismissible" prompts. There's a new toggle switch, which is ON by default, which allows these prompts to be dismissed. This represents the status quo/current behavior, so sites already using prompts won't experience any change in behavior for existing prompts. …

feat: add "undismissible" option for inline prompts

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
src/editor/Sidebar.js

Fixes an edge case where an inline prompt can get stuck with an invalid "insertion position" or `trigger_type` value, which causes the `RangeControl` used to set the insertion position to not appear at all in the editor, and the prompt to always appear at the very end of the content.
Prior to #755 `scroll` was really the only valid `trigger_type` value for inline prompts, so all inline prompts behaved the same way regardless of what that value was. After #842, a second `blocks_count` option was added, but it's still possible for a prompt to be saved as an overlay, then converted to an inline prompt, and have `trigger_type` be set to `time` as a result. This is the edge case fixed by this PR. The fix is to make any value other than `blocks_count` behave like `scroll`, effectively making …

fix: make "scroll" the default inline trigger_type

---

includes/class-newspack-popups-model.php

The plugin currently fully tracks only Jetpack Mailchimp block forms as newsletter subscribe form submissions. This PR adds handling for MC4WP forms, Gravity Forms, and arbitrary forms, the latter two via a `.newspack-subscribe-form` class name. The class name and the name of the field containing the user's email address are now filterable via the following filters:
* `newspack_campaigns_form_class` - The class name of the subscribe form.
* `newspack_campaigns_form_selector` - The CSS selector used to target the form for tracking submit events. If the form being tracked is a Jetpack Mailchimp or MC4WP form, it will be the selector for those form types (which generate consistent markup). Otherwise it will use the result of `newspack_campaigns_form_class` to build a selector.
* …

feat: support other newsletter signup forms

---

includes/class-newspack-popups-inserter.php
tests/test-content-insertion.php

Fixes the insertion algorithm of inline blocks around Group blocks. Previously the length of the Group's inner blocks wasn't factored into the total article length calculation, so inline prompts wouldn't get properly inserted into posts consisting mostly of multiple Groups.
1. Create a post consisting of several top-level Group blocks. Or copy the following test content:
<details>
<summary>Expand to copy</summary>
```html
<p>Nam tellus duis magna finibus penatibus eleifend maecenas aptent, senectus quam egestas dictum dapibus eu risus maximus, ligula lacus cras malesuada ipsum montes bibendum. Donec hendrerit aenean in pharetra suspendisse conubia ligula sollicitudin quis placerat varius sodales, natoque mattis mollis per ad dapibus taciti ut platea tempor. Aenean integer duis consectetur …
```

fix: insertion of prompts around Group blocks

---

CHANGELOG.md
includes/class-newspack-popups-inserter.php
newspack-popups.php
package-lock.json
package.json
tests/test-content-insertion.php

This reverts commit 6ae5ea90c664e359d80e116253a2a675fe200b69.
#855 improved the insertion behavior of inline prompts around Group blocks, taking into account the length of Groups' inner blocks. However, this has resulted in changed prompt placement on many homepages, most of which consist almost entirely of Group blocks. Many publishers have complained about the new placement, so this may be an instance in which the fix is not actually desired. Let's revert it for now.
1. Publish a post consisting of several top-level Group blocks containing a few other blocks like paragraphs, etc.
2. Publish an inline prompt at 50% placement.
3. On `master`, observe that the prompt appears halfway down the page.
4. On this branch, confirm that the prompt renders at the very end of the page, which is …

fix: revert group insertion fix

---

api/classes/class-lightweight-api.php
tests/test-api.php

The standard way of discouraging crawlers from indexing [seems to be](https://developers.google.com/search/docs/advanced/crawling/block-indexing) "noindexing" rather than returning a 400 error. This PR changes the behaviour towards bots crawling the API.
1. Add a line to `return true;` from `is_a_web_crawler` API method
2. On `master`, observe API requests from the front-end get `400` error response
3. Switch to this branch, observe the response is `200` with a `X-Robots-Tag: noindex` header

feat(api): improve web crawler handling

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
tests/test-model.php

#867 added a new option for overlay prompts to decide whether display the overlay background, meaning the site under the prompt is interactive. To avoid changing the behavior of pre-existing prompts, the background should be on by default, so that pre-existing prompts and new prompts should always display overlay backgrounds. However, a logical error in #867 meant that the reverse was true. This PR fixes the logical error and restores the overlay background for pre-existing and new prompts.
1. On `master`, create a new overlay prompt and open the "Colors" sidebar. Observe that the "Show overlay background" option is turned off. Preview the prompt and observe that the prompt is shown without a background.
2. Check out this branch and repeat step 1. Confirm that the option is now turned on …

fix: overlays should have a background by default

---

src/view/index.js
src/view/utils/index.js

Fixes two bugs affecting prompts in non-AMP environments.
* ab9ddd0 improves the JS selector for dismiss form elements to avoid attaching duplicate event listeners to the same form. This is happening because the `.newspack-popup` class exists on both the prompt's outer `amp-layout` container and its inner `div`. This doesn't really affect any behavior in `master` but it does affect #869 since that refactor logs each prompt dismissal as a discrete event rather than in an array keyed by prompt ID.
* 4e2388c fixes a bug where email input values aren't being properly captured for MC4WP and Gravity Forms newsletter forms in non-AMP mode only. Instead of the user-inputted email address, the input value is being logged as an AMP input value placeholder, e.g. `${formFields['email']}`.
1. Turn off …

fix: non-AMP signup forms

---

includes/class-newspack-popups.php

Disables prompts by default on special/protected pages, such as My Account, Privacy Policy, Donation, etc. other than the homepage and blog posts page.
Also makes the "Disable prompts on this post or page" option available to all post types that can possibly show prompts.
Requires https://github.com/Automattic/newspack-plugin/pull/1686.
1. Using WP CLI, ensure that the `newspack_popups_has_disabled_popups` meta value doesn't exist on a protected page by running `wp post meta delete newspack_popups_has_disabled_popups <post_id>`. See `\Newspack\Patches` class for a list of protected pages.
2. Edit the page and confirm that by default, the "Disable prompts on this post or page" is turned on. Also confirm that this behavior is true on the front-end and that no prompts are displayed.
3. …

feat: disable prompts by default for protected pages

---

includes/class-newspack-popups-segmentation.php

_Note: supersedes #895._
Fixes a misnamed variable in a filter affecting non-AMP Analytics config. In most cases this won't cause any errors because [the main Newspack plugin also does the same thing](https://github.com/Automattic/newspack-plugin/blob/master/includes/class-analytics.php#L527), but if any other plugins use this same filter the bug may cause subsequent filter callbacks to fail.
Nothing really to test—verify that the variable used in the filter matches the named function argument.

fix: misnamed variable in GA non-AMP config filter

---

api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
api/segmentation/class-segmentation-client-data.php
tests/test-api.php

#866 removed permanent suppression features as well as the logic that treated visitors coming to the site via any URL with a `utm_medium=email` param as a subscriber. However, removing both has resulted in some unwanted behavior for readers who visit sites via a newsletter link, but in a new or cache-cleared browser session. For these readers, prompt display logic is executed before their Mailchimp subscriber or donor status is evaluated, meaning they will be segmented as a subscriber/donor only after the first page load.
This PR evaluates the Mailchimp subscriber and donor status before executing segmentation logic, so that by the time the plugin decides which segment's prompts to display, a reader who arrives via a Mailchimp URL should already be known to be a subscriber/donor.
This PR …

fix: check subscriber status earlier and restore utm_medium=email logic

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/Sidebar.js
src/view/style.scss

Uses the existing "hide border" and "overlay size" options to improve the display of overlay prompts in small viewports. Currently there's no way to prevent an overlay prompt from taking up the entire viewport at smaller screen sizes if its content is long enough, so these changes provide some means of ensuring that the prompt size can be limited independently of content length.
The "hide border" option was originally only available for inline prompts, but it makes sense to allow it for overlays as well. This PR enables that option for overlays and applies appropriate CSS to hide the white border around the overlay content, replacing it with a transparent margin of the same size.
The "overlay size" option now restricts the max-height of overlays as a percentage of viewport height. If the …

feat: use existing options to restrict display size of overlay prompts

---

api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
api/campaigns/class-report-campaign-data.php
api/classes/class-lightweight-api.php
api/segmentation/class-segmentation-client-data.php
api/segmentation/class-segmentation-custom-ga-config.php
api/segmentation/class-segmentation-report.php
api/segmentation/class-segmentation.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-parse-logs.php
includes/class-newspack-popups-segmentation.php
tests/test-api.php
tests/test-segmentation.php

This PR implements a significant refactor of segmentation data storage and retrieval for improved performance. It does the following:
* Creates two new tables with a column and index structure optimized for performance:
- The "readers" table replaces the legacy "transients" table and normalizes data that was previously serialized in a single column into separate, indexable columns
- The "reader events" table replaces the legacy "events" table and stores info on not just `post_read` events, but also non-article page views, prompt views, donations, and newsletter subscriptions. In the future, when we're able to support a JS-based alternative to `amp-access`, this table may be offloaded from the server to `localStorage`.
- Because the above are stored as events, we no longer replicate the …

refactor: segmentation data

---

includes/class-newspack-popups-segmentation.php

Moves the "Remove all preview sessions data." block down, so `$old_client_ids_to_delete` is available to it. Otherwise, `PHP Notice:  Undefined variable: old_client_ids_to_delete` is logged.

fix(segmentation): data pruning

---

api/campaigns/class-campaign-data-utils.php
api/classes/class-lightweight-api.php
api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-donations.php
includes/class-newspack-popups-newsletters.php
includes/class-newspack-popups-segmentation.php

I recently started running into issues getting single, non-authenticated WooCommerce donation orders logged as donation events. In the process, I decided to simplify the plugin's handling of WC donation orders in general.
There are two ways the plugin looks for orders:
1. If the reader completes a recurring donation, they are automatically authenticated as a WooCommerce customer. For all logged-in WP users, the plugin fetches all orders associated with the logged-in user and upserts the orders as donation events. This seems wasteful and redundant as this happens on every logged-in session page load.
2. If the reader completes a single donation while not logged in, the plugin looks for a webhook callback on `order.created` and creates a donation event with the order details. This started …

fix: simplify WC donation handling

---

api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-segmentation.php

Closes #903.
1. Create a prompt segmented to users who have an account
2. Enable Reader Activation (`NEWSPACK_EXPERIMENTAL_READER_ACTIVATION` env. variable)
3. In a new session, observe the prompt is not displayed
4. Pre-authenticate by entering existing user's email in Registration block
5. Navigate to another page, observe the prompt displayed

feat(segmentation): handle pre-authenticated users

---

includes/class-newspack-popups-newsletters.php

With the change in https://github.com/Automattic/newspack-newsletters/pull/900, the newsletter contact can be updated w/out a change to lists selection. This PR brings the relevant hook handler up to date, making sure the reader event is not added in this case. 
Ensure the reader is still segmented as subscriber after subscribing

feat: handle no lists update

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/view/style.scss

Adds featured image support for overlay prompts. Support for inline prompts coming up (https://github.com/Automattic/newspack-popups/pull/925).
Closes #914 
1. Create a new prompt, observe a featured image can be added
2. View the frontend, observe the featured image is displayed if the prompt is an overlay one
3. Observe the featured image is centred in a 208px high element above prompt content

feat: featured images for overlay prompts

---

includes/class-newspack-popups-newsletters.php

Adds donation-related metadata fetching from the ESP, on login.
Closes https://github.com/Automattic/newspack-issues/issues/236
1. Switch Newsletters plugin to `feat/contact-data-details` branch (https://github.com/Automattic/newspack-newsletters/pull/901)
2. Manually add a contact in ActiveCampaign ESP, and fill in `NP_Last Payment Amount` or `Total Spent` fields
3. Register on the site as this user and observe prompts segmented to donors are displayed

feat: read ESP donation metadata on login and supply to segmentation

---

api/campaigns/class-maybe-show-campaign.php

Fixes `utm_source` suppression logic. Currently, if the URL contains a `utm_source` value that matches the prompt's UTM Suppression setting, if the prompt also matches the reader's segment, the segmentation matching will override the UTM suppression. This fix skips evaluating the prompt's segments and frequency options if UTM suppression is triggered first.
1. Publish a prompt to a segment that will match a new reader (e.g. non-donors). Set the UTM Suppression value to something like "Suppress This".
2. On `master`, in a new incognito session, visit the site with a matching `utm_source=Suppress%20This` param. Observe that the prompt is still displayed even though the debug response says it should have been suppressed based on the `utm_source` value.
3. Check out this branch, repeat step 2 …

fix: utm_source suppression if segment also matches

---

api/campaigns/class-maybe-show-campaign.php
api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-segmentation.php
tests/test-api.php

Fixes what seems to be a long-standing bug when evaluating whether a reader matches a prompt's segments, but none of the prompt's segments is the reader's highest-priority segment. In this case, the prompt's segmentation matching is evaluated as if it has no segments (same as "Everyone").
Closes #928.
1. On `master`, create an "Anonymous" segment targeted to readers with no account, and make it the highest-priority segment. Publish a prompt to the segment (only that segment) with "Every page" frequency. Then, create a second, lower-priority segment that will also easily match readers, such as "not subscribed" or "non-donors".
2. In a new incognito session, observe that you see the "Anonymous" prompt on every pageview before and after logging into a user account (**note:** must log in via …

fix: segment matching when no segment is the best-priority

---

includes/class-newspack-popups-inserter.php
src/editor/AdvancedSidebar.js

Fixes the category/term exclusion fields in the single prompt editor so that multiple terms can be selected for a prompt.
Closes #932.
1. On `master`, create a prompt with a category and tag in the exclusion fields ("Advanced Settings" sidebar).
2. Check out this branch. Confirm that the previously selected category/tag are still shown for the prompt, and that #932 can't be replicated.

fix: category/tag exclusion fields in block editor

---

src/editor/FrequencySidebar.js

Fixes a minor bug in the Frequency sidebar.
1. On `master`, with Reader Activation off (option in Engagement turned off, or no `NEWSPACK_EXPERIMENTAL_READER_ACTIVATION` flag) create a new overlay prompt.
2. In the Prompt Settings sidebar, change the Prompt Type to "inline".
3. In the Frequency Settings sidebar, observe that the "Every pageview" option remains disabled even after changing the prompt type to "inline", until you save draft + refresh.
4. Check out this branch, repeat steps 1–3, confirm that the "Every pageview" option becomes available whenever "Prompt Type" is set to "inline", without having to refresh the browser.

fix: update frequency options disabled status when prompt type is changed

---

src/editor/AdvancedSidebar.js

The "Advanced Settings" panel of the campaign editor lets users select categories and tags to exclude. However, this panel doesn't indicate that these are _exclusion_ settings, leading some users to mistakenly input their inclusion preferences into these fields, producing just the opposite results as intended.
Renames the labels for the category and tag exclusion fields, distinguishing them from the inclusion settings farther down the screen.
1. Observe the current behavior when editing a prompt:
2. Install this branch (complete with compiled JS files).
3. Open the prompt editor. The labels "Post categories" and "Post tags" should now read "Excluded categories" and "Excluded tags".

Clarify exclusion labels

---

src/view/style.scss

Instead of having different max-height depending on the size of the overlay, this PR standardise it to `80vh` on small screens and `100vh - 32px` on larger screens.
This would avoid potential cases where some content gets cut when screen space is tight.
Pinging @dkoo since you originally implemented this max-height and I'd love your opinion. 
__After:__
__Before:__
_Note: Both screenshots are meant to have a featured image at the top. Not quite sure why they're not appearing!_
1. Add tons of content to an overlay (play with different sizes as well)
2. Check front-end
4. Check again

feat: simplify overlay max-height

---

src/view/style.scss

Ensures that prompts' featured images are always full-width.
1. On `master`, publish an overlay prompt with a featured image.
2. On the front-end, observe that the image doesn't quite reach the edges of the container: 
- If that didn't work, try a smaller image.
3. Check out this branch, confirm that the image always fills the whole width of the prompt, and is scaled appropriately (no horizontal or vertical distortion).

style: ensure prompt featured images are always full-width

---

includes/class-newspack-popups-newsletters.php

Fixes a segmentation bug. 
1. Switch Newspack Plugin to `fix/master-list-handling` branch (https://github.com/Automattic/newspack-plugin/pull/1946)
2. Configure a site w/ ActiveCampagin and set a "Master List" in the Engagement wizard
3. Register a new reader w/out subscribing to any newsletter 
4. Observe the reader will be identified as a subscriber for segmentation
5. Switch to this branch, repeat – observe the reader won't be identified as a subscriber

feat(analytics): prevent marking client as a subscriber if subscribing to master list

---

includes/class-newspack-popups-model.php

Captures form info to analytics events for forms submitted via prompts. This lets us distinguish between subscribe vs register forms, and tells us whether the reader subscribed to any newsletter lists (and which ones).
1. Check out this branch, as well as https://github.com/Automattic/newspack-plugin/pull/1953 and https://github.com/Automattic/newspack-newsletters/pull/943
2. Ensure that your site is connected to Google Analytics, and monitor the Realtime events dashboard for incoming events.
3. Publish a prompt containing a registration form.
4. On the front-end, register a new email address and optionally subscribe to one or more newsletter lists.
5. In Google Analytics, look for new events with the event category `Newspack Announcement` and event action `Form Submission`. Confirm that …

feat: log reg form info to analytics events

---

src/view/style.scss

#952 fixed styles for prompt featured images to ensure they're always full-bleed, but the solution apparently didn't entirely fix the issue when AMP is active. This PR ensures that AMP images are also always full-width.
1. With AMP on, on `master` try to replicate the issue described in #952. You may need to try different combinations of featured images and prompt sizes to replicate.
2. Check out this branch and confirm that the issue is fixed with and without AMP on.

style: fix featured image wrapper style in AMP

---

includes/class-newspack-popups-inserter.php
src/view/index.js

Removes enqueueing of `wp-dom-ready` and `mediaelement-core` dependencies: the first is replaced by an inline function, second simply removed. 
The `mediaelement-core` dependency was added in #771, but it's not clear how the fix there works. The podcast player block is broken for me with or without the `mediaelement-core` enqueued, so the fix seems not to work anymore. I've found that the podcast player block is also broken 
- whenever Newspack Newsletters' Subscribe block assets are loaded
- on one test site, when Newspack Plugin is active at all
Which makes me think that the code of the podcast player block is too brittle to function property with Newspack. 
View a page without AMP and confirm the prompts load as expected

feat: remove wp-dom-ready, medialement dependencies for frontend script

---

api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/FrequencySidebar.js
src/editor/style.scss

Reopening #963 which was closed due to a conflict with an ongoing `release` build.
Moves the improved frequency options out from behind the `NEWSPACK_EXPERIMENTAL_READER_ACTIVATION` flag, replaces the preset with the one we actually went with for RAS sites, and makes the UI for custom frequency options a little bit more human-readable.
1. Check out this branch and https://github.com/Automattic/newspack-plugin/pull/2000.
2. Turn off the `NEWSPACK_EXPERIMENTAL_READER_ACTIVATION` flag in wp-config.
3. Create a new overlay prompt. In the Frequency Settings sidebar, confirm that you can select "every pageview" and "custom" options.
4. For "custom" options, confirm that there's a new toggle to enable or disable max displays. Disabling it forces the `frequency_max` meta value to `0`, or no …

feat: improved frequency options no longer experimental; clearer UI (v2)

---

.circleci/config.yml
composer.json
composer.lock
tests/test-api.php
tests/test-blocks.php
tests/test-content-insertion.php
tests/test-insertion.php
tests/test-model.php
tests/test-segmentation-criteria.php
tests/test-segmentation.php
tests/wp-unittestcase-pagewithpopups.php

This upgrades the tests so they can run both on php 7.4 and 8.
To test it, load the repo in a php 8 environment and run composer install. the run ./vendor/bin/phpunit
Do the same thing on a php 7.4 environment, but run composer update instead of install. (Discard the changes to composer.lock afterwards)

test: Upgrade to php 8

---

includes/class-newspack-popups-model.php
src/view/analytics.js

Lowers the threshold for a prompt being "visible" for purposes of logging `prompt_seen` events. Some people have really fast trigger fingers when it comes to closing modals!
* Before: At least 90% of a prompt element had to be visible within the viewport for at least half a second before it's considered seen.
* Proposed: At least 50% of a prompt element has to be visible within the viewport for at least a quarter of a second before it's considered seen.
Kind of hard to test, but may be easier with an inline prompt. Try to scroll it into view slowly, and note when the `POST` request to `newspack-popups/api/campaigns/index.php` happens—with this patch, it should happen more quickly than on `master`.

fix: lower visibility threshold for prompt_seen events

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php

Currently, logged-in admins and editor users are treated the same as readers for segmentation purposes. That is, their browsing activity and logged-in state determine which segments they match and which prompts they see when browsing the site front-end. However, admins and editors often exhibit very different browsing behavior compared to real readers, so the prompts they see while browsing can feel unexpected or incongruous.
This PR proposes that logged-in admins and editors should be treated as preview users. That is, when browsing the site, their client IDs are mocked with a `preview-` prefix, and their logged-in status is forced to not logged in for purposes of showing prompts and RAS login states. Their browsing activity (post views, term views, prompt interactions, donations, …

feat: treat logged-in admins and editors as preview sessions

---

includes/class-newspack-popups-model.php

#951 added form info (form and list IDs) to analytics events that occur from inside a prompt. However, the placeholders for this info were added to _all_ events that are triggered by the prompt, even events that don't have anything to do with the form. This results in unprocessed placeholders being sent to GA. This PR only adds the form info to form submission events.
1. On `master`, on a site connected to Google Analytics, publish a prompt containing a registration or subscribe block.
2. On the front-end view the prompt and submit it.
3. On the Analytics side, in the Realtime Events report, observe that the `Form Submission` event has an Event Label with properly processed placeholders (e.g. `Prompt position: Prompt Name (prompt ID) - Segment name | Form ID - list IDs`), but that the …

fix(analytics): only add form info to form submission events

---

api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-parse-logs.php
src/view/utils/index.js
tests/test-api.php

Fixes a bug where reader data is not properly fetched from the DB if any reader data was previously cached but then purged. At the moment if a persistent cache is enabled, the plugin assumes that any data that exists in the cache is all that needs to be retrieved, but data in the cache is not guaranteed to persist indefinitely despite having no expiration.
Also implements a "cache version" constant so we can bust the cache for all readers by bumping the version number.
~Also adds a fix that closes #981 by polyfilling AMP Analytics whenever AMP Plus is enabled, not just if AMP Analytics isn't available. This should fix any conflicts between AMP and non-AMP JS in the AMP Plus context.~
1. On `master` using a site with a persistent cache configured, visit the front-end in a new session. …

fix: handle purged cache

---

includes/class-newspack-popups-model.php
src/view/style.scss

Fixes a hard-to-reproduce issue which causes a timer-triggered overlay prompt to not be animated into view.
Overlay prompts are inserted in the DOM, but pushed down visually with CSS. The "appearance" animation transitions them up, resulting in a from-below-the-viewport effect. This relies on an [`IntersectionObserver`](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) which triggers the animation when the element is visible. 
For time-triggered prompts, the visibility should be immediate (and the animation delayed). There's a quirk in how the intersection is computed, though – if the prompt is pushed down by 100vh (100% of viewport height), the intersection still counts (the prompt only "touches" the viewport). Relying on that proved to be fragile on at least …

fix: prompt visibility animation

---

includes/class-newspack-popups-model.php
src/view/style.scss

Fixes a hard-to-reproduce issue which causes a timer-triggered overlay prompt to not be animated into view.
Overlay prompts are inserted in the DOM, but pushed down visually with CSS. The "appearance" animation transitions them up, resulting in a from-below-the-viewport effect. This relies on an [`IntersectionObserver`](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) which triggers the animation when the element is visible. 
For time-triggered prompts, the visibility should be immediate (and the animation delayed). There's a quirk in how the intersection is computed, though – if the prompt is pushed down by 100vh (100% of viewport height), the intersection still counts (the prompt only "touches" the viewport). Relying on that proved to be fragile on at least …

hotfix: prompt visibility animation

---

api/setup.php

A recent change to WordPress core added a call to `str_contains` in the `wpdb` class.
See https://github.com/WordPress/wordpress-develop/commit/fed98bd9ef9a232d102c41e74944d3c21cd6183e
This function is only available in PHP 8, and WordPress has a polyfill for it in `wp-includes/compat.php`.
Since our endpoint for segmentation loads `wpdb`, it now will fail when `wpdb` tries to call `str_contains`.
In order to fix it, we are now also including the core's polyfills.
Invoke WP core polyfills for WP 6.1 compatibility
1. Upgrade your WP to the latest WP 6.1 RC release. You can use the Beta tester plugin for that
2. Set up some segmentations and prompts
3. Visit your site and inspect the response to the ajax call to `api/campaigns/index.php` or `api/segmentation/index.php`.
4. Confirm you see …

Invoke WP core polyfills for WP 6.1 compatibility

---

src/editor/StylesSidebar.js

As discussed, clarifies the names of the available prompt styles. For overlay prompts, these should be "hide padding" and "large padding" instead of "border".
Edit a prompt and look at the style names when switching between inline and overlay prompt settings.

fix: clarify padding vs. border styles in overlay vs. inline

---

includes/class-newspack-popups-inserter.php
src/view/access.js
src/view/access.scss
src/view/index.js
src/view/utils/index.js
src/view/utils/index.test.js

Polyfills `amp-access` script. At this point what we called polyfills are not polyfills anymore, but a standalone JS solution for displaying prompts.
Some of the changes in this PR were originally introduced in #959, but then reverted in #995. The missing piece was setting the `newspack-cid` cookie, which resulting in some prompts being displayed on all pageviews. This was not caught in review because [Newspack Plugin's Reader Activation JS also sets this cookie](https://github.com/Automattic/newspack-plugin/blob/d6e072ccd18b2cff2e3dda97e371eedb1187afab/assets/reader-activation/index.js#L317-L321). With Reader Activation and AMP disabled, no JS code was setting this cookie. In this PR, there's the cookie-setting code on top of the original changes. 
Closes #193
Closes #880
Closes #749 …

Polyfill amp-access script

---

CHANGELOG.md
includes/class-newspack-popups-newsletters.php
newspack-popups.php
package-lock.json
package.json

The `add_contact()` - or other ESP-related methods - might fail or error due to ESP misconfiguration. The fetch under `wp_login` shouldn't be susceptible to such errors.
1. While on the `release` branch, make sure you have Newspack Newsletters installed
3. Set your ESP to Constant Contact and save without setting any credentials
4. Log in as a reader/subscriber
5. Confirm the fatal error
6. Check out this branch, log out and log in again
7. Confirm you authenticate without errors

fix: handle ESP exception on login fetch

---

api/classes/class-lightweight-api.php

#1010 fixed the issue of storing too many reconciled client IDs in the DB, but this fix is also needed to avoid querying too many in the first place.

fix: also limit query to fetch reconciled session client IDs

---

includes/class-newspack-popups-inserter.php
src/blocks/custom-placement/block.json
src/blocks/custom-placement/view.php
src/blocks/single-prompt/block.json
src/blocks/single-prompt/view.php
tests/test-blocks.php

Adds support for the "Additional CSS Class(es)" field on Single Prompt and Custom Placement blocks.
Closes /0/1200550061930446/1203415265039373.
1. Add a Single Prompt and Custom Placement block to a post. Ensure that the latter has at least one prompt assigned to the selected placement.
2. Add class names to the Additional CSS Class(es) field:
3. View on the front-end and inspect each element. Confirm in Dev Tools > Inspector that your class names are appended to the `aside` wrapper element for each prompt. Note that all prompts within the Custom Placement block will inherit the same class names.

feat: support custom class names on inline prompt blocks

---

composer.json
includes/schemas/class-campaigns.php
includes/schemas/class-prompts.php
includes/schemas/class-schema.php
includes/schemas/class-segments.php
tests/test-schemas.php

This PR creates a few JSON Schemas to describe the json format of the Prompts, Segments and Campaigns we will import and export.
This is a proposition based on what I could find, as the format of each entity is not formally described. The Schemas created here could also be used in the `schema` parameter of the REST api endpoints for documentation and validation if we want.
How I plan to use this:
* The importer/exporter will use these classes to validate the input json file
* Sanitize the input (with `rest_sanitize_value_from_schema`) and fill in default values when they are blank
* Santize the output json when exporting
Other notes:
* Note that the IDs (campaigns and segments IDs) that are used in the prompts will be replaced on importing. They will only have to be consistent within the …

Create Json schemas

---

includes/class-newspack-popups-importer.php
includes/class-newspack-popups.php
includes/cli/class-import.php
includes/schemas/class-campaigns.php
includes/schemas/class-package.php
includes/schemas/class-prompts.php
includes/schemas/class-schema.php
includes/schemas/class-segments.php
tests/bootstrap.php
tests/test-importer.php

Creates the Importer class and bootstrap the CLI command
Important: For now, we are not importing Categories and Tags. This will be handled in future PRs... The idea is to give the user the option to map tags and categories to existing terms or create them...
1. Tests are passing?
2. Use the exporter to export all your data: `wp newspack-popups export campaigns.json`
3. Delete all your prompts and segments
4. Try to import a file that is not a json and confirm you see the correspondent error `wp newspack-popups import index.php`
5. Import the file you have just exported: `wp newspack-popups import campaigns.json`
6. Confirm everything was created back again (note that you will lose categories and tags for now)
7. Edit the json file and make it not pass validation (remove the `frequency` …

Add the Importer class and basic CLI command

---

includes/class-newspack-popups-inserter.php

#1012 has added a prompt visibility toggle for site admins. This toggle is not useful in the admin panel, though, so it should not be displayed there. 
1. On `master`
2. Visit any admin page, observe the "Prompts Visible" toggle in the admin bar
3. Switch to this branch, reload, observe the toggle gone 
4. Visit the front-end when logged-in as an admin, observe the toggle is there

fix: hide the 'Prompts Visible' button in the admin panel

---

includes/class-newspack-popups-segmentation.php

Optimizes performance of, and also temporarily disables, a filter related to reporting custom dimensions which has proven to cause issues with edge caching.
No reader-facing changes, but custom dimensions related to Campaigns segmentation data will not be reported in the meantime. The following custom dimension roles are affected:
* `newspack_popups_cd_reader_frequency`
* `newspack_popups_cd_is_subscriber`
* `newspack_popups_cd_is_donor`

fix: temporarily remove cd filter

---

CHANGELOG.md
api/classes/class-lightweight-api.php
includes/class-newspack-popups-segmentation.php
newspack-popups.php
package-lock.json
package.json

#1014 introduced a strategy that requires the `Lightweight_API` to be instantiated on every page load. The web crawler check under the API constructor should consider the new argument to not exit the page on every crawler render.
4516503a981bb18bc8f4eb7099bd807fdb98955f restores the filter hook commented-out on #1034
1. While on `release`, change your user agent to `Googlebot`, visit the page and confirm it renders blank
2. Check out this branch, refresh, and confirm the page renders without issues

fix: prevent API bot exit without referer

---

includes/cli/class-import.php
presets/ras-defaults.json

Closes # .
1. Checkout this branch, make sure to run `composer install`
2. Run `wp newspack-popups import --ras-defaults`
3. Confirm that a Campaign named "Reader Activation Defaults" was created with a set of prompts and Segments
4. Check pemhSX-2m-p2 and verify everything was created as expected

feat: add ras defaults preset

---

src/editor/Sidebar.js

Removes some editor behavior which was a holdover from when we didn't allow "every pageview" frequency for overlays.
1. On `master`, create an inline prompt. Set the frequency to "every pageview".
2. Under Prompt Settings, change the prompt type to "overlay". Observe that the frequency reverts to "once a month".
3. Check out this branch, repeat steps 1–2, confirm that the frequency remains "every pageview".

fix: allow every pageview frequency for overlays in editor

---

includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
includes/cli/class-prune-data.php

This PR adds ability to run the data prune from the CLI. We occasionally have to go into a site and do some manual cleanup of the Campaigns tables if they get so large that they crash the cron job, and this would make that much simpler.
1. `composer install`
2. At the CLI, run `wp newspack-popups prune-data`. If there is data to prune you should see something like this:
```
Starting data pruning
Newspack Campaigns: Data pruning – removed X preview session rows from wp_newspack_campaigns_readers table.
Newspack Campaigns: Data pruning – removed X preview session rows from wp_newspack_campaigns_reader_events table.
Newspack Campaigns: Data pruning – removed X old rows from wp_newspack_campaigns_readers table.
Newspack Campaigns: Data pruning – removed X old rows from …
```

Add CLI command to run data pruning

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/utils.js

Fixes a bug that sometimes results in an invalid `full` size value, when the correct value should be `full-width`. Also accounts for the invalid size value so that it renders the same as `full-size`.
Closes 1203536997639429/1203494575662740.
1. On `master`, go to Newspack > Campaigns and use the wizard to create a new prompt. Select the "Top Overlay" placement.
2. In the editor for the prompt, in the Prompt Settings sidebar, observe that the "size" dropdown shows "extra small" (this is because the size value is forced to `full`, which is not a valid value, resulting in the first option being shown). Add a small amount of content which won't fill the full viewport width, like a few words.
3. View the prompt on the front-end and observe that it renders at the minimum width required for the …

fix: force invalid "full" size value to correct "full-width" value

---

composer.json

Updates the composer.json to add the "type" parameter with "wordpress-plugin" to allow for inclusion in Composer-based WordPress projects. This matches the [composer.json for the Newspack Plugin](https://github.com/Automattic/newspack-plugin/blob/master/composer.json)

Add type to composer.json

---

api/campaigns/class-maybe-show-campaign.php

Fixes the method signature so it won't throw notices on PHP 8+
1. Spin up a site with php 8 and Campaigns
2. Visit the site and inspect the ajax requests to `.../wp-content/plugins/newspack-popups/api/campaigns/index.php?cid=...`
3. Check the response and confirm you see the following warning:
```
<br />
<b>Deprecated</b>:  Required parameter $client_id follows optional parameter $all_segments in <b>/newspack-repos/newspack-popups/api/campaigns/class-maybe-show-campaign.php</b> on line <b>185</b><br />
```
4. Checkout this branch and confirm the warning is gone.

fix: avoid notice on php 8

---

api/classes/class-lightweight-api.php
includes/class-newspack-popups-inserter.php

Adds a feature to bypass reader and reader event data caching via a URL param or environment flag. Cached data can sometimes become unreliable as a reader amasses many client IDs, and this offers us a way to bypass the cache.
1. On a site with memcache setup, check out this branch and browse around the site as a reader.
2. Observe that after the first pageview, on subsequent pageviews your reader data and events are fetched from and written to the persistent object cache instead of directly to the DB.
3. Add a `?nocache` param to the URL and refresh. Confirm that reader data and events are fetched directly from the DB when this param is prseent.
4. Add `define( 'NEWSPACK_POPUPS_NOCACHE', true );` to your `newspack-popups-config.php` file and repeat step 3 without the param. Confirm that …

feat: add feature to disable reader data caching via flag

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups-settings.php

#948 changed overlay behavior so that tapping on the overlay background no longer dismissed overlay prompts. This largely resulted in increased prompt engagement from readers, but also some greater degree of reader frustration. We've received feedback from some publishers that this is highly undesired because of the frustration, so we're introducing a global option to restore the prior behavior for publishers who want it.
1. Check out this branch. Go to **Newspack > Campaigns > Settings** and confirm there's a new option (disabled by default) under General Settings:
2. Without enabling the new option, publish an overlay prompt with a visible overlay background. (Prompts without overlay backgrounds will not be affected as there's no overlay background to tap.)
3. View the overlay on the …

feat: allow overlays to be dismissed on background tap

---

api/setup.php

It may happen that a plugin will load code when this plugin's API is running. This plugin's API is not WordPress, so some functions assumed to be present in a WP environment have to be provided.
1. On `master`, activate the `performance-lab` plugin an visit a page with prompts 
2. Observe the request made to the API (`/wp-content/plugins/newspack-popups/api/campaigns/index.php`) – it will fail with a WP HTML error message as response 
3. Switch to this branch, observe the request succeeds as expected

fix: ensure the plugin works when performance-lab plugin is active

---

includes/schemas/class-prompts.php
presets/ras-defaults.json

Changes the default RAS newsletter signup prompt
See 1204068745367915-as-1204158608390449
1. Set up a new site
2. Activate Campaigns
3. Import defaults with `wp newspack-popups import --ras-defaults`
4. See all prompts
5. Open the Newsletters Inline signup (secondary)
6. Confirm the paragraph and the form are grouped and the group has a border
7. Confirm the separator at the bottom was removed
8. Confirm "Insert position" is set to "block count"
9. Confirm "Number of blocks" is set to 2

feat: Update default newsletter prompt

---

includes/class-newspack-popups-inserter.php

The paywalled post check is using the `wc_memberships_is_post_content_restricted()` function incorrectly. This will always be true if the post is restricted to any user and does not take the current user into account. 
This bug was found while working [the same fix for another feature](https://github.com/Automattic/newspack-plugin/pull/2366#issuecomment-1489119379).
This PR improves the check with the `wc_memberships_view_restricted_post_content` capability check.
1. Install and configure Woo Memberships while in the master branch
2. Setup an always visible inline prompt set to position 0
3. Login with an account that has a plan (can be the admin account)
4. Confirm the inline prompt does not render
5. Checkout this branch and confirm the prompt renders
6. Log out, visit the page and …

fix(memberships): restriction check for inline prompt insertion

---

tests/test-segments.php

This PR adds tests to the methods that get and save segments. This is a preparation for a refactor in the way we persist segments in the database
1. Watch the tests pass
2.Read the tests

tests: add tests to segments

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-importer.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
includes/schemas/class-prompts.php
presets/ras-defaults.json

Supports new RAS-related setup UI in https://github.com/Automattic/newspack-plugin/pull/2399. The main changes:
- Updates the prompt schema to support additional user input field data types (array and integer in addition to string)
- Implements logic to store user inputs by field name and populate preset config placeholders with matching stored inputs when fetching the preset configs
- Implements logic to build dynamic prompt previews from preset config + user input, without having to create prompt posts
Follow testing instructions in https://github.com/Automattic/newspack-plugin/pull/2399. The plugin should function as usual and all tests should continue passing even without the changes in https://github.com/Automattic/newspack-plugin/pull/2399.

feat: support RAS default prompts wizard UI

---

includes/class-newspack-popups-inserter.php

Adds a filter so plugins can add additional rules for prompt visibility
1. Check the code and read the docs to see if it's all clear
I preferred to not allow filters to completely override the checks, meaning that a plugin could make a prompt be displayed when the rules set by the user would not.
In practice, plugins will only be able to not display prompts that match all native conditions.

feat: add filter to maybe display prompt check

---

includes/class-newspack-popups-exporter.php
includes/class-newspack-popups-model.php

Adds custom taxonomies information to the prompt object.
Remove it from the exporter since we are not changing the prompt schema for now.
See https://github.com/Automattic/newspack-multibranded-site/pull/19

feat: add custom prompt taxonomies

---

presets/ras-defaults.json

The Registration block has an attribute to always sign up the reader to a newsletter upon registration, if there's only one newsletter. This attribute's default value is `false`, but we want the behavior in the RAS presets to be `true`, so this updates the preset config accordingly.
1. Start with a fresh site or delete all prompts + segments and the `newspack_reader_activation_enabled` option.
2. Run through the entire RAS setup wizard again and create default prompts and segments. Make sure at least one newsletter list is selected for the Registration Overlay prompt.
3. After completing setup, go to the Campaigns dashboard and edit the Registration Overlay prompt. Confirm that the "Hide newsletter selection and always subscribe" option is enabled. Note that it will be greyed out if …

fix(ras-defaults): turn on feature to always subscribe to newsletters by default

---

includes/class-newspack-popups.php

Tweaks the lightweight API config file creation to attempt on every host. The logic to skip if set as env var is preserved but all config variables will be checked, instead of just `DB_CHARSET`, `WP_CACHE_KEY_SALT`, and `DB_PREFIX`.
1. On a fresh instance, install the plugin and confirm the file is created
2. Remove the created file and set your database credentials as env vars, if not possible through runtime configuration, [`putenv()`](https://www.php.net/manual/en/function.putenv.php) is convenient
3. Refresh wp-admin and confirm the file is created but the env vars were skipped

fix: attempt to create config file on every host

---

includes/class-newspack-popups.php

Fixes an oversight in #1121, values should be escaped.
1. While in master, change your wp-config file to have a `'` character as part of the db password
2. Delete the `newspack-popups-config.php` so it's created again
3. Confirm the broken php
4. Check out this branch and delete the file
5. Confirm it's properly escaped and works

fix: escape value when creating config file

---

includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php

Exposes a previously private method so that https://github.com/Automattic/newspack-plugin/pull/2484 can update the donor landing page from Reader Revenue settings. Also adds a missing feature to segment readers who hit the donor landing page as donors.
See testing instructions in https://github.com/Automattic/newspack-plugin/pull/2484.

feat(ras): add segmentation support for NRH donations

---

src/view/analytics/dismissed.js
src/view/analytics/ga4.js

This PR adds tracking for a `dismissed` event.
See 1204238302518911-as-1204668686462485
1. Ensure that you have Google Analytics and a GA4 property set up in Site Kit (otherwise the JS won't init).
2. Check out this branch.
3. Visit a post or page that will display overlay prompts. 
4. Click the 'close' button on the overlap prompt. 
5. Check the realtime tracking in your GA account and confirm that `dismissed` was tracked as an action for the `np_prompt_interaction` event.

feat: first pass at dismiss event tracking

---

src/view/analytics/dismissed.js

This PR adds a check for the close button before trying to add events to it, just in case it's not actually there 😅 
Repeat the testing steps from https://github.com/Automattic/newspack-popups/pull/1131, and make sure everything still works as expected!

fix: add check for close button before adding action

---

src/view/analytics/clicked.js
src/view/analytics/dismissed.js
src/view/analytics/ga4.js
src/view/utils/index.js

This PR adds tracking for links inside of prompts.
1. Ensure that you have Google Analytics and a GA4 property set up in Site Kit (otherwise the JS won't init).
2. Check out this branch.
3. Set up a few different prompts with and without links; confirm that clicking those links is getting tracked correctly in GA.

feat: add tracking for click events

---

includes/class-newspack-popups-data-api.php
src/view/analytics/dismissed.js
src/view/analytics/ga4.js
src/view/analytics/submitted.js

Implements `form_submission` GA4 events when a form inside prompt content is submitted.
Also implements an `action_value` for all donation-related events, which lists the suggested donations for that form (if manually configured in the block, from the block's attributes, if not, from the sitewide donation settings).
1. On a site connected to a GA4 property via Site Kit, publish prompts containing registration, newsletter signup, and donation forms.
2. On the front-end, submit each form. Confirm in your GA dashboard > Reports > Realtime that a `form_submission` event with relevant event params gets fired upon form submission for each form.
1. Publish a prompt containing an link pointing to a URL anywhere in the content.
2. View the prompt on the front-end and click on the prompt.
3. In …

feat: GA4 `form_submission` events for prompts

---

includes/class-newspack-popups-inserter.php

There's a weakness in the [`the_content`](https://developer.wordpress.org/reference/hooks/the_content/) filter hook in that it doesn't tell you what post object the filtered content is coming from. For this reason, the callback to insert inline prompts in article content sometimes gets called on the wrong content, as was discovered in https://github.com/Automattic/newspack-theme/pull/2127.
This PR attempts to mitigate that situation by comparing the `post_content` property on the post in the global `$wp_query` and comparing it to the `$content` string being filtered, before executing the prompt insertion logic. Since this filter callback is being called with priority `1`, before most or all other content filters would be run to transform this content string, the strings should match. I …

fix: ensure inline posts are inserted into main post content only

---

includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
tests/test-segments.php

Fixes a bug in which inactive segments are included in the payload for the segmentation API request. This doesn't resolve, but helps avoid, an issue where including too many segments in the payload results in a "Request URI too long" error response.
This is fairly unlikely to happen in a production environment, so it's an edge case.
1. Generate a lot of segments, but make most of them inactive. The easiest way to do this is to repeatedly navigate to `domain/wp-admin/admin.php?page=newspack-engagement-wizard#/reader-activation/complete` and click the button to "Enable Reader Activation". Each time you do this it will generate a new set of default segments + prompts, and deactivate the old ones. Do this at least 4 times to replicate the bug.
2. View the front-end and observe that no prompts …

fix: don’t include inactive segments in API request payload

---

src/view/analytics/dismissed.js

The `dismissed` GA event for overlay prompts should describe when a reader closes the prompt without interacting with its content. If the reader submits a form within the prompt (whether or not that submission results in a successful registration or login) that indicates a conversion intent and closing the prompt after that should not result in a `dismissed` event.
1. Check out this branch and open your GA real time events report.
2. In an overlay prompt, register/sign up for a newsletter and submit the form.
3. Close the overlay.
4. Confirm that after submitting the form, you do NOT see a `dismissed` event for this prompt

fix: remove dismissed event after form is submitted

---

includes/class-newspack-popups-data-api.php

Places the donation_suggested_values into the interaction_data key of the data events for popups.
1. Set up a site with back-end ga4 tracking
2. Make sure newspack plugin is running this branch -> https://github.com/Automattic/newspack-plugin/pull/2506
3. Make a donation via a popup
4. Make sure the `donation_suggested_values` parameters are sent alongside all the other `donation_*` params that are sent when a donation is submitted

feat: rearrange info on popup events metadata

---

includes/class-newspack-popups-inserter.php

Further details and instructions at https://github.com/Automattic/newspack-plugin/pull/2516

fix: render prompts on metered content

---

src/criteria/utils.js

Addresses [this suggestion](https://github.com/Automattic/newspack-popups/pull/1155#discussion_r1262777158) from #1155 to have a more descriptive log when the reader data library is not loaded.

fix(criteria): warn when criteria value is not available

---

src/view/style.scss

This PR moves the close button to inside of the popup when you're using the Hide Padding option, to the same placement it has when the prompt has a featured image in the same situation. This helps make sure the close button is always easy to see, since it's contrast depends on the prompt's background, not the overlay's background.
See 1200550061930446-as-1204474693104072
1. Set up a prompt that's an overlay, and have it use the Hide Padding style.
2. Preview the prompt; note that the close button is outside of the prompt area, and, if you're using the default colours, is dark against a dark overlay (and possibly dark text!):
3. Apply the PR, and run `npm run build`.
4. Preview your prompt again and confirm that the close button is now inside of the prompt itself, and easier to see:
5. Try …

fix: move the close button when Hide Padding is enabled

---

includes/class-newspack-popups-criteria.php
src/criteria/index.js
src/criteria/utils.js

Allows the criteria matching configuration to run before the criteria are registered.

fix(criteria): allow async matching configuration

---

src/criteria/default/favorite-categories.js

Proposes logic for segmenting by favorite category. Picking up a thread from https://github.com/Automattic/newspack-popups/pull/1155#discussion_r1261746719. Note that I was slightly incorrect in my description of the logic in that thread; I missed the `key()` function in the current logic which means that the criteria categories are only compared against the top-most-viewed category.
The way the current (non-rearchitected) logic [works](https://github.com/Automattic/newspack-popups/blob/master/api/campaigns/class-campaign-data-utils.php#L263-L269) is that a category is considered "favorite" if it's been viewed more times than any other category. This could result in a slightly awkward situation where if the very first post visited matches the segment criteria, it would make for a match on …

feat: favorite categories segmentation logic

---

includes/class-newspack-popups.php

Implements a migration strategy from the `wp_newspack_reader_data_events` table to Newspack's reader data library.
The proposed approach migrates on demand, executing on an authenticated reader's page load. It works as follows:
1. Fetch all event IDs from the reader
2. Fetch all events from the collection of event IDs attached to that reader
3. In ascending order by creation date, iterate through each event to build an object with:
```
{
"is_newsletter_subscriber": Boolean, 
"is_donor": Boolean,
"is_former_donor": Boolean
}
```
The order matters so that the latest `donation` or `donation_cancelled` event establishes the former donor or donor state.
4. If no recent reader data item exists for each data key, create them
5. Delete all the rows that match the client IDs from the reader and …

feat: migrate reader data

---

includes/class-newspack-popups.php

#1176 introduced a means to migrate previously registered readers to the new rearchitecture data scheme. This also has a mechanism to add a `newspack_popups_reader_data_migrated` user meta key to readers that have already been migrated so that this migration will only run once per reader, but some changes along the way dropped the variable. 
1. On `master` for this plugin as well as the main plugin and Newspack Blocks, register a reader by signing up for a newsletter with RAS and/or donating.
2. Check out this branch as well as https://github.com/Automattic/newspack-plugin/pull/2558 and https://github.com/Automattic/newspack-blocks/pull/1498.
3. In a new session, sign into the reader account registered during step 1. Navigate to a new page or two to make sure the async migration functions …

fix: undefined user meta key

---

includes/class-newspack-popups.php

Removes the lightweight API checks and setup.
1. Check out this branch, navigate to the wizard and confirm you're able to create prompts and segments
2. Create a prompt and assign to a segment
3. In a fresh session, confirm the prompt renders when matching the segment

chore: remove lightweight api setup

---

newspack-popups.php

With AMP having been deprecated from the Newspack platform in H1 2023, it's no longer relevant to describe this plugin as "AMP-compatible overlay and inline Campaigns." This PR updates the "Description" and "Author URI" fields in the plugin header.
No code has changed; no testing is needed.

fix: update plugin description

---

.distignore
includes/class-newspack-popups.php

Fixes some bugs introduced in #1168 and #1169.
1. On `epic/rearchitecture`, run `npm run release:archive` to build a release package.
2. Install the package on a fresh site. Observe a fatal PHP error due to missing files in the `src/criteria` and `src/blocks` folders.
3. Check out this branch and confirm the fatals no longer occur.
1. On `epic/rearchitecture`, edit a prompt and expand the "Segments" panel.
2. Observe that the "Manage segments" link doesn't go anywhere.
3. Check out this branch and confirm it now links to the segments page of the Campaigns wizard.

fix: missing release files

---

includes/class-newspack-popups.php
includes/class-newspack-segments-migration.php
includes/class-newspack-segments-model.php

Fixes an issue with the migration of segments from the `wp_options` implementation (pre- #1192) to segments as a term with registered criteria.
To replicate the issue:
1. Create a new site using the latest releases of Newspack Plugin, Blocks, and Campaigns
2. Create a bunch of different segments with different criteria and prompts in each (and/or complete the RAS setup wizard to generate them), and make sure to disable one or two
3. Upgrade all three plugins at once to the current alphas:
- https://github.com/Automattic/newspack-plugin/releases/tag/v2.4.0-alpha.1
- https://github.com/Automattic/newspack-blocks/releases/tag/v1.74.0-alpha.1
- https://github.com/Automattic/newspack-popups/releases/tag/v2.23.0-alpha.1
7. Observe that the prompts lose their segment assignments as above.
8. …

fix: include missing file

---

includes/class-newspack-popups.php
src/editor/index.js

When creating a prompt from the "Add new prompt" button in a segment section, the segment will not be stored with the segment taxonomy sidebar panel closed, which is the default state on a fresh session.
This PR fixes it through the backend, by detecting the URL param and setting the term if there are no selected segments.
This PR also changes the strategy to avoid always updating the input on mount.
1. While on the master branch confirm the bug by visiting "Campaigns" in a fresh session (the sidebar panel closed) and clicking "Add New Prompt" from any existing segment
2. Publish, go back to "Campaigns" and confirm the prompt is set to "Everyone"
3. Check out this branch, repeat, and confirm the proper segment is set
4. Create a new prompt in a segment and select multiple segments
5. …

fix: ensure url param segment is set

---

includes/class-newspack-popups-model.php

#1192 didn't account for frequency presets, which should override individual frequency settings. Also fixes a long-lingering bug where the "weekly" preset couldn't be chosen in the Campaigns settings modal.
1. On `master`, create a new prompt, set it to a frequency of "Once a month", "Once a week", or "Once a day". Don't choose "Custom" at any point while editing.
2. View the prompt on the front-end and observe that it's shown on every page view, no matter which frequency preset you've chosen.
3. Check out this branch and repeat step 2. Confirm that it now shows only once.
4. Play with various presets and confirm that the prompt shows according to the selected preset in all cases. You can also inspect the prompt's HTML wrapper element `.newspack-popup-container` and confirm that the …

fix: account for frequency presets in printed config

---

includes/class-newspack-popups-model.php

Closes # .
1. On `master` Set up an overlay prompt on the bottom of the page
2. Notice there is a `.hide">` string on the middle of the page
3. Checkout this branch and confirm the glitch is gone
4. Confirm the prompt still works and you are still able to close it

fix: remove string from overlay prompt

---

includes/class-newspack-popups-data-api.php

Handles error coming from `\Newspack\Donations::get_donation_settings()`. Also, see https://github.com/Automattic/newspack-plugin/pull/2675
1. While on the master branch, force `\Newspack\Donations::get_donation_settings()` to throw an error by adding `return new \WP_Error( 'test_error',  'Test error' );` to line `291` of `includes/class-donations.php` in `newspack-plugin`
2. Visit a page that has a prompt with the Donate block and confirm the fatal error
3. Check out this branch and confirm the page doesn't throw a fatal error

fix(data-api): handle errored default donation settings

---

includes/class-newspack-popups-settings.php

Removes the reference to the deprecated non-interactive mode.
There should be no changes, this method is not used anywhere.

feat: remove is_non_interactive method

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/index.js

https://github.com/Automattic/newspack-blocks/pull/1543 proposes a new strategy for opting out of the deduplication logic in the Homepage Posts block. This requires a change in how it's implemented for campaigns.
This PR implements the necessary changes to the logic initially implemented in #630 so it continues to work as expected.
1. Checkout https://github.com/Automattic/newspack-blocks/pull/1543 and this branch
2. Create a page and a campaign prompt with matching Homepage Posts blocks (so they display the same content)
3. Make sure the prompt is displayed as an overlay and can be rendered on the created page
4. Visit the page and confirm the expected duplicated posts rendered on the page and the prompt

fix: deduplication strategy for Homepage Posts block

---

src/view/segmentation.js
src/view/utils/prompts.js

Implements RAS overlays as proposed in https://github.com/Automattic/newspack-plugin/pull/2708
1. Checkout this branch, https://github.com/Automattic/newspack-plugin/pull/2708, and add the following code to line 20 of `src/view/segmentation.js`:
```javascript
ras.on( 'overlay', ev => {
console.log( ev.detail );
} );
```
2. Create an overlay prompt to render for everyone and on every page view
3. Visit the front-end and open devtools
4. Wait until the prompt renders and confirm the array containing an overlay ID is logged
5. Close the prompt and confirm the overlays array is again logged and empty

feat: implement ras overlays

---

CHANGELOG.md
includes/class-newspack-popups-model.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups.php
newspack-popups.php
package-lock.json
package.json
src/editor/index.js
src/view/segmentation.js
src/view/utils/prompts.js

Release Oct 31

---

CHANGELOG.md
includes/class-newspack-popups-inserter.php
newspack-popups.php
package-lock.json
package.json
src/criteria/default/index.php

Release Nov 13

---

includes/class-newspack-popups-settings.php
tests/test-model.php

Fixes a logical error in the `Newspack_Popups_Settings::get_setting` method. If getting an invalid setting key or a setting key that doesn't have a saved option, it would always return `true` instead of the setting's default value. This PR validates the key and also returns the default value if a value hasn't been saved before.
1. On a fresh site, install Campaigns from `master`.
2. Run `wp shell`, then `Newspack_Popups_Settings::get_setting( 'newspack_popups_mc_donor_merge_field' )`. Observe that it returns `true`.
3. Check out this branch and repeat step 2 in a new `wp shell` session. Confirm it now returns `DONAT`.
4. Update the settings in Newspack > Campaigns > Settings and repeat with various keys ([see here](https://github.com/Automattic/newspack-popups/blob/master/includes/class-ne …

fix(settings): get_setting method

---

includes/class-newspack-popups-criteria.php
includes/class-newspack-popups-inserter.php

Prevents loading the criteria-handling JS if prompts are disabled on a page. 
1. Visit a page that will display a prompt and observe that the `criteria.js` file is loaded
2. Visit a page with prompts disabled, observe the file is not downloaded

feat: don't enqueue criteria if popups are disabled for post

---

includes/class-newspack-popups.php

Adds support for post revisions to the Newspack Popups CPT.
Closes #688 & #731 .
1. Make a change to a prompt. Observe that there is no "Revisions" box in the post settings.
2. Switch to this branch.
3. Make a change to a prompt. Observe that there is a "Revisions" box in the post settings.
4. Confirm that the previous version of the prompt is visible in (and can be restored from) the revisions timeline.

feat: adds support for post revisions to popup CPT

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php

When we loop through prompts before header, we use a standard WP Loop, and use `wp_reset_postdata` to reset the global `$post` object afterwards.
This works in most cases, but we just found a situation where this doesn't work and ends up messing up the global object.
When you are in an archive page that has no posts, `wp_reset_postdata()` will not reset post data, because there is no post. See this check -> https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/class-wp-query.php#L4898
I modified the loop to use a simple foreach and to not touch the global post variable.
1. On `master`, create a new user and make sure there are no posts assigned to them
2. Using Newspack theme, visit this user archive
3. Confirm the user name displayed in the page title is not the user …

fix: dont change global post before header

---

composer.json
composer.lock
includes/class-newspack-segments-model.php
includes/schemas/class-prompts.php
tests/test-schemas.php
tests/test-segments.php

Fixes the schema for prompts and segments.
Recently `criteria_hash` was added to segments, but we didn't update the schema, and thus we broke the importer/exporter tool. In prompts `duplicate_of` was in the wrong place.
1. on `master` in a site with many promtps and segments recently creted, try exporting it via CLI and confirm you see some error in segments: `wp newspack-popups export`
2. Checkout this branch and confirm export works
3. Also confirm import works

fix: prompts and segments schema

---

includes/class-newspack-popups-importer.php
includes/class-newspack-popups-model.php
tests/test-importer.php

Bumps the max number of prompts fetched by the API from 100 to 1000.
1. Test with a site that already has more than 100 prompts, or generate more than 100.
2. On `release`, visit Newspack > Campaigns and observe that only 100 prompts are shown.
3. Check out this branch, refresh, and confirm that up to 1000 prompts are now shown.

feat: fetch up to 1000 prompts

---

includes/class-newspack-popups.php
tests/wp-unittestcase-pagewithpopups.php

Registers the prompt CPT with a custom `capability_type`, in order to allow granular control over access to this CPT.
1. There should be no functional changes, verify that prompts are editable and visible on the front-end.

feat: use custom capability_type for the CPT

---

includes/class-newspack-popups.php
tests/wp-unittestcase-pagewithpopups.php

This reverts commit 1d01212c54b8307ff0150242ffa0d8b787f9e9ea.
Closes # .
1.
2.
3.

Revert "feat: use custom capability_type for the CPT (#1259)"
