Automattic/newspack-popups

includes/class-newspack-popups.php

It's useful  to make the admin aware which Pop-up will be shown on all Posts, in  case there are multiple Pop-ups, certain are unpublished, or Pop-ups have category assignments (to be introduced in a future PR). This PR  adds `itewide Default` to the title of this Pop-up  on the posts page.
1. Create one Pop-up, but do not publish it. Verify no post state is shown.
2. Publish the Pop-up. Verify `Sitewide Default` is shown after the title.
3. Create a second Pop-up and publish. Verify `Sitewide Default` is shown by the new post, not  the first one.

"Sitewide Default" Post State

---

src/view/style.scss

This avoids having the pointer cursor when moving the mouse around the overlay, which feels odd
1. load a post with the popup, move your mouse outside of the pop-up content, the cursor should become a pointer (because the overlay is a button)
2. switch to this branch and run `npm run build`
3. reload the post, move your mouse again, it should stay the same

Set the cursor of `.newspack-lightbox-shim` to auto

---

package.json

Adds a start script. 
1. `npm start`
2. Verify the plugin builds successfully and is in watch mode.

Add npm start script.

---

package-lock.json
package.json

Updates Calypso Build so the plugin can be built with current Node.
1. `nvm use  stable`,  then check `node --version`
2. `npm install`
3. `npm start`
4. Verify plugin builds successfully with no errors.

Node v12 Support

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

Integration points for the Newspack plugin Engagement Wizard. Test with https://github.com/Automattic/newspack-plugin/pull/365.
Complete testing instructions in https://github.com/Automattic/newspack-plugin/pull/365.

Integration With Newspack Plugin

---

newspack-popups.php

Bump Version to 1.0.0-alpha.01

---

newspack-popups.php

This updates the version to 1.0.0 since we're out of the beta period.

Bump version for release

---

.circleci/config.yml
.eslintrc.js
.stylelintrc
commitlint.config.js
composer.json
composer.lock
package-lock.json
package.json
src/editor/index.js
src/editor/utils.js
src/view/style.scss

- Configures semantic-release for automated releases
- Configures JS & CSS liniting
- Configures CircleCI to run the linting and releasing
1. `npm run lint` should exit without error
2. `npm run format:js` & `npm run format:scss` should not change any files

Add semantic-release & linting

---

.circleci/config.yml
.eslintrc.js
.stylelintrc
commitlint.config.js
composer.json
composer.lock
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
newspack-popups.php
package-lock.json
package.json
src/editor/index.js
src/editor/utils.js
src/view/style.scss

Release 3/24/2020

---

includes/class-newspack-popups-model.php

Handling of MC4WP plugin Mailchimp forms.
1. Install MC4WP plugin
2. Create a popup with "Mailchimp for WordPress form" block
3. Visit the site, sign up for the newsletter
4. Refresh site. Observe that the form does not reappear.

feat: handle MC4WP forms submissions

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/PopupPreview.js
src/editor/index.js
src/view/index.js
src/view/patterns.scss
src/view/style.scss

Release 3/31/2020

---

includes/class-newspack-popups-inserter.php

A new release, as #101 got left behind.

Release 4/22/2020

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups.php
src/document-settings/index.js
webpack.config.js

A new release. Let's get #108 out there!

Release 4/24/2020

---

src/document-settings/index.js

A new release of the popups plugin.

Release 4/29/2020

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php

Adds a few features required by the Newspack Plugin Pop-ups Wizard in https://github.com/Automattic/newspack-plugin/pull/515. 
Testing instructions in https://github.com/Automattic/newspack-plugin/pull/515

feat: convenience method for updating pop-up options

---

includes/class-newspack-popups-model.php

Description and testing instructions in https://github.com/Automattic/newspack-plugin/pull/525.

feat: support for draft popups

---

includes/class-newspack-popups-api.php

This PR fixes two issues I noticed in the popups utm suppression feature:
1. Appending `?utm_source=blah` (or any utm source) to the site's homepage URL (e.g. `http://newspack.test?utm_source=blah` will render some sort of messed-up archive page.
2. A fresh user arriving to a site with a suppressed utm source will still receive the popup on their first visit. It may just be on my local environment, but the transient wasn't available on the initial request.
There is one third issue that I wasn't able to solve, and I'm not sure if it has a good solution. A user visiting the site for the first time will not have an `amp-access` cookie, so after they navigate to a 2nd post (because fix 2 from above handles the first post) they get hit with a popup. In theory, though, that would not be common, …

Fix couple issues with popup utm suppression

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
newspack-popups.php
src/document-settings/index.js
src/editor/index.js

Release May 6, 2020

---

includes/class-newspack-popups-inserter.php

Release 5/12/2020

---

includes/class-newspack-popups-inserter.php

Release 5/15/2020

---

.github/workflows/main.yml
includes/class-newspack-popups-inserter.php
package-lock.json
package.json
src/editor/index.js
src/view/index.js

Release 09/06/2020

---

.distignore
composer.json
composer.lock
package.json

This gets rid of all unnecessary files from the release zip.
1. Create a release zip: `$ npm run build && npm run release:archive`
2. Inspect zip contents - it should only contain the license, PHP files, and `dist` folder with JS/CSS assets 
3. Upload the plugin to a new site, it should work as expected

Clean up release zip

---

includes/class-newspack-popups-inserter.php

Complete description and testing instructions in https://github.com/Automattic/newspack-blocks/pull/529.

refactor: homepage posts pre/post rendering hooks

---

.distignore
composer.json
composer.lock
includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
package.json

Release 18/06/2020

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
src/view/index.js

Release 23/06/2020

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

A new release.
* Fix for ad insertion in overlay campaigns
* Fix for `the_content` hooks firing too often

Release 30/06/2020

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

Release 07/07/2020

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

A new release – to get bounce rate fix out there.

Release 09/07/2020

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups.php
package-lock.json
package.json
src/settings/index.js
webpack.config.js

Adds plugin settings page and an option to suppress newsletter campaigns for visitors coming from email. Next step will be to set a transient so that the site will "remember" that newsletter campaigns should be hidden after user navigates.
Related: https://github.com/Automattic/newspack-newsletters/pull/265
1. Create two campaigns – one with a newsletter form (let's call it A) and one without (B)
2. Visit the site to confirm that both are showing up
3. Append `?utm_medium=email` to URL – observe that only campaign B is visible
4. Visit the Campaigns plugin settings page (link is in the sidebar), oberve the option is on by default 
5. Unset the option
4. Re-visit the site (with the `utm_medium`), observe that both campaigns are visible
4. Remove the param from URL, observe that both …

Add option to suppress newsletter campaigns if visiting from email

---

includes/class-newspack-popups-api.php

Closes #177.
1. Create a campaign, set "UTM Suppression" to a string with spaces in it
2. Visit the site to confirm that the campaign is visible 
3. Append the `utm_source` param, replacing spaces with `%20`, confirm the Campaign is hidden
3. Append the `utm_source` param, replacing spaces with `+`, confirm the Campaign is hidden

Decode URL when checking utm_source suppression

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups.php
package-lock.json
package.json
src/settings/index.js
src/settings/style.scss
webpack.config.js

Release 14/07/2020

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php

A new release, to get #180 out there.

Release 15/07/2020

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php

Release Jul 21

---

.circleci/config.yml
.distignore
includes/class-newspack-popups-api.php
includes/class-newspack-popups-model.php
package.json

Alpha release Aug 18

---

includes/class-newspack-popups-model.php

Release Aug 18

---

.circleci/config.yml
includes/class-newspack-popups-api.php
includes/class-newspack-popups-model.php

Alpha release Aug 25

---

.circleci/config.yml
includes/class-newspack-popups-api.php
includes/class-newspack-popups-model.php

Release Aug 25

---

api/README.md
api/classes/class-lightweight-api.php
api/classes/class-maybe-show-campaign.php
api/index.php
includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
package-lock.json

Alpha release Sep 15

---

api/README.md
api/classes/class-lightweight-api.php
api/classes/class-maybe-show-campaign.php
api/index.php
includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
package-lock.json

Release Sep 15

---

api/README.md
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups.php

A proposition: create config file on plugin initialisation, if it does not exist.

feat: create config if not exists

---

.circleci/config.yml
.gitignore
api/classes/class-lightweight-api.php
phpcs.xml
tests/bootstrap.php

Configures CI to run PHP linter.
1. Look at the CI jobs reported in this PR, observe a `lint-php` job
2. Look at the job logs, it should not pass because of existing PHP linting errors (they will be fixed by #213), but it should report the linting errors

CI: linting

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups.php
phpcs.xml

Fixes remaining linting errors
1. Look at the CI output below – the `lint-php` job should complete with success

Fix linting errors

---

api/index.php
includes/class-newspack-popups.php

Alpha release Sep 22

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
tests/test-insertion.php
tests/test-model.php

Closes #217
Closes #231
1. Observe that #217 and #231 are not reproducible on this branch

Fix scroll-triggered popups

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
tests/test-insertion.php
tests/test-model.php

Alpha release Sep 29

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
src/view/style.scss
tests/test-insertion.php
tests/test-model.php

Release Sep 29

---

includes/class-newspack-popups-model.php

Release Sep 30

---

README.md
api/campaigns/class-maybe-show-campaign.php
api/campaigns/class-report-campaign-data.php
api/campaigns/index.php
api/classes/class-lightweight-api.php
api/segmentation/class-segmentation-report.php
api/segmentation/class-segmentation.php
api/setup.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-parse-logs.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
src/editor/index.js
tests/bootstrap.php
tests/test-segmentation.php

Release – Oct. 7

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
src/settings/index.js
src/view/style.scss
tests/bootstrap.php
tests/test-insertion.php
tests/test-model.php

Oct. 20 - Alpha release

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
src/settings/index.js
src/view/style.scss
tests/bootstrap.php
tests/test-insertion.php
tests/test-model.php

Oct. 20 – Release

---

includes/class-newspack-popups.php
src/editor/index.js
src/editor/utils.js

Closes #72.
1. Observe #72 is fixed

Fix setting sitewide default

---

composer.json
composer.lock

Closes #172.
1. Run `composer validate`
2. Observe it's valid

Chore: composer package update

---

composer.json
composer.lock

Composer package update
1. Look at the CI output below, all should pass

Chore: update composer package

---

api/campaigns/class-maybe-show-campaign.php
api/campaigns/class-report-campaign-data.php
api/classes/class-lightweight-api.php
tests/test-api.php
tests/test-segmentation.php

Fixes two cacheing issues (cacheing added in #238) and adds tests to prove it.
Since there are not features depending on this yet, please rely on tests added here.

Fix cacheing issues

---

api/campaigns/class-maybe-show-campaign.php
api/campaigns/class-report-campaign-data.php
api/campaigns/index.php
api/classes/class-lightweight-api.php
api/segmentation/class-segmentation-client-data.php
api/segmentation/class-segmentation-report.php
api/segmentation/index.php
api/setup.php
composer.json
composer.lock
includes/class-newspack-popups-donations.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
phpunit.xml.dist
src/editor/PopupPreview.js
src/editor/index.js
src/editor/style.scss
src/editor/utils.js
tests/bootstrap.php
tests/test-api.php
tests/test-segmentation.php

Alpha release Oct 27

---

api/classes/class-lightweight-api.php

Alpha release Oct 28

---

api/classes/class-lightweight-api.php

Release Oct 28

---

src/view/index.js

Closes #200.
Closes #257.
1. Create a campaign with a newsletter signup form
2. On `master`, 
3. observe that this campaign cannot be permanently dismissed on a non-AMP page
3. observe that signing up for the newsletter does not dismiss the campaign permanently
5. Observe both issues resolved

Fix non-AMP issues

---

api/campaigns/class-maybe-show-campaign.php
api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-settings.php
src/settings/index.js
src/view/index.js
tests/bootstrap.php
tests/test-api.php

Alpha release Oct 29

---

api/campaigns/class-maybe-show-campaign.php
api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-settings.php
src/settings/index.js
src/view/index.js
tests/bootstrap.php
tests/test-api.php

Release Oct 29

---

api/campaigns/class-maybe-show-campaign.php
tests/test-api.php

Closes #249
Closes #250
_Follow testing steps in https://github.com/Automattic/newspack-plugin/pull/693_

Handle subscription, donation segmentation

---

api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups.php
src/editor/index.js
src/editor/utils.js
src/settings/index.js
tests/test-api.php
tests/test-model.php

Alpha release Nov 11

---

api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups.php
src/editor/index.js
src/editor/utils.js
src/settings/index.js
tests/test-api.php
tests/test-model.php

Release Nov 11

---

api/setup.php
includes/class-newspack-popups.php

Alpha release Nov 24

---

api/campaigns/class-maybe-show-campaign.php
api/campaigns/segmentation-utils.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-segmentation.php

Compute segment size based on provided configuration, for use in Newspack Plugin. 
Closes #272 
1. Follow testing steps in https://github.com/Automattic/newspack-plugin/pull/709

Compute segment size

---

api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php

Adds handling of a referrer-based segment.
1. Follow testing steps in https://github.com/Automattic/newspack-plugin/pull/708

Handle referrer segmentation

---

includes/class-newspack-popups.php

Closes #333
1. Observe #333 is not reproducible

Do create config on the atomic platform

---

src/editor/style.scss

Closes #337.
1. Add or edit a campaign
2. Observe it cannot be set to private or password protected (in "Status & visibility" sidebar panel)

Hide post visibility selector in the editor

---

api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
tests/test-api.php
tests/test-segmentation.php

Adds handling of session post read count segmentation criterion.
1. Follow testing steps in https://github.com/Automattic/newspack-plugin/pull/750

Segmentation: session post read count

---

api/campaigns/class-maybe-show-campaign.php

Add handling of segmentation based on favourite categories list. If a reader's favourite category (by most articles read) is in the segment's list
1. Follow testing steps in https://github.com/Automattic/newspack-plugin/pull/707

Handle favourite categories segment

---

.circleci/config.yml
api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
api/segmentation/class-segmentation.php
includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-view-as.php
includes/class-newspack-popups.php
src/editor/SegmentationSidebar.js
src/editor/StatusSidebar.js
tests/test-api.php
tests/test-segmentation.php

Alpha Test

---

.circleci/config.yml

Testing release job using changes from https://github.com/Automattic/newspack-plugin/pull/448

Alpha release – Jan. 4

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups.php

Complete testing instructions in https://github.com/Automattic/newspack-plugin/pull/767

feat: support for campaign groups in campaigns wizard

---

.circleci/config.yml

Alpha Vendor Directory Test

---

.circleci/config.yml

Alpha release Jan 11

---

src/view/index.js

Fixes an issue occuring on site without GA configured.
1. Build the plugin from `master` and install on a fresh site, with no other plugins
2. Observe and error being thrown in the JS console on page load
3. Switch to this branch and rebuild, observe no error thrown

Fix: handle no GA id

---

api/campaigns/class-maybe-show-campaign.php
tests/test-api.php

Closes #379.
1. Observe #379 is not reproducible

Fix segmentation and frequency conflict

---

api/campaigns/class-maybe-show-campaign.php
src/view/index.js
tests/test-api.php

Alpha release Jan 12

---

api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
tests/test-api.php

Alpha release (3) Jan 12

---

api/campaigns/class-maybe-show-campaign.php
api/segmentation/class-segmentation.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
tests/test-api.php
tests/test-insertion.php
tests/test-segmentation.php

Alpha release Jan 14

---

api/campaigns/class-campaign-data-utils.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/EditorAdditions.js
src/editor/FrequencySidebar.js
src/editor/StatusSidebar.js
src/view/style.scss
tests/test-api.php
tests/test-insertion.php
tests/test-model.php

Alpha release Jan 20

---

.circleci/config.yml
api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
api/segmentation/class-segmentation.php
includes/class-newspack-popups-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups-view-as.php
includes/class-newspack-popups.php
src/editor/EditorAdditions.js
src/editor/FrequencySidebar.js
src/editor/SegmentationSidebar.js
src/editor/StatusSidebar.js
src/view/index.js
src/view/style.scss
src/view/utils/index.js
src/view/utils/index.test.js
tests/test-api.php
tests/test-insertion.php
tests/test-model.php
tests/test-segmentation.php

Release Jan 20

---

includes/class-newspack-popups.php

Release January 21 (bugfix)

---

includes/class-newspack-popups.php

Release January 22 (bugfix)

---

api/campaigns/class-campaign-data-utils.php
tests/test-api.php

Closes #386 
Follow testing steps in https://github.com/Automattic/newspack-plugin/pull/831

Referrer exclusion segmentation

---

api/campaigns/class-campaign-data-utils.php
package-lock.json
package.json
tests/test-api.php

Alpha release Jan 26

---

api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
src/settings/index.js
src/settings/style.scss
tests/test-insertion.php

Closes #377 .
_Follow testing steps in https://github.com/Automattic/newspack-plugin/pull/829_

Handle setting donor status by visiting a page

---

api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
src/settings/index.js
src/settings/style.scss
tests/test-insertion.php

Alpha release Jan 28

---

api/campaigns/class-campaign-data-utils.php
api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
package-lock.json
package.json
src/settings/index.js
src/settings/style.scss
tests/test-api.php
tests/test-insertion.php

Release Jan 28

---

includes/class-newspack-popups-inserter.php

Release Jan 29

---

includes/class-newspack-popups.php

Description and testing notes in https://github.com/Automattic/newspack-plugin/pull/833

feat: campaign management functions

---

includes/class-newspack-popups.php

Two additional features needed to improve routing in https://github.com/Automattic/newspack-plugin/pull/833. Full description and testing instructions in https://github.com/Automattic/newspack-plugin/pull/833.

feat: create campaign function

---

api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
src/view/style.scss

Alpha release Feb 10

---

includes/class-newspack-popups-model.php

Release Feb 16

---

includes/class-newspack-popups-inserter.php

Alpha release Feb 23

---

includes/class-newspack-popups-segmentation.php

Alpha release Feb 24

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-segmentation.php

Release Feb 24

---

README.md
api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
src/editor/SegmentationSidebar.js
src/editor/style.scss
tests/bootstrap.php
tests/test-api.php

Alpha release Mar 02

---

README.md
api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
src/editor/SegmentationSidebar.js
src/editor/style.scss
tests/bootstrap.php
tests/test-api.php

Release Mar 02

---

README.md
api/README.md
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-segmentation.php

Release Mar 09

---

includes/class-newspack-popups-inserter.php

Alpha release Mar 12

---

includes/class-newspack-popups-inserter.php

Hotfix release Mar 12

---

api/classes/class-lightweight-api.php
api/segmentation/class-segmentation-custom-ga-config.php
api/segmentation/class-segmentation.php
includes/class-newspack-popups-segmentation.php

Alpha release Mar 16

---

api/classes/class-lightweight-api.php
api/segmentation/class-segmentation-custom-ga-config.php
api/segmentation/class-segmentation.php
includes/class-newspack-popups-segmentation.php

Release Mar 16

---

includes/class-newspack-popups-model.php

Closes #496.
_Testing steps in https://github.com/Automattic/newspack-plugin/pull/914_

Leaner GA config

---

.circleci/config.yml
api/campaigns/class-maybe-show-campaign.php
api/campaigns/class-report-campaign-data.php
api/classes/class-lightweight-api.php
tests/test-api.php

Alpha release Mar 23

---

src/blocks/custom-placement/edit.js
src/editor/Sidebar.js
src/editor/style.scss

Release Mar 30

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
tests/test-insertion.php

Fixes a bug
1. On `master`, create a prompt and set a tag on it
2. Visit a post with no tags, observe that the prompt is displayed anyway
3. Switch to this branch, observe the prompt is not displayed

Fix tag filtering

---

includes/class-newspack-popups-inserter.php

Since Text Widget's options are store in `text_widget` option, retrieving prompts displayed in the widgets can be simplified.
Closes #470.
1. Add prompts in widgets
2. Visit a page on which these prompts would be displayed only in widget areas (e.g. category archive)
3. Verify the prompts are displayed

Retrieve widget popups ids from options

---

api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-custom-placements.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
tests/bootstrap.php
tests/test-api.php
tests/test-insertion.php
tests/wp-unittestcase-pagewithpopups.php

Alpha release Apr 06

---

api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-custom-placements.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
tests/bootstrap.php
tests/test-api.php
tests/test-insertion.php
tests/wp-unittestcase-pagewithpopups.php

Release Apr 06

---

includes/class-newspack-popups-inserter.php
tests/test-insertion.php

Alpha release Apr 08

---

includes/class-newspack-popups-inserter.php
tests/test-insertion.php

A new release to fix a bug that affects inline prompts for many sites who use tags on posts and pages.

Hotfix release Apr 08

---

api/classes/class-lightweight-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/Preview.js
src/editor/Sidebar.js
src/editor/utils.js
src/view/style.scss
tests/test-insertion.php
tests/test-model.php
tests/wp-unittestcase-pagewithpopups.php

Alpha release Apr 13

---

api/classes/class-lightweight-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/editor/Preview.js
src/editor/Sidebar.js
src/editor/utils.js
src/view/style.scss
tests/test-insertion.php
tests/test-model.php
tests/wp-unittestcase-pagewithpopups.php

Release Apr 13

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php

Closes #526 
1. On `master`, create a prompt that would appear on a post, and also insert it using a shortcode in a widget area
2. Observe that the payload to the `GET /api/campaigns/index.php` endpoint has the prompt duplicated under `popups` key
3. Switch to this branch, observe the prompt data not duplicated 
4. Observe #526 fixed

Assorted fixes

---

includes/class-newspack-popups-segmentation.php
tests/test-api.php

Closes #491.
Observe that #491 is not reproducible

Filter out non-existing categories in segments

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
src/view/style.scss
tests/test-api.php

Alpha release Apr 27

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
src/view/index.js
src/view/style.scss
tests/test-api.php

Release Apr 27

---

api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
tests/test-api.php

Alpha release May 04

---

api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
tests/test-api.php

Release May 04

---

includes/class-newspack-popups-model.php

Alpha release May 13

---

includes/class-newspack-popups-model.php

Release May 13

---

tests/test-e2e.php
tests/test-insertion.php
tests/test-segmentation.php
tests/wp-unittestcase-pagewithpopups.php

Alpha release May 18

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-custom-placements.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
package-lock.json
package.json
src/blocks/index.js
src/blocks/single-prompt/block.json
src/blocks/single-prompt/edit.js
src/blocks/single-prompt/editor.scss
src/blocks/single-prompt/index.js
src/blocks/single-prompt/view.php
src/editor/Sidebar.js
src/editor/utils.js
tests/test-blocks.php
tests/test-insertion.php

Alpha release May 25

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-custom-placements.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
package-lock.json
package.json
src/blocks/index.js
src/blocks/single-prompt/block.json
src/blocks/single-prompt/edit.js
src/blocks/single-prompt/editor.scss
src/blocks/single-prompt/index.js
src/blocks/single-prompt/view.php
src/editor/Sidebar.js
src/editor/utils.js
tests/test-blocks.php
tests/test-e2e.php
tests/test-insertion.php
tests/test-segmentation.php
tests/wp-unittestcase-pagewithpopups.php

Release May 25

---

package-lock.json
package.json

Updates `newspack-components` to v1.6.0, which contains some improvements to the `AutocompleteWithSuggestions` component used by the Single Prompt block.
No functional changes, just make sure the Single Prompt block works as expected in the editor.

chore: update newspack-components

---

tests/test-insertion.php

Fixes the CI unit tests. Previously this was using the `assertStringNotContainsString` method which is not available on the version of PHPUnit our CI uses. I've replaced it with a functionally identical check that doesn't use the method.
1. `phpunit` - observe no failing tests.
2. This PR should pass the CI checks below.

Update unit test for compatibility with our CI infra

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
package-lock.json
package.json
src/editor/Duplicate.js
src/editor/style.scss
src/editor/utils.js

Alpha release Jun 30

---

includes/class-newspack-popups-api.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
package-lock.json
package.json
src/editor/Duplicate.js
src/editor/style.scss
src/editor/utils.js

Release Jun 30

---

api/setup.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
src/editor/Sidebar.js

Alpha release Jul 19

---

api/setup.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
src/editor/Sidebar.js

Release Jul 19

---

includes/class-newspack-popups.php
src/editor/FrequencySidebar.js

Closes #428.
Observe #428 irreproducible.

feat: sanitize utm suppression setting

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
src/editor/FrequencySidebar.js
tests/test-segmentation.php

Alpha release Jul 27

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
src/editor/FrequencySidebar.js
tests/test-segmentation.php

Release Jul 27

---

includes/class-newspack-popups-donations.php

Fixes an issue that might arise after a site is moved to a new domain.
1. On a site configured with WooCommerce as the donations handler, visit the WC webhooks settings (`/wp-admin/admin.php?page=wc-settings&tab=advanced&section=webhooks`)
2. There should be a webhook with title "Sync to Newspack Popups on order checkout"
3. Change the domain in webhook's delivery URL directly in the database (to mimick an unfortunate post-migration state) (in `wp_wc_webhooks` table)
4. Refresh the webhook settings page, observe the webhook has the correct URL and name updated to "Sync to Newspack Campaigns"
5. Remove the webhook and observe it's still there (it's created when loading the admin panel)

fix(donations): update WC webhook if needed

---

includes/class-newspack-popups-donations.php
includes/class-newspack-popups-model.php

Alpha release Aug 10

---

includes/class-newspack-popups-donations.php
includes/class-newspack-popups-model.php

Release Aug 10

---

src/view/utils/index.js

Alpha release Aug 17

---

src/view/utils/index.js

Release Aug 17

---

includes/class-newspack-popups-model.php

Alpha release Sep 07

---

includes/class-newspack-popups-model.php

Release Sep 08

---

api/segmentation/class-segmentation-client-data.php

Alpha release Sep 28

---

api/segmentation/class-segmentation-client-data.php

Release Sep 28

---

includes/class-newspack-popups-segmentation.php

Alpha release Oct 05

---

api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-segmentation.php
tests/test-api.php

Alpha release Nov 02

---

src/editor/Preview.js

Adds correct preview URL for single-prompt preview.
1. Edit a prompt, set placement to "In archive pages", click "Preview" in "Status & Visibility" sidebar panel 
2. Observe the preview is using an archive page URL
3. Switch to "In article content" placement, observe the preview is using single post URL

feat(editor): handle archive placement in preview

---

includes/class-newspack-popups-model.php
src/editor/Preview.js
src/view/index.js

Alpha release Nov 09

---

includes/class-newspack-popups-model.php
src/editor/Preview.js
src/view/index.js

Release Nov 09

---

.circleci/config.yml
api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
package-lock.json
package.json
src/editor/AdvancedSidebar.js
src/editor/EditorAdditions.js
src/editor/PositionPlacementControl.js
src/editor/Sidebar.js
src/editor/index.js
src/editor/style.scss
src/editor/utils.js
src/view/style.scss
tests/test-insertion.php
tests/test-model.php

Alpha release Nov 16

---

.circleci/config.yml
CHANGELOG.md
api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
newspack-popups.php
package-lock.json
package.json
src/editor/AdvancedSidebar.js
src/editor/EditorAdditions.js
src/editor/PositionPlacementControl.js
src/editor/Sidebar.js
src/editor/index.js
src/editor/style.scss
src/editor/utils.js
src/view/style.scss
tests/test-insertion.php
tests/test-model.php

Release Nov 18

---

includes/class-newspack-popups-inserter.php
tests/test-content-intertion.php

Alpha release Nov 18

---

CHANGELOG.md
includes/class-newspack-popups-inserter.php
newspack-popups.php
package-lock.json
package.json
tests/test-content-intertion.php

Release Nov 30

---

api/setup.php

Alpha release Dec 01

---

CHANGELOG.md
api/setup.php
newspack-popups.php
package-lock.json
package.json

Release Dec 01

---

includes/class-newspack-popups-inserter.php
tests/test-content-intertion.php

Alpha release Dec 02

---

CHANGELOG.md
includes/class-newspack-popups-inserter.php
newspack-popups.php
package-lock.json
package.json
tests/test-content-intertion.php

Release Dec 02

---

includes/class-newspack-popups-settings.php

Ensures that the "Donor landing page" dropdown only shows pages, even if another plugin is runs a `pre_get_posts` callback to add additional post types. Generally, query alterations like this should be done in very specific scenarios, such as only on the front-end and only with specific query params, but occasionally some plugins alter the query without doing the necessary checks to ensure that the query isn't altered when it shouldn't be.
1. Temporarily add a callback to alter the query in your theme's `functions.php`. You can use any post type, but I'm using the Campaigns CPT in this example:
```php
function newspack_test_pre_get_posts( $query ) {
$existing_post_types = $query->get( 'post_type' );
if ( empty( $existing_post_types ) ) {
$existing_post_types = [ 'post' ];
}
if ( ! …
```

fix: prevent non-page post types from appearing in settings dropdown

---

.circleci/config.yml
.distignore
CHANGELOG.md
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups.php
newspack-popups.php
package-lock.json
package.json
src/editor/Preview.js
src/editor/Sidebar.js
src/editor/utils.js
tests/test-content-insertion.php
tests/test-model.php

Release Mar 08

---

includes/class-newspack-popups-segmentation.php

#814 tightened the criteria for who is considered a donor for segmentation purposes, by checking whether WooCommerce customers have purchased a Newspack Donation product before segmenting them as donors. However, some publishers have additional WooCommerce membership products outside of Newspack Donations that they consider to be donations. Members who have purchased one of these site-specific products should also be segmented as donors.
This PR adds a filter to the segmentation logic that lets other plugins add other product IDs to be considered as donations. Any customer who has bought either a Newspack Donation product or one of these additional products will be segmented as a donor.
1. Check out this branch. Make sure you have a segment targeted to donors only, and a prompt published …

feat(segmentation): add filter to designate additional product IDs as donations

---

includes/class-newspack-popups-settings.php

Closes https://github.com/Automattic/newspack-plugin/issues/1559
Also removes a duplicated line of code.
1. Observe that https://github.com/Automattic/newspack-plugin/issues/1559 is not reproducible

fix: donation landing page setting

---

CHANGELOG.md
includes/class-newspack-popups-segmentation.php
newspack-popups.php
package-lock.json
package.json

Release Mar 22

---

includes/class-newspack-popups-model.php

Alpha release Apr 05

---

CHANGELOG.md
api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
composer.lock
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups.php
newspack-popups.php
package-lock.json
package.json
src/editor/DismissSidebar.js
src/editor/EditorAdditions.js
src/editor/Sidebar.js
src/editor/utils.js
tests/test-api.php
tests/test-insertion.php
tests/test-model.php

Release Apr 05

---

includes/class-newspack-popups-settings.php

Update text in settings section to describe current behaviour of plugin as per [documentation](https://newspack.pub/support/campaigns/settings/)
- Permanently dismisssed rather than dismissed
1. Check out this branch
2. Make sure that updated text is reflected in settings section
Description: Suppress newsletter prompts if permanently dismissed
Help: Automatically suppress any dismissible prompt that contains a newsletter signup block if at least one prompt with a signup block has been permanently dismissed.

Update text in settings section

---

composer.lock
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-settings.php
package-lock.json
package.json
src/editor/Sidebar.js

Alpha release Apr 18

---

includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
tests/test-content-insertion.php

Alpha release Apr 20

---

CHANGELOG.md
composer.lock
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-settings.php
newspack-popups.php
package-lock.json
package.json
src/editor/Sidebar.js
tests/test-content-insertion.php

Release Apr 20

---

api/classes/class-lightweight-api.php
package-lock.json
package.json
tests/test-api.php

Alpha release May 19

---

.circleci/config.yml
includes/class-newspack-popups.php
package-lock.json
package.json
src/view/index.js
src/view/utils/index.js

Alpha release Jun 16

---

src/view/style.scss

Makes the padding smaller on smaller viewports. 
1. Insert an overlay prompt
2. Observe the padding is smaller on smaller viewports

feat(styling): smaller padding on smaller viewports

---

api/classes/class-lightweight-api.php

Alpha release Jul 18

---

api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-donations.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-newsletters.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
src/view/style.scss
tests/test-api.php

Alpha release Aug 05

---

CHANGELOG.md
api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
api/segmentation/class-segmentation-client-data.php
includes/class-newspack-popups-donations.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-newsletters.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
newspack-popups.php
package-lock.json
package.json
src/view/style.scss
tests/test-api.php

Release Aug 16

---

includes/class-newspack-popups-inserter.php
src/editor/AdvancedSidebar.js

Alpha release Aug 16

---

composer.lock
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-newsletters.php
includes/class-newspack-popups.php
src/editor/AdvancedSidebar.js
src/view/analytics.js
src/view/animation.js
src/view/bind.js
src/view/form.js
src/view/index.js
src/view/position-observer.js
src/view/store.js
src/view/style.scss
src/view/utils/index.js
tests/test-model.php

Alpha release Sep 06

---

api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
includes/class-newspack-popups-donations.php
includes/class-newspack-popups-segmentation.php
tests/test-segmentation-criteria.php
tests/test-segmentation.php

Adds "former donor" segmentation handling, and receiving data about a cancelled recurring donation.
_Follow testing steps in https://github.com/Automattic/newspack-plugin/pull/1966_

Segmentation: handle former donor

---

includes/class-newspack-popups-inserter.php
src/view/access.js
src/view/access.scss
src/view/index.js
src/view/utils/index.js

Closes #193
Closes #880
Closes #749
Closes #170
Closes #569
1. Set up a site with a few prompts
2. Test without AMP
3. Observe the appropriate prompts hidden and displayed, according to the segmentation and view logic
4. Observe that the AMP runtime JS files are not loaded
5. Observe that #880, #749, #170, and #569 are not reproducible anymore

feat: polyfill amp-access script

---

CHANGELOG.md
composer.lock
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-newsletters.php
includes/class-newspack-popups.php
newspack-popups.php
package-lock.json
package.json
src/editor/AdvancedSidebar.js
src/view/analytics.js
src/view/animation.js
src/view/bind.js
src/view/form.js
src/view/index.js
src/view/position-observer.js
src/view/store.js
src/view/style.scss
src/view/utils/index.js
tests/test-model.php

Release Sep 14

---

api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
composer.json
composer.lock
includes/class-newspack-popups-donations.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-segmentation.php
src/view/access.js
src/view/access.scss
src/view/index.js
src/view/style.scss
src/view/utils/index.js
tests/bootstrap.php
tests/test-segmentation-criteria.php
tests/test-segmentation.php

Alpha release Sep 16

---

.circleci/config.yml
composer.json
composer.lock
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
src/view/analytics.js
tests/test-api.php
tests/test-blocks.php
tests/test-content-insertion.php
tests/test-insertion.php
tests/test-model.php
tests/test-segmentation-criteria.php
tests/test-segmentation.php
tests/wp-unittestcase-pagewithpopups.php

Alpha release Oct 06

---

.circleci/config.yml

Updates the CI orb to the latest version.

chore: update CircleCI orb

---

.circleci/config.yml
includes/class-newspack-popups-inserter.php
package-lock.json
package.json
src/view/access.js
src/view/access.scss
src/view/index.js
src/view/utils/index.js
src/view/utils/index.test.js

Alpha release Nov 08

---

.circleci/config.yml
CHANGELOG.md
api/campaigns/class-campaign-data-utils.php
api/campaigns/class-maybe-show-campaign.php
api/classes/class-lightweight-api.php
composer.lock
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-segmentation.php
newspack-popups.php
package-lock.json
package.json
src/editor/StylesSidebar.js
src/view/access.js
src/view/access.scss
src/view/index.js
src/view/utils/index.js
src/view/utils/index.test.js
tests/test-api.php
tests/test-e2e.php
tests/test-insertion.php
tests/test-segmentation-criteria.php

Release Nov 14

---

composer.lock
includes/class-newspack-popups-exporter.php
includes/class-newspack-popups-importer.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
includes/cli/class-export.php
includes/cli/class-import.php
includes/schemas/class-campaigns.php
includes/schemas/class-package.php
includes/schemas/class-prompts.php
includes/schemas/class-schema.php
includes/schemas/class-segments.php
newspack-popups.php
package-lock.json
package.json
src/editor/AdvancedSidebar.js
src/editor/utils.js
src/view/admin.js
src/view/admin.scss
tests/bootstrap.php
tests/test-exporter.php
tests/test-importer.php
tests/test-model.php
tests/test-schemas.php
webpack.config.js

Alpha release Dec 16

---

includes/cli/class-import.php
presets/ras-defaults.json
src/editor/Sidebar.js

Alpha release Dec 22

---

CHANGELOG.md
composer.lock
includes/class-newspack-popups-exporter.php
includes/class-newspack-popups-importer.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
includes/cli/class-export.php
includes/cli/class-import.php
includes/schemas/class-campaigns.php
includes/schemas/class-package.php
includes/schemas/class-prompts.php
includes/schemas/class-schema.php
includes/schemas/class-segments.php
newspack-popups.php
package-lock.json
package.json
presets/ras-defaults.json
src/editor/AdvancedSidebar.js
src/editor/Sidebar.js
src/editor/utils.js
src/view/admin.js
src/view/admin.scss
tests/bootstrap.php
tests/test-exporter.php
tests/test-importer.php
tests/test-model.php
tests/test-schemas.php
webpack.config.js

Release Jan 09

---

includes/class-newspack-popups-model.php

Add support to Popups events in the Data Events api
See https://github.com/Automattic/newspack-plugin/pull/2291

feat: add popups ids to forms in prompts

---

includes/class-newspack-popups-model.php

Adds metadata to the donations via donation block. See https://github.com/Automattic/newspack-plugin/pull/2300
See https://github.com/Automattic/newspack-plugin/pull/2300

feat: add popup info to donation block

---

CHANGELOG.md
api/campaigns/class-maybe-show-campaign.php
composer.json
composer.lock
includes/class-newspack-popups-model.php
includes/class-newspack-popups-settings.php
newspack-popups.php
package-lock.json
package.json
src/editor/style.scss
src/settings/style.scss

Release Mar 13

---

.hooks/pre-push
composer.json
package.json

Prevents direct pushes to master.
1. Run composer install
2. Commit something to master
3. try to push and see the error message

fix: pre commit and add pre push

---

src/view/style.scss

Details and instructions at https://github.com/Automattic/newspack-plugin/pull/2414

feat: hide overlays on sign in modal

---

presets/ras-defaults.json

Updates copy and help URLs to the latest.
No functionality changes.

chore: update default RAS copy

---

includes/class-newspack-popups-presets.php

Updates to the RAS preset previewing functionality for https://github.com/Automattic/newspack-plugin/pull/2435.
See instructions in https://github.com/Automattic/newspack-plugin/pull/2435.

fix(ras-defaults): updates for design review feedback

---

includes/class-newspack-popups-presets.php
package-lock.json
package.json

Alpha release May 03

---

presets/ras-defaults.json

Alpha release May 08

---

includes/class-newspack-popups-data-api.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
src/view/analytics/clicked.js
src/view/analytics/dismissed.js
src/view/analytics/ga4.js
src/view/analytics/loaded.js
src/view/analytics/seen.js
src/view/analytics/submitted.js
src/view/index.js
src/view/utils/index.js

Implements front-end GA4 events for prompt interactions.
Closes `1204238302518911/1204668686462485`.
All code in this PR has already been reviewed in smaller PRs, so this just needs a quick review of the changeset.

feat: front-end GA4 events for prompt interactions

---

CHANGELOG.md
includes/class-newspack-popups-presets.php
newspack-popups.php
package-lock.json
package.json

Release Jun 19

---

CHANGELOG.md
composer.json
composer.lock
includes/class-newspack-popups-inserter.php
newspack-popups.php
package-lock.json
package.json

Release Jul 03

---

includes/class-newspack-popups-presets.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php
includes/class-newspack-segments-model.php
includes/schemas/class-segments.php
package-lock.json
package.json
tests/test-importer.php
tests/test-presets.php
tests/test-segments.php
tests/wp-unittestcase-pagewithpopups.php

Alpha release Jul 07

---

composer.lock
includes/class-newspack-popups.php

Alpha release Jul 20

---

src/editor/index.js

Automatically selects the segment when coming from the Campaigns wizard "Add new prompt" button in each segment group:
1. Go to the Campaigns wizard
2. Click on the "Add new prompt" button on any segment
3. Select any placement
4. In the editor, confirm that the segment you clicked on is automatically selected in the "Segments" sidebar control
5. Save and confirm the value is stored
6. Repeat the process and make changes to the selected segments, also hide and show the Segments form, and confirm your changes are kept
NOTE: Toggling the form visibility was forcing a component re-render and thus the `useEffect` call, resetting the selected segments. The workaround I found was to push the browser history and remove the `segment` query var from the URL once it's read for the first time. Maybe …

Fix: auto select segment when coming from the Campaigns wizard

---

composer.lock
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups.php
package-lock.json
package.json
src/editor/index.js
src/view/README.md
src/view/segmentation.js
src/view/utils/segments.js
src/view/utils/segments.test.js

Alpha release Aug 21

---

package-lock.json
package.json
src/settings/style.scss
src/view/style.scss

Alpha release Aug 23

---

CHANGELOG.md
composer.lock
includes/class-newspack-segments-migration.php
newspack-popups.php
package-lock.json
package.json

Release Sep 13

---

includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups.php

Removes GA-related code.
Everything should work as before.

Remove GA custom-dimensions related code

---

includes/class-newspack-popups-inserter.php
package-lock.json
package.json
src/criteria/default/index.php

Alpha release Oct 31

---

composer.lock
includes/class-newspack-popups.php

Alpha release Dec 15

---

CHANGELOG.md
composer.lock
includes/class-newspack-popups.php
newspack-popups.php
package-lock.json
package.json

Release Jan 08

---

composer.json
composer.lock
includes/class-newspack-popups-exporter.php
includes/class-newspack-popups-importer.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups.php
includes/class-newspack-segments-migration.php
includes/cli/class-export.php
includes/cli/class-import.php
includes/cli/class-prune-data.php
includes/schemas/class-campaigns.php
includes/schemas/class-package.php
includes/schemas/class-prompts.php
includes/schemas/class-segments.php
newspack-popups.php
phpcs.xml
tests/bootstrap.php
tests/test-importer.php
tests/test-presets.php

Updates the PHPCS rulesets used to latest versions. 
Smoke test – there should be no changes to users.

chore: update PHPCS rules to latest

---

includes/class-newspack-popups.php
package-lock.json
package.json
tests/wp-unittestcase-pagewithpopups.php

Alpha release Feb 01

---

CHANGELOG.md
composer.json
composer.lock
includes/class-newspack-popups-exporter.php
includes/class-newspack-popups-importer.php
includes/class-newspack-popups-inserter.php
includes/class-newspack-popups-model.php
includes/class-newspack-popups-segmentation.php
includes/class-newspack-popups-settings.php
includes/class-newspack-popups.php
includes/class-newspack-segments-migration.php
includes/cli/class-export.php
includes/cli/class-import.php
includes/cli/class-prune-data.php
includes/schemas/class-campaigns.php
includes/schemas/class-package.php
includes/schemas/class-prompts.php
includes/schemas/class-segments.php
newspack-popups.php
package-lock.json
package.json
phpcs.xml
tests/bootstrap.php
tests/test-importer.php
tests/test-presets.php
tests/wp-unittestcase-pagewithpopups.php

Release Feb 06
